= Cloud Spanner R2DBC Driver Example

This sample application demonstrates performing DDL, DML, and SQL operations on https://cloud.google.com/spanner/[Google Cloud Spanner] using a the Cloud Spanner R2DBC driver.

image:http://gstatic.com/cloudssh/images/open-btn.svg[link=https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fcloud-spanner-r2dbc&cloudshell_open_in_editor=cloud-spanner-r2dbc-samples/cloud-spanner-r2dbc-sample/README.adoc]

== Setup & Configuration
1. Create a Google Cloud Platform Project
2. https://cloud.google.com/docs/authentication/getting-started#creating_the_service_account[Create a service account] with Cloud Spanner permission.
Furnish a new JSON key and then set the credentials using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
+
Alternatively, have the https://cloud.google.com/sdk/[Google Cloud SDK] installed and initialized and logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials].

3. Enable the https://console.cloud.google.com/apis/api/spanner.googleapis.com/overview[Cloud Spanner API]

4. Create a Cloud Spanner instance and database in your project.

== Run the Example
Run the example `main` method in `SampleApplication.java`, passing in three properties: `gcp.project`, `spanner.instance` and `spanner.database`.

For example, to run from command line, you could run the following:

----
./mvnw clean install exec:java -DskipTests -f cloud-spanner-r2dbc-sample/ -Dgcp.project=[PROJECT_ID] -Dspanner.instance=[INSTANCE] -Dspanner.database=[DATABASE]
----

The example creates a table named `BOOKS`.
It then opens a transaction and saves some `BOOKS` rows.
Finally, the example reads the books back from the database.

The application output will show the sequence of operations:

----
 Table creation completed.
 ...
 Insert books transaction committed.
 Insert 3rd book with JSON field transaction committed.
 ...
 Retrieved book: book1; Title: Book One
 Retrieved book: book2; Title: Book Two
 Retrieved book: book3; Title: Book Three; Extra Details: {"rating":9,"series":true}
----

