/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.language.v2.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.language.v2.LanguageServiceClient;
import com.google.cloud.language.v2.LanguageServiceSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link LanguageServiceClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(LanguageServiceClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.language.v2.language-service.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(LanguageServiceSpringProperties.class)
public class LanguageServiceSpringAutoConfiguration {
  private final LanguageServiceSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(LanguageServiceSpringAutoConfiguration.class);

  protected LanguageServiceSpringAutoConfiguration(
      LanguageServiceSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from LanguageService-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultLanguageServiceTransportChannelProvider")
  public TransportChannelProvider defaultLanguageServiceTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return LanguageServiceSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return LanguageServiceSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a LanguageServiceSettings bean configured to use a DefaultCredentialsProvider and the
   * client library's default transport channel provider
   * (defaultLanguageServiceTransportChannelProvider()). It also configures the quota project ID and
   * executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in LanguageServiceSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link LanguageServiceSettings} bean configured with {@link TransportChannelProvider}
   *     bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public LanguageServiceSettings languageServiceSettings(
      @Qualifier("defaultLanguageServiceTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    LanguageServiceSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = LanguageServiceSettings.newHttpJsonBuilder();
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using REST (HTTP/JSON) transport.");
      }
    } else {
      clientSettingsBuilder = LanguageServiceSettings.newBuilder();
    }
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          LanguageServiceSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings analyzeSentimentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.analyzeSentimentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .analyzeSentimentSettings()
          .setRetrySettings(analyzeSentimentRetrySettings);

      RetrySettings analyzeEntitiesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.analyzeEntitiesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .analyzeEntitiesSettings()
          .setRetrySettings(analyzeEntitiesRetrySettings);

      RetrySettings classifyTextRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.classifyTextSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.classifyTextSettings().setRetrySettings(classifyTextRetrySettings);

      RetrySettings moderateTextRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.moderateTextSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.moderateTextSettings().setRetrySettings(moderateTextRetrySettings);

      RetrySettings annotateTextRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.annotateTextSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.annotateTextSettings().setRetrySettings(annotateTextRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry analyzeSentimentRetry = clientProperties.getAnalyzeSentimentRetry();
    if (analyzeSentimentRetry != null) {
      RetrySettings analyzeSentimentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.analyzeSentimentSettings().getRetrySettings(),
              analyzeSentimentRetry);
      clientSettingsBuilder
          .analyzeSentimentSettings()
          .setRetrySettings(analyzeSentimentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for analyzeSentiment from properties.");
      }
    }
    Retry analyzeEntitiesRetry = clientProperties.getAnalyzeEntitiesRetry();
    if (analyzeEntitiesRetry != null) {
      RetrySettings analyzeEntitiesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.analyzeEntitiesSettings().getRetrySettings(),
              analyzeEntitiesRetry);
      clientSettingsBuilder
          .analyzeEntitiesSettings()
          .setRetrySettings(analyzeEntitiesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for analyzeEntities from properties.");
      }
    }
    Retry classifyTextRetry = clientProperties.getClassifyTextRetry();
    if (classifyTextRetry != null) {
      RetrySettings classifyTextRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.classifyTextSettings().getRetrySettings(), classifyTextRetry);
      clientSettingsBuilder.classifyTextSettings().setRetrySettings(classifyTextRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for classifyText from properties.");
      }
    }
    Retry moderateTextRetry = clientProperties.getModerateTextRetry();
    if (moderateTextRetry != null) {
      RetrySettings moderateTextRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.moderateTextSettings().getRetrySettings(), moderateTextRetry);
      clientSettingsBuilder.moderateTextSettings().setRetrySettings(moderateTextRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for moderateText from properties.");
      }
    }
    Retry annotateTextRetry = clientProperties.getAnnotateTextRetry();
    if (annotateTextRetry != null) {
      RetrySettings annotateTextRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.annotateTextSettings().getRetrySettings(), annotateTextRetry);
      clientSettingsBuilder.annotateTextSettings().setRetrySettings(annotateTextRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for annotateText from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a LanguageServiceClient bean configured with LanguageServiceSettings.
   *
   * @param languageServiceSettings settings to configure an instance of client bean.
   * @return a {@link LanguageServiceClient} bean configured with {@link LanguageServiceSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public LanguageServiceClient languageServiceClient(
      LanguageServiceSettings languageServiceSettings) throws IOException {
    return LanguageServiceClient.create(languageServiceSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-language-service";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
