/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.retail.v2.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.retail.v2.CatalogServiceClient;
import com.google.cloud.retail.v2.CatalogServiceSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link CatalogServiceClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(CatalogServiceClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.retail.v2.catalog-service.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(CatalogServiceSpringProperties.class)
public class CatalogServiceSpringAutoConfiguration {
  private final CatalogServiceSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(CatalogServiceSpringAutoConfiguration.class);

  protected CatalogServiceSpringAutoConfiguration(
      CatalogServiceSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from CatalogService-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultCatalogServiceTransportChannelProvider")
  public TransportChannelProvider defaultCatalogServiceTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return CatalogServiceSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return CatalogServiceSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a CatalogServiceSettings bean configured to use a DefaultCredentialsProvider and the
   * client library's default transport channel provider
   * (defaultCatalogServiceTransportChannelProvider()). It also configures the quota project ID and
   * executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in CatalogServiceSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link CatalogServiceSettings} bean configured with {@link TransportChannelProvider}
   *     bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public CatalogServiceSettings catalogServiceSettings(
      @Qualifier("defaultCatalogServiceTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    CatalogServiceSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = CatalogServiceSettings.newHttpJsonBuilder();
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using REST (HTTP/JSON) transport.");
      }
    } else {
      clientSettingsBuilder = CatalogServiceSettings.newBuilder();
    }
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          CatalogServiceSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listCatalogsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listCatalogsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listCatalogsSettings().setRetrySettings(listCatalogsRetrySettings);

      RetrySettings updateCatalogRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateCatalogSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.updateCatalogSettings().setRetrySettings(updateCatalogRetrySettings);

      RetrySettings setDefaultBranchRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setDefaultBranchSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .setDefaultBranchSettings()
          .setRetrySettings(setDefaultBranchRetrySettings);

      RetrySettings getDefaultBranchRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getDefaultBranchSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getDefaultBranchSettings()
          .setRetrySettings(getDefaultBranchRetrySettings);

      RetrySettings getCompletionConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getCompletionConfigSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getCompletionConfigSettings()
          .setRetrySettings(getCompletionConfigRetrySettings);

      RetrySettings updateCompletionConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateCompletionConfigSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .updateCompletionConfigSettings()
          .setRetrySettings(updateCompletionConfigRetrySettings);

      RetrySettings getAttributesConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAttributesConfigSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getAttributesConfigSettings()
          .setRetrySettings(getAttributesConfigRetrySettings);

      RetrySettings updateAttributesConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateAttributesConfigSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .updateAttributesConfigSettings()
          .setRetrySettings(updateAttributesConfigRetrySettings);

      RetrySettings addCatalogAttributeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.addCatalogAttributeSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .addCatalogAttributeSettings()
          .setRetrySettings(addCatalogAttributeRetrySettings);

      RetrySettings removeCatalogAttributeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.removeCatalogAttributeSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .removeCatalogAttributeSettings()
          .setRetrySettings(removeCatalogAttributeRetrySettings);

      RetrySettings replaceCatalogAttributeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.replaceCatalogAttributeSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .replaceCatalogAttributeSettings()
          .setRetrySettings(replaceCatalogAttributeRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listCatalogsRetry = clientProperties.getListCatalogsRetry();
    if (listCatalogsRetry != null) {
      RetrySettings listCatalogsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listCatalogsSettings().getRetrySettings(), listCatalogsRetry);
      clientSettingsBuilder.listCatalogsSettings().setRetrySettings(listCatalogsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listCatalogs from properties.");
      }
    }
    Retry updateCatalogRetry = clientProperties.getUpdateCatalogRetry();
    if (updateCatalogRetry != null) {
      RetrySettings updateCatalogRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateCatalogSettings().getRetrySettings(), updateCatalogRetry);
      clientSettingsBuilder.updateCatalogSettings().setRetrySettings(updateCatalogRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for updateCatalog from properties.");
      }
    }
    Retry setDefaultBranchRetry = clientProperties.getSetDefaultBranchRetry();
    if (setDefaultBranchRetry != null) {
      RetrySettings setDefaultBranchRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setDefaultBranchSettings().getRetrySettings(),
              setDefaultBranchRetry);
      clientSettingsBuilder
          .setDefaultBranchSettings()
          .setRetrySettings(setDefaultBranchRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for setDefaultBranch from properties.");
      }
    }
    Retry getDefaultBranchRetry = clientProperties.getGetDefaultBranchRetry();
    if (getDefaultBranchRetry != null) {
      RetrySettings getDefaultBranchRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getDefaultBranchSettings().getRetrySettings(),
              getDefaultBranchRetry);
      clientSettingsBuilder
          .getDefaultBranchSettings()
          .setRetrySettings(getDefaultBranchRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getDefaultBranch from properties.");
      }
    }
    Retry getCompletionConfigRetry = clientProperties.getGetCompletionConfigRetry();
    if (getCompletionConfigRetry != null) {
      RetrySettings getCompletionConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getCompletionConfigSettings().getRetrySettings(),
              getCompletionConfigRetry);
      clientSettingsBuilder
          .getCompletionConfigSettings()
          .setRetrySettings(getCompletionConfigRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getCompletionConfig from properties.");
      }
    }
    Retry updateCompletionConfigRetry = clientProperties.getUpdateCompletionConfigRetry();
    if (updateCompletionConfigRetry != null) {
      RetrySettings updateCompletionConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateCompletionConfigSettings().getRetrySettings(),
              updateCompletionConfigRetry);
      clientSettingsBuilder
          .updateCompletionConfigSettings()
          .setRetrySettings(updateCompletionConfigRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for updateCompletionConfig from properties.");
      }
    }
    Retry getAttributesConfigRetry = clientProperties.getGetAttributesConfigRetry();
    if (getAttributesConfigRetry != null) {
      RetrySettings getAttributesConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAttributesConfigSettings().getRetrySettings(),
              getAttributesConfigRetry);
      clientSettingsBuilder
          .getAttributesConfigSettings()
          .setRetrySettings(getAttributesConfigRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getAttributesConfig from properties.");
      }
    }
    Retry updateAttributesConfigRetry = clientProperties.getUpdateAttributesConfigRetry();
    if (updateAttributesConfigRetry != null) {
      RetrySettings updateAttributesConfigRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateAttributesConfigSettings().getRetrySettings(),
              updateAttributesConfigRetry);
      clientSettingsBuilder
          .updateAttributesConfigSettings()
          .setRetrySettings(updateAttributesConfigRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for updateAttributesConfig from properties.");
      }
    }
    Retry addCatalogAttributeRetry = clientProperties.getAddCatalogAttributeRetry();
    if (addCatalogAttributeRetry != null) {
      RetrySettings addCatalogAttributeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.addCatalogAttributeSettings().getRetrySettings(),
              addCatalogAttributeRetry);
      clientSettingsBuilder
          .addCatalogAttributeSettings()
          .setRetrySettings(addCatalogAttributeRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for addCatalogAttribute from properties.");
      }
    }
    Retry removeCatalogAttributeRetry = clientProperties.getRemoveCatalogAttributeRetry();
    if (removeCatalogAttributeRetry != null) {
      RetrySettings removeCatalogAttributeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.removeCatalogAttributeSettings().getRetrySettings(),
              removeCatalogAttributeRetry);
      clientSettingsBuilder
          .removeCatalogAttributeSettings()
          .setRetrySettings(removeCatalogAttributeRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for removeCatalogAttribute from properties.");
      }
    }
    Retry replaceCatalogAttributeRetry = clientProperties.getReplaceCatalogAttributeRetry();
    if (replaceCatalogAttributeRetry != null) {
      RetrySettings replaceCatalogAttributeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.replaceCatalogAttributeSettings().getRetrySettings(),
              replaceCatalogAttributeRetry);
      clientSettingsBuilder
          .replaceCatalogAttributeSettings()
          .setRetrySettings(replaceCatalogAttributeRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for replaceCatalogAttribute from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a CatalogServiceClient bean configured with CatalogServiceSettings.
   *
   * @param catalogServiceSettings settings to configure an instance of client bean.
   * @return a {@link CatalogServiceClient} bean configured with {@link CatalogServiceSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public CatalogServiceClient catalogServiceClient(CatalogServiceSettings catalogServiceSettings)
      throws IOException {
    return CatalogServiceClient.create(catalogServiceSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-catalog-service";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
