/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.compute.v1.spring;

import com.google.api.core.BetaApi;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.CredentialsSupplier;
import com.google.cloud.spring.core.Retry;
import javax.annotation.Generated;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/** Provides default property values for Instances client bean */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@ConfigurationProperties("com.google.cloud.compute.v1.instances")
public class InstancesSpringProperties implements CredentialsSupplier {
  /** OAuth2 credentials to authenticate and authorize calls to Google Cloud Client Libraries. */
  @NestedConfigurationProperty
  private final Credentials credentials =
      new Credentials(
          "https://www.googleapis.com/auth/compute",
          "https://www.googleapis.com/auth/cloud-platform");
  /** Quota project to use for billing. */
  private String quotaProjectId;
  /** Number of threads used for executors. */
  private Integer executorThreadCount;
  /** Allow override of retry settings at service level, applying to all of its RPC methods. */
  @NestedConfigurationProperty private Retry retry;
  /**
   * Allow override of retry settings at method-level for aggregatedList. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry aggregatedListRetry;
  /**
   * Allow override of retry settings at method-level for get. If defined, this takes precedence
   * over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getRetry;
  /**
   * Allow override of retry settings at method-level for getEffectiveFirewalls. If defined, this
   * takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getEffectiveFirewallsRetry;
  /**
   * Allow override of retry settings at method-level for getGuestAttributes. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getGuestAttributesRetry;
  /**
   * Allow override of retry settings at method-level for getIamPolicy. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getIamPolicyRetry;
  /**
   * Allow override of retry settings at method-level for getScreenshot. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getScreenshotRetry;
  /**
   * Allow override of retry settings at method-level for getSerialPortOutput. If defined, this
   * takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getSerialPortOutputRetry;
  /**
   * Allow override of retry settings at method-level for getShieldedInstanceIdentity. If defined,
   * this takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getShieldedInstanceIdentityRetry;
  /**
   * Allow override of retry settings at method-level for list. If defined, this takes precedence
   * over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listRetry;
  /**
   * Allow override of retry settings at method-level for listReferrers. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listReferrersRetry;
  /**
   * Allow override of retry settings at method-level for sendDiagnosticInterrupt. If defined, this
   * takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry sendDiagnosticInterruptRetry;
  /**
   * Allow override of retry settings at method-level for setIamPolicy. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry setIamPolicyRetry;
  /**
   * Allow override of retry settings at method-level for testIamPermissions. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry testIamPermissionsRetry;

  @Override
  public Credentials getCredentials() {
    return this.credentials;
  }

  public String getQuotaProjectId() {
    return this.quotaProjectId;
  }

  public void setQuotaProjectId(String quotaProjectId) {
    this.quotaProjectId = quotaProjectId;
  }

  public Integer getExecutorThreadCount() {
    return this.executorThreadCount;
  }

  public void setExecutorThreadCount(Integer executorThreadCount) {
    this.executorThreadCount = executorThreadCount;
  }

  public Retry getRetry() {
    return this.retry;
  }

  public void setRetry(Retry retry) {
    this.retry = retry;
  }

  public Retry getAggregatedListRetry() {
    return this.aggregatedListRetry;
  }

  public void setAggregatedListRetry(Retry aggregatedListRetry) {
    this.aggregatedListRetry = aggregatedListRetry;
  }

  public Retry getGetRetry() {
    return this.getRetry;
  }

  public void setGetRetry(Retry getRetry) {
    this.getRetry = getRetry;
  }

  public Retry getGetEffectiveFirewallsRetry() {
    return this.getEffectiveFirewallsRetry;
  }

  public void setGetEffectiveFirewallsRetry(Retry getEffectiveFirewallsRetry) {
    this.getEffectiveFirewallsRetry = getEffectiveFirewallsRetry;
  }

  public Retry getGetGuestAttributesRetry() {
    return this.getGuestAttributesRetry;
  }

  public void setGetGuestAttributesRetry(Retry getGuestAttributesRetry) {
    this.getGuestAttributesRetry = getGuestAttributesRetry;
  }

  public Retry getGetIamPolicyRetry() {
    return this.getIamPolicyRetry;
  }

  public void setGetIamPolicyRetry(Retry getIamPolicyRetry) {
    this.getIamPolicyRetry = getIamPolicyRetry;
  }

  public Retry getGetScreenshotRetry() {
    return this.getScreenshotRetry;
  }

  public void setGetScreenshotRetry(Retry getScreenshotRetry) {
    this.getScreenshotRetry = getScreenshotRetry;
  }

  public Retry getGetSerialPortOutputRetry() {
    return this.getSerialPortOutputRetry;
  }

  public void setGetSerialPortOutputRetry(Retry getSerialPortOutputRetry) {
    this.getSerialPortOutputRetry = getSerialPortOutputRetry;
  }

  public Retry getGetShieldedInstanceIdentityRetry() {
    return this.getShieldedInstanceIdentityRetry;
  }

  public void setGetShieldedInstanceIdentityRetry(Retry getShieldedInstanceIdentityRetry) {
    this.getShieldedInstanceIdentityRetry = getShieldedInstanceIdentityRetry;
  }

  public Retry getListRetry() {
    return this.listRetry;
  }

  public void setListRetry(Retry listRetry) {
    this.listRetry = listRetry;
  }

  public Retry getListReferrersRetry() {
    return this.listReferrersRetry;
  }

  public void setListReferrersRetry(Retry listReferrersRetry) {
    this.listReferrersRetry = listReferrersRetry;
  }

  public Retry getSendDiagnosticInterruptRetry() {
    return this.sendDiagnosticInterruptRetry;
  }

  public void setSendDiagnosticInterruptRetry(Retry sendDiagnosticInterruptRetry) {
    this.sendDiagnosticInterruptRetry = sendDiagnosticInterruptRetry;
  }

  public Retry getSetIamPolicyRetry() {
    return this.setIamPolicyRetry;
  }

  public void setSetIamPolicyRetry(Retry setIamPolicyRetry) {
    this.setIamPolicyRetry = setIamPolicyRetry;
  }

  public Retry getTestIamPermissionsRetry() {
    return this.testIamPermissionsRetry;
  }

  public void setTestIamPermissionsRetry(Retry testIamPermissionsRetry) {
    this.testIamPermissionsRetry = testIamPermissionsRetry;
  }
}
