primaryBranch: main
releaseType: java-yoshi
handleGHRelease: true
extraFiles: [
  "README.adoc",
  "spring-cloud-generator/scripts/resources/googleapis_modification_string.txt"
]
branches:
  - releaseType: java-yoshi
    handleGHRelease: true
    branch: 3.x
    extraFiles: ["README.adoc"]
