primaryBranch: main
releaseType: java-yoshi
handleGHRelease: true
extraFiles: ["README.adoc"]
branches:
  - releaseType: java-yoshi
    handleGHRelease: true
    branch: 3.x
    extraFiles: ["README.adoc"]
