rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - 'cla/google'
      - 'unitTests (17)'
      - 'unitTests (19)'
      - 'unitTests (21)'
      - 'releaseCheck'
      - 'conventionalcommits.org'
      - 'Build with Sonar'
      - 'parallel-NativeTests (alloydb-sample)'
      - 'parallel-NativeTests (bigquery-sample)'
      - 'parallel-NativeTests (bigquery)'
      - 'parallel-NativeTests (core)'
      - 'parallel-NativeTests (data-firestore)'
      - 'parallel-NativeTests (data-firestore-sample)'
      - 'parallel-NativeTests (datastore)'
      - 'parallel-NativeTests (datastore-basic-sample)'
      - 'parallel-NativeTests (kms)'
      - 'parallel-NativeTests (kms-sample)'
      - 'parallel-NativeTests (logging-sample)'
      - 'parallel-NativeTests (metrics-sample)'
      - 'parallel-NativeTests (pubsub-sample)'
      - 'parallel-NativeTests (pubsub-bus-sample)'
      - 'parallel-NativeTests (pubsub-integration-sample)'
      - 'parallel-NativeTests (secretmanager)'
      - 'parallel-NativeTests (secretmanager-sample)'
      - 'parallel-NativeTests (spanner)'
      - 'parallel-NativeTests (sql-mysql-sample)'
      - 'parallel-NativeTests (sql-postgres-sample)'
      - 'parallel-NativeTests (starter-firestore-sample)'
      - 'parallel-NativeTests (storage)'
      - 'parallel-NativeTests (storage-sample)'
      - 'parallel-NativeTests (trace-sample)'
      - 'parallel-NativeTests (vision)'
      - 'parallel-NativeTests (vision-sample)'
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
  - pattern: 4.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - 'cla/google'
      - 'unitTests (17)'
      - 'unitTests (19)'
      - 'unitTests (21)'
      - 'releaseCheck'
      - 'conventionalcommits.org'
      - 'Build with Sonar'
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
  - pattern: 3.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - 'cla/google'
      - 'unitTests (8)'
      - 'unitTests (11)'
      - 'unitTests (17)'
      - 'releaseCheck'
      - 'conventionalcommits.org'
      - 'Build with Sonar'
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
  - pattern: 2.x
    isAdminEnforced: true
    requiredStatusCheckContexts:
      - 'cla/google'
      - 'unitTests (8)'
      - 'unitTests (11)'
      - 'unitTests (17)'
      - 'releaseCheck'
      - 'conventionalcommits.org'
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
permissionRules:
  - team: cloud-java-team-teamsync
    permission: admin