language: java
git:
  depth: 9999999
jdk:
  - oraclejdk8
dist: trusty
branches:
  only:
    - master
    - test
cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "spring-cloud-gcp"
    token:
      secure: "felzNXKZep7xs8SVxn+bTEOwnk7Wr52AOP+N8IQqlIGpNryw9RfvWN95o9xP0Z8QAuKxaG3OB90q5/ePb0Ml65ot5o/Dw4Mj4CsUOSpjm/438rLTKW2PcMhD1JWXtKPO76vahtqw/YGVKPpjV/95RXPGAAa4JGU1XvoLhFOipq8EiAdJVWiMHYS3kRLQuH7vZmGQVArXgrenSx70c8GQGTQhMvMYEnkQmnYdNovwA9Rpw51CT/Bk1C5Bhs4ipUCesoUagG8dZs+chLU1+1LPiuYryIHRdFeMm4kYsTLpSLfRZwNMI3ReByxSkDVP8xKH9FHmi+ET/0pQ2Y4e4PydONuDHlzHy/eFfO9zwoHlfa5nLZwpuOFre/vZ21ZOUZgeWrJiGUVR7sFlKIfPTgjUkzAT0HLZuf9DcB0vI9RZe+uFEMJZfuIsMIRGbv3aGuXkBpRR32MYyKgWMTNF2qGiRlUZ1ZiU7Bnq3OpnlzxTZrYtEZbO0G8hd+NDKcqQsQBpOQf6PVCBgLGkbl579dH0teDnL3XmYGK4/PIav1coXWtoC2eVc30ZbErj8P7sxKXBTziC/A4Se1W08cMiqKE9VGAIWs74yeJPzyAl8VRRGu5CapVWkVXr0pAhJC33EcaYEA5g2P6MvaCbSspqSidDMjmsSeVYXqjG+jGMpDfCweM="
script:
  # run local tests
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      ./mvnw test sonar:sonar -B -P codecov -Dit.pubsub-emulator -Dsonar.projectKey=SC-GCP-2;
    else
      ./mvnw test -B -P codecov -Dit.pubsub-emulator;
    fi;
  - bash <(curl -s https://codecov.io/bash) -F unittests
  # run GCP integration tests
  - if [ "$INTEGRATION_TEST_FLAGS" != "" ]; then
      ./mvnw test -B -P codecov ${INTEGRATION_TEST_FLAGS} && bash <(curl -s https://codecov.io/bash) -F integration;
    fi;
install:
  - ./mvnw -T 1.5C install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring.profiles.active=spring -P full-checkstyle -B -V
before_install:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      openssl aes-256-cbc -K $encrypted_ad13726c9b2f_key -iv $encrypted_ad13726c9b2f_iv -in travis.tar.gz.enc -out travis.tar.gz -d;
      tar -xzf travis.tar.gz;
      export INTEGRATION_TEST_FLAGS="-Dit.pubsub-emulator=true -Dit.spanner=true -Dit.storage=true -Dit.config=true -Dit.pubsub=true -Dit.logging=true
          -Dit.cloudsql=true -Dit.datastore=true -Dit.trace=true -Dit.kotlin=true -Dit.vision=true -Dit.firestore=true -Dit.bigquery=true -Dit.secretmanager=true
          -Dspring.cloud.gcp.sql.instance-connection-name=spring-cloud-gcp-ci:us-central1:testmysql
          -Dspring.cloud.gcp.sql.database-name=code_samples_test_db
          -Dspring.datasource.password=test
          -Dgcs-resource-test-bucket=gcp-storage-resource-bucket-sample
          -Dgcs-read-bucket=gcp-storage-bucket-sample-input
          -Dgcs-write-bucket=gcp-storage-bucket-sample-output
          -Dgcs-local-directory=/tmp/gcp_integration_tests/integration_storage_sample";
      export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/travis/admin.json;
      export GOOGLE_CLOUD_PROJECT=spring-cloud-gcp-ci;
    fi;
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update --quiet
  - gcloud components install beta pubsub-emulator --quiet
  - gcloud config set project spring-cloud-gcp-ci

