language: java
git:
  depth: 9999999
jdk:
  - oraclejdk8
dist: trusty
branches:
  only:
    - master
    - test
cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "spring-cloud-gcp"
    token:
      secure: "rrofLH3LbPAoubHN8RnWmV3USAxEkNPvqOcgVA5tNqZHwjc2qxgUPY+0ql0OkEIE81pUbqWpwE0XRosfGk744cpzXXP8Jeu+aszzfWFWEk97qvM5vSgHMMYd+Xzrc1oJSIXSw4U+eFRjLiOhvsF3wXeagS7KN97yvvRKm/TCHPcn0++9O8t3ykCqsGGGXkupF5GFKsPXwUg25mg/aIHZonylaOg9M5HonSwaB/5uMgXOEai8SwrxzXZDqtxQDHQfAFwAANvcAZ0tdPdfl/adnZq4PCMAd5O3R9qOR1QFGxutrM3UMSLdR8Df1Z1TvMeatKHka9KmQftQVhZ/mQjdLTPUSsgwwV5Mk2+DXpEZCryDK3rMOzHtRkMAty0tCZKCeg5Zx9a/kniv84XjiEnUdiuMxOY2GtYlzQ+kCET2ydhOAS4fhhvHTmcYtuTn+/TSPIsXppygpQ/SGdGzlzjIQWAg+g6ASB7vxqZBTTc1n468EVRnypCBUqbMlMy3v+GrZj0pytH3Yu/q6xIYCz/yyZ5UFNeBWbbPw3cxVX1n8x8PclRp+jN6XUPSTdNuuwgz0sF541i5Iv5gqGcVbq/zjUtuT0LC4NOmucNTTuOJZvdYW+Z6UWi45FL7qjwtZLZcybj0v4X72FTP9HKgJccwJ3I95KA0/d37Z1y4cbMZTik="
script:
  # run unit tests
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then
      ./mvnw test sonar:sonar -B -P codecov -Dit.pubsub-emulator -Dsonar.projectKey=SC-GCP-2;
    else
      ./mvnw test -B -P codecov -Dit.pubsub-emulator;
    fi;
  - bash <(curl -s https://codecov.io/bash) -F unittests
  # run GCP integration tests
  - if [ "$INTEGRATION_TEST_FLAGS" != "" ]; then
      ./mvnw test -B -P codecov ${INTEGRATION_TEST_FLAGS} && bash <(curl -s https://codecov.io/bash) -F integration;
    fi;
install:
  - ./mvnw -T 1.5C install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring.profiles.active=spring -P full-checkstyle -B -V
before_install:
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      openssl aes-256-cbc -K $encrypted_3c7171117694_key -iv $encrypted_3c7171117694_iv -in travis.tar.gz.enc -out travis.tar.gz -d;
      tar -xzf travis.tar.gz;
      export INTEGRATION_TEST_FLAGS="-Dit.pubsub-emulator=true -Dit.spanner=true -Dit.storage=true -Dit.config=true -Dit.pubsub=true -Dit.logging=true
          -Dit.cloudsql=true -Dit.datastore=true -Dit.trace=true -Dit.kotlin=true -Dit.vision=true -Dit.firestore=true -Dit.bigquery=true -Dit.secretmanager=true
          -Dspring.cloud.gcp.sql.instance-connection-name=spring-cloud-gcp-ci:us-central1:testmysql
          -Dspring.cloud.gcp.sql.database-name=code_samples_test_db
          -Dspring.datasource.password=test
          -Dgcs-resource-test-bucket=gcp-storage-resource-bucket-sample
          -Dgcs-read-bucket=gcp-storage-bucket-sample-input
          -Dgcs-write-bucket=gcp-storage-bucket-sample-output
          -Dgcs-local-directory=/tmp/gcp_integration_tests/integration_storage_sample";
      export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/travis/admin.json;
      export GOOGLE_CLOUD_PROJECT=spring-cloud-gcp-ci;
    fi;
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update --quiet
  - gcloud components install beta pubsub-emulator --quiet
  - gcloud config set project spring-cloud-gcp-ci

