image:https://github.com/GoogleCloudPlatform/spring-cloud-gcp/workflows/Unit%20Tests/badge.svg?branch=main["HEAD Unit Tests", link="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions?query=branch%3Amain+workflow%3A%22Unit+Tests%22"]
image:https://github.com/GoogleCloudPlatform/spring-cloud-gcp/workflows/Integration%20Tests/badge.svg?branch=main["HEAD Integration Tests", link="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions?query=branch%3Amain+workflow%3A%22Integration+Tests%22"]
image:https://github.com/GoogleCloudPlatform/spring-cloud-gcp/workflows/SonarCloud%20Analysis/badge.svg?branch=main["HEAD SonarCloud Analysis", link="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions?query=branch%3Amain+workflow%3A%22SonarCloud+Analysis%22"]
image:https://sonarcloud.io/api/project_badges/measure?project=GoogleCloudPlatform_spring-cloud-gcp&metric=alert_status["Quality Gate Status", link="https://sonarcloud.io/dashboard?id=GoogleCloudPlatform_spring-cloud-gcp"]
:version-6: 6.4.0
:version-5: 5.13.5
:version-4: 4.11.3
:version-3: 3.9.11

// Define the full URL and link text for each version
:url-6: https://googlecloudplatform.github.io/spring-cloud-gcp/{version-6}/reference/html/index.html
:text-6: Spring Framework on Google Cloud {version-6}

:url-5: https://googlecloudplatform.github.io/spring-cloud-gcp/{version-5}/reference/html/index.html
:text-5: Spring Framework on Google Cloud {version-5}

:url-4: https://googlecloudplatform.github.io/spring-cloud-gcp/{version-4}/reference/html/index.html
:text-4: Spring Framework on Google Cloud {version-4}

:url-3: https://googlecloudplatform.github.io/spring-cloud-gcp/{version-3}/reference/html/index.html
:text-3: Spring Framework on Google Cloud {version-3}

----
DEBUGGING ATTRIBUTE VALUES:

version-6 = {version-6}
version-5 = {version-5}

Computed URL for v6: {url-6}
Computed Text for v6: {text-6}

Computed URL for v5: {url-5}
Computed Text for v5: {text-5}
----

== Spring Framework on Google Cloud

This project makes it easy for Spring users to run their applications on Google Cloud.
You can check our project website https://spring.io/projects/spring-cloud-gcp[here].

For a deep dive into the project, refer to the Spring Framework on Google Cloud Reference documentation or Javadocs:

Google Cloud Reference Documentation:

// {x-version-update-start:spring-cloud-gcp:released}
* https://googlecloudplatform.github.io/spring-cloud-gcp/7.3.2/reference/html/index.html[Spring Framework on Google Cloud (Latest)]
// {x-version-update-end}
* {url-6}[{text-6}]
* {url-5}[{text-5}]
* {url-4}[{text-4}]
* {url-3}[{text-3}]

Javadocs: https://googleapis.dev/java/spring-cloud-gcp/latest/index.html

If you prefer to learn by doing, try taking a look at the https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples[Spring Framework on Google Cloud sample applications] or the https://codelabs.developers.google.com/spring[Spring on Google Cloud codelabs].

Currently, this repository provides support for:

* link:spring-cloud-gcp-pubsub[Spring Framework on Google Cloud Pub/Sub, including Spring Integration Channel Adapters]
* link:spring-cloud-gcp-pubsub-stream-binder[Spring Framework on Google Cloud Pub/Sub Stream Binder]
* link:spring-cloud-gcp-storage[Spring Resource Abstraction for Google Cloud Storage, including Spring Integration Channel Adapters]
* link:spring-cloud-gcp-data-spanner[Spring Data Cloud Spanner]
* link:spring-cloud-gcp-data-datastore[Spring Data Cloud Datastore]
* link:spring-cloud-gcp-data-firestore[Spring Data Cloud Firestore]
* link:spring-cloud-gcp-vision[Google Cloud Vision API Template]
* Spring Boot starters
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter[GCP Support]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-config[Google Cloud Config] (Beta)
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-spanner[Google Cloud Spanner]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-datastore[Google Cloud Datastore]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-firestore[Google Cloud Firestore]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-logging[Google Cloud Logging]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-pubsub[Google Cloud Pub/Sub]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-mysql[Google Cloud SQL MySQL]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-postgresql[Google Cloud SQL PostgreSQL]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-storage[Google Cloud Storage]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-secretmanager[Google Secret Manager]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-security-firebase[Firebase Authentication]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-security-iap[Google Cloud IAP Authentication]
** link:spring-cloud-gcp-starters/spring-cloud-gcp-starter-vision[Google Cloud Vision API]

If you have any other ideas, suggestions or bug reports, please use our https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues[GitHub issue tracker] and let us know!

If you want to collaborate in the project, we would also love to get your Pull Requests.
Before you start working on one, please take a look at our link:CONTRIBUTING.md[collaboration manual].

== Compatibility with Spring Project Versions

This project has dependency and transitive dependencies on Spring Projects. The table below outlines the versions of Spring Cloud, Spring Boot and Spring Framework versions that are compatible with certain Spring Framework on Google Cloud version.
|===
| Spring Framework on Google Cloud | Spring Cloud | Spring Boot | Spring Framework | Supported

|7.x
|https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2025.0-Release-Notes[2025.0.x] (Northfields)
|https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.5-Release-Notes[3.5.x]
|https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes[6.2.8 or above]
|Yes

|6.x
|https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2024.0-Release-Notes[2024.0.x] (Moorgate)
|https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.4-Release-Notes[3.4.x]
|https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-6.2-Release-Notes[6.2.0 or above]
|Yes

|5.x
|https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes[2023.0.x] (Leyton)
|https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes[3.2.x]*, https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes[3.3.x]

* Except trace
|https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x#whats-new-in-version-61[6.1.x]
|Yes

|4.x
|https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2022.0-Release-Notes[2022.0.x] (Kilburn)
|https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes[3.0.x], https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes[3.1.x]
|https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x#whats-new-in-version-60[6.0.x]
|No

|3.x
|https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2021.0-Release-Notes[2021.0.x] (Jubilee)
|https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes[2.6.x], https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes[2.7.x]
|https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-5.x#whats-new-in-version-53[5.3.x]
|Yes

|2.x
|https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes[2020.0.x] (Ilford)
|https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes[2.4.x], https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5-Release-Notes[2.5.x]
|https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-5.x#whats-new-in-version-53[5.3.x]
|No
|===
&ast; The Spring Cloud GCP 5.x trace module only supports Spring Boot 3.3.x due to link:https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes#brave-and-zipkin[Boot's major version increment] of its Brave and Zipkin dependencies.

== Spring Initializr

Spring Initializr contains Spring Framework on Google Cloud auto-configuration support through the `GCP Support` entry.

`GCP Messaging` contains the Spring Framework on Google Cloud messaging support with Google Cloud Pub/Sub working out of the box.

Similarly to `GCP Messaging`, `GCP Storage` contains the Google Cloud Storage support with no other dependencies needed.

== Spring Framework on Google Cloud Bill of Materials (BOM)

If you're a Maven user, add our BOM to your pom.xml `<dependencyManagement>` section.
This will allow you to not specify versions for any of the Maven dependencies and instead delegate versioning to the BOM.

// {x-version-update-start:spring-cloud-gcp:released}

[source,xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-dependencies</artifactId>
            <version>7.3.2</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

// {x-version-update-end} 

== Snapshots Repository

We do not publish `SNAPSHOT` versions of the project. If you would like to test out the latest snapshot, please clone this repository and install locally.

== Spring Boot Starters

Spring Boot greatly simplifies the Spring Framework on Google Cloud experience.
Our starters handle the object instantiation and configuration logic so you don't have to.

Every starter depends on the GCP starter to provide critical bits of configuration, like the GCP project ID or OAuth2 credentials location.
You can configure these as properties in, for example, a properties file:

[source]
----
spring.cloud.gcp.project-id=[YOUR_GCP_PROJECT_ID]
spring.cloud.gcp.credentials.location=file:[LOCAL_PRIVATE_KEY_FILE]
spring.cloud.gcp.credentials.scopes=[SCOPE_1],[SCOPE_2],[SCOPE_3]
----

These properties are optional and, if not specified, Spring Boot will attempt to automatically find them for you.
For details on how Spring Boot finds these properties, refer to the link:https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html[documentation].

NOTE: If your app is running on Google App Engine or Google Compute Engine, in most cases, you should omit the `spring.cloud.gcp.credentials.location` property and, instead, let the Spring Framework on Google Cloud Core Starter find the correct credentials for those environments.
