/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.showcase.v1beta1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import com.google.showcase.v1beta1.SequenceServiceClient;
import com.google.showcase.v1beta1.SequenceServiceSettings;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link SequenceServiceClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(SequenceServiceClient.class)
@ConditionalOnProperty(
    value = "com.google.showcase.v1beta1.sequence-service.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(SequenceServiceSpringProperties.class)
public class SequenceServiceSpringAutoConfiguration {
  private final SequenceServiceSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(SequenceServiceSpringAutoConfiguration.class);

  protected SequenceServiceSpringAutoConfiguration(
      SequenceServiceSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from SequenceService-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean. The default is gRPC and will default to it
   * unless the useRest option is supported and provided to use HTTP transport instead
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultSequenceServiceTransportChannelProvider")
  public TransportChannelProvider defaultSequenceServiceTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return SequenceServiceSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return SequenceServiceSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a SequenceServiceSettings bean configured to use a DefaultCredentialsProvider and the
   * client library's default transport channel provider
   * (defaultSequenceServiceTransportChannelProvider()). It also configures the quota project ID and
   * executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in SequenceServiceSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link SequenceServiceSettings} bean configured with {@link TransportChannelProvider}
   *     bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public SequenceServiceSettings sequenceServiceSettings(
      @Qualifier("defaultSequenceServiceTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    SequenceServiceSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = SequenceServiceSettings.newHttpJsonBuilder();
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using REST (HTTP/JSON) transport.");
      }
    } else {
      clientSettingsBuilder = SequenceServiceSettings.newBuilder();
    }
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          SequenceServiceSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings createSequenceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createSequenceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.createSequenceSettings().setRetrySettings(createSequenceRetrySettings);

      RetrySettings createStreamingSequenceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createStreamingSequenceSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .createStreamingSequenceSettings()
          .setRetrySettings(createStreamingSequenceRetrySettings);

      RetrySettings getSequenceReportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getSequenceReportSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getSequenceReportSettings()
          .setRetrySettings(getSequenceReportRetrySettings);

      RetrySettings getStreamingSequenceReportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getStreamingSequenceReportSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getStreamingSequenceReportSettings()
          .setRetrySettings(getStreamingSequenceReportRetrySettings);

      RetrySettings attemptSequenceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.attemptSequenceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .attemptSequenceSettings()
          .setRetrySettings(attemptSequenceRetrySettings);

      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);

      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry createSequenceRetry = clientProperties.getCreateSequenceRetry();
    if (createSequenceRetry != null) {
      RetrySettings createSequenceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createSequenceSettings().getRetrySettings(),
              createSequenceRetry);
      clientSettingsBuilder.createSequenceSettings().setRetrySettings(createSequenceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for createSequence from properties.");
      }
    }
    Retry createStreamingSequenceRetry = clientProperties.getCreateStreamingSequenceRetry();
    if (createStreamingSequenceRetry != null) {
      RetrySettings createStreamingSequenceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createStreamingSequenceSettings().getRetrySettings(),
              createStreamingSequenceRetry);
      clientSettingsBuilder
          .createStreamingSequenceSettings()
          .setRetrySettings(createStreamingSequenceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for createStreamingSequence from properties.");
      }
    }
    Retry getSequenceReportRetry = clientProperties.getGetSequenceReportRetry();
    if (getSequenceReportRetry != null) {
      RetrySettings getSequenceReportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getSequenceReportSettings().getRetrySettings(),
              getSequenceReportRetry);
      clientSettingsBuilder
          .getSequenceReportSettings()
          .setRetrySettings(getSequenceReportRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getSequenceReport from properties.");
      }
    }
    Retry getStreamingSequenceReportRetry = clientProperties.getGetStreamingSequenceReportRetry();
    if (getStreamingSequenceReportRetry != null) {
      RetrySettings getStreamingSequenceReportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getStreamingSequenceReportSettings().getRetrySettings(),
              getStreamingSequenceReportRetry);
      clientSettingsBuilder
          .getStreamingSequenceReportSettings()
          .setRetrySettings(getStreamingSequenceReportRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getStreamingSequenceReport from properties.");
      }
    }
    Retry attemptSequenceRetry = clientProperties.getAttemptSequenceRetry();
    if (attemptSequenceRetry != null) {
      RetrySettings attemptSequenceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.attemptSequenceSettings().getRetrySettings(),
              attemptSequenceRetry);
      clientSettingsBuilder
          .attemptSequenceSettings()
          .setRetrySettings(attemptSequenceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for attemptSequence from properties.");
      }
    }
    Retry listLocationsRetry = clientProperties.getListLocationsRetry();
    if (listLocationsRetry != null) {
      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), listLocationsRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listLocations from properties.");
      }
    }
    Retry getLocationRetry = clientProperties.getGetLocationRetry();
    if (getLocationRetry != null) {
      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), getLocationRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getLocation from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a SequenceServiceClient bean configured with SequenceServiceSettings.
   *
   * @param sequenceServiceSettings settings to configure an instance of client bean.
   * @return a {@link SequenceServiceClient} bean configured with {@link SequenceServiceSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public SequenceServiceClient sequenceServiceClient(
      SequenceServiceSettings sequenceServiceSettings) throws IOException {
    return SequenceServiceClient.create(sequenceServiceSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-sequence-service";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
