/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.metastore.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.metastore.v1.DataprocMetastoreClient;
import com.google.cloud.metastore.v1.DataprocMetastoreSettings;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link DataprocMetastoreClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@ConditionalOnClass(DataprocMetastoreClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.metastore.v1.spring.auto.dataproc-metastore.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(DataprocMetastoreSpringProperties.class)
public class DataprocMetastoreSpringAutoConfiguration {
  private final DataprocMetastoreSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER =
      LogFactory.getLog(DataprocMetastoreSpringAutoConfiguration.class);

  protected DataprocMetastoreSpringAutoConfiguration(
      DataprocMetastoreSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from DataprocMetastore-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Returns the default channel provider. The default is gRPC and will default to it unless the
   * useRest option is provided to use HTTP transport instead
   */
  @Bean
  @ConditionalOnMissingBean
  public TransportChannelProvider defaultDataprocMetastoreTransportChannelProvider() {
    return DataprocMetastoreSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a DataprocMetastoreClient bean configured to use the default credentials provider
   * (obtained with dataprocMetastoreCredentials()) and its default transport channel provider
   * (defaultDataprocMetastoreTransportChannelProvider()). It also configures the quota project ID
   * if provided. It will configure an executor provider in case there is more than one thread
   * configured in the client
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in DataprocMetastoreSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   */
  @Bean
  @ConditionalOnMissingBean
  public DataprocMetastoreSettings dataprocMetastoreSettings(
      @Qualifier("defaultDataprocMetastoreTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    DataprocMetastoreSettings.Builder clientSettingsBuilder =
        DataprocMetastoreSettings.newBuilder()
            .setCredentialsProvider(this.credentialsProvider)
            .setTransportChannelProvider(defaultTransportChannelProvider)
            .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          DataprocMetastoreSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder.setTransportChannelProvider(
          DataprocMetastoreSettings.defaultHttpJsonTransportProviderBuilder().build());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using HTTP transport channel");
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listServicesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listServicesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listServicesSettings().setRetrySettings(listServicesRetrySettings);

      RetrySettings getServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getServiceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getServiceSettings().setRetrySettings(getServiceRetrySettings);

      RetrySettings createServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createServiceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.createServiceSettings().setRetrySettings(createServiceRetrySettings);

      RetrySettings updateServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateServiceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.updateServiceSettings().setRetrySettings(updateServiceRetrySettings);

      RetrySettings deleteServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteServiceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.deleteServiceSettings().setRetrySettings(deleteServiceRetrySettings);

      RetrySettings listMetadataImportsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMetadataImportsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listMetadataImportsSettings()
          .setRetrySettings(listMetadataImportsRetrySettings);

      RetrySettings getMetadataImportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMetadataImportSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getMetadataImportSettings()
          .setRetrySettings(getMetadataImportRetrySettings);

      RetrySettings createMetadataImportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createMetadataImportSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .createMetadataImportSettings()
          .setRetrySettings(createMetadataImportRetrySettings);

      RetrySettings updateMetadataImportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateMetadataImportSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .updateMetadataImportSettings()
          .setRetrySettings(updateMetadataImportRetrySettings);

      RetrySettings exportMetadataRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.exportMetadataSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.exportMetadataSettings().setRetrySettings(exportMetadataRetrySettings);

      RetrySettings restoreServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.restoreServiceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.restoreServiceSettings().setRetrySettings(restoreServiceRetrySettings);

      RetrySettings listBackupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBackupsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listBackupsSettings().setRetrySettings(listBackupsRetrySettings);

      RetrySettings getBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getBackupSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getBackupSettings().setRetrySettings(getBackupRetrySettings);

      RetrySettings createBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createBackupSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.createBackupSettings().setRetrySettings(createBackupRetrySettings);

      RetrySettings deleteBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteBackupSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.deleteBackupSettings().setRetrySettings(deleteBackupRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listServicesRetry = clientProperties.getListServicesRetry();
    if (listServicesRetry != null) {
      RetrySettings listServicesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listServicesSettings().getRetrySettings(), listServicesRetry);
      clientSettingsBuilder.listServicesSettings().setRetrySettings(listServicesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listServices from properties.");
      }
    }
    Retry getServiceRetry = clientProperties.getGetServiceRetry();
    if (getServiceRetry != null) {
      RetrySettings getServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getServiceSettings().getRetrySettings(), getServiceRetry);
      clientSettingsBuilder.getServiceSettings().setRetrySettings(getServiceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getService from properties.");
      }
    }
    Retry createServiceRetry = clientProperties.getCreateServiceRetry();
    if (createServiceRetry != null) {
      RetrySettings createServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createServiceSettings().getRetrySettings(), createServiceRetry);
      clientSettingsBuilder.createServiceSettings().setRetrySettings(createServiceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for createService from properties.");
      }
    }
    Retry updateServiceRetry = clientProperties.getUpdateServiceRetry();
    if (updateServiceRetry != null) {
      RetrySettings updateServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateServiceSettings().getRetrySettings(), updateServiceRetry);
      clientSettingsBuilder.updateServiceSettings().setRetrySettings(updateServiceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for updateService from properties.");
      }
    }
    Retry deleteServiceRetry = clientProperties.getDeleteServiceRetry();
    if (deleteServiceRetry != null) {
      RetrySettings deleteServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteServiceSettings().getRetrySettings(), deleteServiceRetry);
      clientSettingsBuilder.deleteServiceSettings().setRetrySettings(deleteServiceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for deleteService from properties.");
      }
    }
    Retry listMetadataImportsRetry = clientProperties.getListMetadataImportsRetry();
    if (listMetadataImportsRetry != null) {
      RetrySettings listMetadataImportsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMetadataImportsSettings().getRetrySettings(),
              listMetadataImportsRetry);
      clientSettingsBuilder
          .listMetadataImportsSettings()
          .setRetrySettings(listMetadataImportsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMetadataImports from properties.");
      }
    }
    Retry getMetadataImportRetry = clientProperties.getGetMetadataImportRetry();
    if (getMetadataImportRetry != null) {
      RetrySettings getMetadataImportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMetadataImportSettings().getRetrySettings(),
              getMetadataImportRetry);
      clientSettingsBuilder
          .getMetadataImportSettings()
          .setRetrySettings(getMetadataImportRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMetadataImport from properties.");
      }
    }
    Retry createMetadataImportRetry = clientProperties.getCreateMetadataImportRetry();
    if (createMetadataImportRetry != null) {
      RetrySettings createMetadataImportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createMetadataImportSettings().getRetrySettings(),
              createMetadataImportRetry);
      clientSettingsBuilder
          .createMetadataImportSettings()
          .setRetrySettings(createMetadataImportRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for createMetadataImport from properties.");
      }
    }
    Retry updateMetadataImportRetry = clientProperties.getUpdateMetadataImportRetry();
    if (updateMetadataImportRetry != null) {
      RetrySettings updateMetadataImportRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateMetadataImportSettings().getRetrySettings(),
              updateMetadataImportRetry);
      clientSettingsBuilder
          .updateMetadataImportSettings()
          .setRetrySettings(updateMetadataImportRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for updateMetadataImport from properties.");
      }
    }
    Retry exportMetadataRetry = clientProperties.getExportMetadataRetry();
    if (exportMetadataRetry != null) {
      RetrySettings exportMetadataRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.exportMetadataSettings().getRetrySettings(),
              exportMetadataRetry);
      clientSettingsBuilder.exportMetadataSettings().setRetrySettings(exportMetadataRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for exportMetadata from properties.");
      }
    }
    Retry restoreServiceRetry = clientProperties.getRestoreServiceRetry();
    if (restoreServiceRetry != null) {
      RetrySettings restoreServiceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.restoreServiceSettings().getRetrySettings(),
              restoreServiceRetry);
      clientSettingsBuilder.restoreServiceSettings().setRetrySettings(restoreServiceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for restoreService from properties.");
      }
    }
    Retry listBackupsRetry = clientProperties.getListBackupsRetry();
    if (listBackupsRetry != null) {
      RetrySettings listBackupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBackupsSettings().getRetrySettings(), listBackupsRetry);
      clientSettingsBuilder.listBackupsSettings().setRetrySettings(listBackupsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listBackups from properties.");
      }
    }
    Retry getBackupRetry = clientProperties.getGetBackupRetry();
    if (getBackupRetry != null) {
      RetrySettings getBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getBackupSettings().getRetrySettings(), getBackupRetry);
      clientSettingsBuilder.getBackupSettings().setRetrySettings(getBackupRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getBackup from properties.");
      }
    }
    Retry createBackupRetry = clientProperties.getCreateBackupRetry();
    if (createBackupRetry != null) {
      RetrySettings createBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createBackupSettings().getRetrySettings(), createBackupRetry);
      clientSettingsBuilder.createBackupSettings().setRetrySettings(createBackupRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for createBackup from properties.");
      }
    }
    Retry deleteBackupRetry = clientProperties.getDeleteBackupRetry();
    if (deleteBackupRetry != null) {
      RetrySettings deleteBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteBackupSettings().getRetrySettings(), deleteBackupRetry);
      clientSettingsBuilder.deleteBackupSettings().setRetrySettings(deleteBackupRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for deleteBackup from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public DataprocMetastoreClient dataprocMetastoreClient(
      DataprocMetastoreSettings dataprocMetastoreSettings) throws IOException {
    return DataprocMetastoreClient.create(dataprocMetastoreSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-dataproc-metastore";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
