/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.metastore.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.metastore.v1.DataprocMetastoreFederationClient;
import com.google.cloud.metastore.v1.DataprocMetastoreFederationSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link DataprocMetastoreFederationClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(DataprocMetastoreFederationClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.metastore.v1.dataproc-metastore-federation.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(DataprocMetastoreFederationSpringProperties.class)
public class DataprocMetastoreFederationSpringAutoConfiguration {
  private final DataprocMetastoreFederationSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER =
      LogFactory.getLog(DataprocMetastoreFederationSpringAutoConfiguration.class);

  protected DataprocMetastoreFederationSpringAutoConfiguration(
      DataprocMetastoreFederationSpringProperties clientProperties,
      CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from DataprocMetastoreFederation-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean. The default is gRPC and will default to it
   * unless the useRest option is provided to use HTTP transport instead
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultDataprocMetastoreFederationTransportChannelProvider")
  public TransportChannelProvider defaultDataprocMetastoreFederationTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return DataprocMetastoreFederationSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return DataprocMetastoreFederationSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a DataprocMetastoreFederationSettings bean configured to use the default credentials
   * provider (obtained with dataprocMetastoreFederationCredentials()) and its default transport
   * channel provider (defaultDataprocMetastoreFederationTransportChannelProvider()). It also
   * configures the quota project ID if provided. It will configure an executor provider in case
   * there is more than one thread configured in the client
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in DataprocMetastoreFederationSpringProperties. Method-level properties will take precedence
   * over service-level properties if available, and client library defaults will be used if neither
   * are specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link DataprocMetastoreFederationSettings} bean configured with {@link
   *     TransportChannelProvider} bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public DataprocMetastoreFederationSettings dataprocMetastoreFederationSettings(
      @Qualifier("defaultDataprocMetastoreFederationTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    DataprocMetastoreFederationSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = DataprocMetastoreFederationSettings.newHttpJsonBuilder();
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using REST (HTTP/JSON) transport.");
      }
    } else {
      clientSettingsBuilder = DataprocMetastoreFederationSettings.newBuilder();
    }
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          DataprocMetastoreFederationSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listFederationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFederationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listFederationsSettings()
          .setRetrySettings(listFederationsRetrySettings);

      RetrySettings getFederationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFederationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getFederationSettings().setRetrySettings(getFederationRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listFederationsRetry = clientProperties.getListFederationsRetry();
    if (listFederationsRetry != null) {
      RetrySettings listFederationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFederationsSettings().getRetrySettings(),
              listFederationsRetry);
      clientSettingsBuilder
          .listFederationsSettings()
          .setRetrySettings(listFederationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listFederations from properties.");
      }
    }
    Retry getFederationRetry = clientProperties.getGetFederationRetry();
    if (getFederationRetry != null) {
      RetrySettings getFederationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFederationSettings().getRetrySettings(), getFederationRetry);
      clientSettingsBuilder.getFederationSettings().setRetrySettings(getFederationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getFederation from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a DataprocMetastoreFederationClient bean configured with
   * DataprocMetastoreFederationSettings.
   *
   * @param dataprocMetastoreFederationSettings settings to configure an instance of client bean.
   * @return a {@link DataprocMetastoreFederationClient} bean configured with {@link
   *     DataprocMetastoreFederationSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public DataprocMetastoreFederationClient dataprocMetastoreFederationClient(
      DataprocMetastoreFederationSettings dataprocMetastoreFederationSettings) throws IOException {
    return DataprocMetastoreFederationClient.create(dataprocMetastoreFederationSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-dataproc-metastore-federation";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
