/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.automl.v1.spring;

import com.google.api.core.BetaApi;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.CredentialsSupplier;
import javax.annotation.Generated;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;
import org.threeten.bp.Duration;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/** Provides default property values for PredictionService client bean */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@ConfigurationProperties("com.google.cloud.automl.v1.spring.auto.prediction-service")
public class PredictionServiceSpringProperties implements CredentialsSupplier {
  @NestedConfigurationProperty
  private final Credentials credentials =
      new Credentials("https://www.googleapis.com/auth/cloud-platform");

  private String quotaProjectId;
  private Integer executorThreadCount;
  private boolean useRest = false;
  private Duration predictInitialRpcTimeout;
  private Double predictRpcTimeoutMultiplier;
  private Duration predictMaxRpcTimeout;
  private Duration predictTotalTimeout;
  private Duration batchPredictInitialRpcTimeout;
  private Double batchPredictRpcTimeoutMultiplier;
  private Duration batchPredictMaxRpcTimeout;
  private Duration batchPredictTotalTimeout;

  @Override
  public Credentials getCredentials() {
    return this.credentials;
  }

  public String getQuotaProjectId() {
    return this.quotaProjectId;
  }

  public void setQuotaProjectId(String quotaProjectId) {
    this.quotaProjectId = quotaProjectId;
  }

  public boolean getUseRest() {
    return this.useRest;
  }

  public void setUseRest(boolean useRest) {
    this.useRest = useRest;
  }

  public Integer getExecutorThreadCount() {
    return this.executorThreadCount;
  }

  public void setExecutorThreadCount(Integer executorThreadCount) {
    this.executorThreadCount = executorThreadCount;
  }

  public Duration getPredictInitialRpcTimeout() {
    return this.predictInitialRpcTimeout;
  }

  public void setPredictInitialRpcTimeout(java.time.Duration predictInitialRpcTimeout) {
    this.predictInitialRpcTimeout = Duration.parse(predictInitialRpcTimeout.toString());
  }

  public Double getPredictRpcTimeoutMultiplier() {
    return this.predictRpcTimeoutMultiplier;
  }

  public void setPredictRpcTimeoutMultiplier(Double predictRpcTimeoutMultiplier) {
    this.predictRpcTimeoutMultiplier = predictRpcTimeoutMultiplier;
  }

  public Duration getPredictMaxRpcTimeout() {
    return this.predictMaxRpcTimeout;
  }

  public void setPredictMaxRpcTimeout(java.time.Duration predictMaxRpcTimeout) {
    this.predictMaxRpcTimeout = Duration.parse(predictMaxRpcTimeout.toString());
  }

  public Duration getPredictTotalTimeout() {
    return this.predictTotalTimeout;
  }

  public void setPredictTotalTimeout(java.time.Duration predictTotalTimeout) {
    this.predictTotalTimeout = Duration.parse(predictTotalTimeout.toString());
  }

  public Duration getBatchPredictInitialRpcTimeout() {
    return this.batchPredictInitialRpcTimeout;
  }

  public void setBatchPredictInitialRpcTimeout(java.time.Duration batchPredictInitialRpcTimeout) {
    this.batchPredictInitialRpcTimeout = Duration.parse(batchPredictInitialRpcTimeout.toString());
  }

  public Double getBatchPredictRpcTimeoutMultiplier() {
    return this.batchPredictRpcTimeoutMultiplier;
  }

  public void setBatchPredictRpcTimeoutMultiplier(Double batchPredictRpcTimeoutMultiplier) {
    this.batchPredictRpcTimeoutMultiplier = batchPredictRpcTimeoutMultiplier;
  }

  public Duration getBatchPredictMaxRpcTimeout() {
    return this.batchPredictMaxRpcTimeout;
  }

  public void setBatchPredictMaxRpcTimeout(java.time.Duration batchPredictMaxRpcTimeout) {
    this.batchPredictMaxRpcTimeout = Duration.parse(batchPredictMaxRpcTimeout.toString());
  }

  public Duration getBatchPredictTotalTimeout() {
    return this.batchPredictTotalTimeout;
  }

  public void setBatchPredictTotalTimeout(java.time.Duration batchPredictTotalTimeout) {
    this.batchPredictTotalTimeout = Duration.parse(batchPredictTotalTimeout.toString());
  }
}
