/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.networksecurity.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.networksecurity.v1.MirroringClient;
import com.google.cloud.networksecurity.v1.MirroringSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link MirroringClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(MirroringClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.networksecurity.v1.mirroring.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(MirroringSpringProperties.class)
public class MirroringSpringAutoConfiguration {
  private final MirroringSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(MirroringSpringAutoConfiguration.class);

  protected MirroringSpringAutoConfiguration(
      MirroringSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from Mirroring-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultMirroringTransportChannelProvider")
  public TransportChannelProvider defaultMirroringTransportChannelProvider() {
    return MirroringSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a MirroringSettings bean configured to use a DefaultCredentialsProvider and the client
   * library's default transport channel provider (defaultMirroringTransportChannelProvider()). It
   * also configures the quota project ID and executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in MirroringSpringProperties. Method-level properties will take precedence over service-level
   * properties if available, and client library defaults will be used if neither are specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link MirroringSettings} bean configured with {@link TransportChannelProvider} bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public MirroringSettings mirroringSettings(
      @Qualifier("defaultMirroringTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    MirroringSettings.Builder clientSettingsBuilder = MirroringSettings.newBuilder();
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setEndpoint(MirroringSettings.getDefaultEndpoint())
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          MirroringSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listMirroringEndpointGroupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMirroringEndpointGroupsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMirroringEndpointGroupsSettings()
          .setRetrySettings(listMirroringEndpointGroupsRetrySettings);

      RetrySettings getMirroringEndpointGroupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMirroringEndpointGroupSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getMirroringEndpointGroupSettings()
          .setRetrySettings(getMirroringEndpointGroupRetrySettings);

      RetrySettings listMirroringEndpointGroupAssociationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder
                  .listMirroringEndpointGroupAssociationsSettings()
                  .getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMirroringEndpointGroupAssociationsSettings()
          .setRetrySettings(listMirroringEndpointGroupAssociationsRetrySettings);

      RetrySettings getMirroringEndpointGroupAssociationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder
                  .getMirroringEndpointGroupAssociationSettings()
                  .getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getMirroringEndpointGroupAssociationSettings()
          .setRetrySettings(getMirroringEndpointGroupAssociationRetrySettings);

      RetrySettings listMirroringDeploymentGroupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMirroringDeploymentGroupsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMirroringDeploymentGroupsSettings()
          .setRetrySettings(listMirroringDeploymentGroupsRetrySettings);

      RetrySettings getMirroringDeploymentGroupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMirroringDeploymentGroupSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getMirroringDeploymentGroupSettings()
          .setRetrySettings(getMirroringDeploymentGroupRetrySettings);

      RetrySettings listMirroringDeploymentsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMirroringDeploymentsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMirroringDeploymentsSettings()
          .setRetrySettings(listMirroringDeploymentsRetrySettings);

      RetrySettings getMirroringDeploymentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMirroringDeploymentSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getMirroringDeploymentSettings()
          .setRetrySettings(getMirroringDeploymentRetrySettings);

      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);

      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);

      RetrySettings setIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setIamPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.setIamPolicySettings().setRetrySettings(setIamPolicyRetrySettings);

      RetrySettings getIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getIamPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getIamPolicySettings().setRetrySettings(getIamPolicyRetrySettings);

      RetrySettings testIamPermissionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.testIamPermissionsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .testIamPermissionsSettings()
          .setRetrySettings(testIamPermissionsRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listMirroringEndpointGroupsRetry = clientProperties.getListMirroringEndpointGroupsRetry();
    if (listMirroringEndpointGroupsRetry != null) {
      RetrySettings listMirroringEndpointGroupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMirroringEndpointGroupsSettings().getRetrySettings(),
              listMirroringEndpointGroupsRetry);
      clientSettingsBuilder
          .listMirroringEndpointGroupsSettings()
          .setRetrySettings(listMirroringEndpointGroupsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMirroringEndpointGroups from properties.");
      }
    }
    Retry getMirroringEndpointGroupRetry = clientProperties.getGetMirroringEndpointGroupRetry();
    if (getMirroringEndpointGroupRetry != null) {
      RetrySettings getMirroringEndpointGroupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMirroringEndpointGroupSettings().getRetrySettings(),
              getMirroringEndpointGroupRetry);
      clientSettingsBuilder
          .getMirroringEndpointGroupSettings()
          .setRetrySettings(getMirroringEndpointGroupRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMirroringEndpointGroup from properties.");
      }
    }
    Retry listMirroringEndpointGroupAssociationsRetry =
        clientProperties.getListMirroringEndpointGroupAssociationsRetry();
    if (listMirroringEndpointGroupAssociationsRetry != null) {
      RetrySettings listMirroringEndpointGroupAssociationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder
                  .listMirroringEndpointGroupAssociationsSettings()
                  .getRetrySettings(),
              listMirroringEndpointGroupAssociationsRetry);
      clientSettingsBuilder
          .listMirroringEndpointGroupAssociationsSettings()
          .setRetrySettings(listMirroringEndpointGroupAssociationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMirroringEndpointGroupAssociations from properties.");
      }
    }
    Retry getMirroringEndpointGroupAssociationRetry =
        clientProperties.getGetMirroringEndpointGroupAssociationRetry();
    if (getMirroringEndpointGroupAssociationRetry != null) {
      RetrySettings getMirroringEndpointGroupAssociationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder
                  .getMirroringEndpointGroupAssociationSettings()
                  .getRetrySettings(),
              getMirroringEndpointGroupAssociationRetry);
      clientSettingsBuilder
          .getMirroringEndpointGroupAssociationSettings()
          .setRetrySettings(getMirroringEndpointGroupAssociationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMirroringEndpointGroupAssociation from properties.");
      }
    }
    Retry listMirroringDeploymentGroupsRetry =
        clientProperties.getListMirroringDeploymentGroupsRetry();
    if (listMirroringDeploymentGroupsRetry != null) {
      RetrySettings listMirroringDeploymentGroupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMirroringDeploymentGroupsSettings().getRetrySettings(),
              listMirroringDeploymentGroupsRetry);
      clientSettingsBuilder
          .listMirroringDeploymentGroupsSettings()
          .setRetrySettings(listMirroringDeploymentGroupsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMirroringDeploymentGroups from properties.");
      }
    }
    Retry getMirroringDeploymentGroupRetry = clientProperties.getGetMirroringDeploymentGroupRetry();
    if (getMirroringDeploymentGroupRetry != null) {
      RetrySettings getMirroringDeploymentGroupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMirroringDeploymentGroupSettings().getRetrySettings(),
              getMirroringDeploymentGroupRetry);
      clientSettingsBuilder
          .getMirroringDeploymentGroupSettings()
          .setRetrySettings(getMirroringDeploymentGroupRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMirroringDeploymentGroup from properties.");
      }
    }
    Retry listMirroringDeploymentsRetry = clientProperties.getListMirroringDeploymentsRetry();
    if (listMirroringDeploymentsRetry != null) {
      RetrySettings listMirroringDeploymentsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMirroringDeploymentsSettings().getRetrySettings(),
              listMirroringDeploymentsRetry);
      clientSettingsBuilder
          .listMirroringDeploymentsSettings()
          .setRetrySettings(listMirroringDeploymentsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMirroringDeployments from properties.");
      }
    }
    Retry getMirroringDeploymentRetry = clientProperties.getGetMirroringDeploymentRetry();
    if (getMirroringDeploymentRetry != null) {
      RetrySettings getMirroringDeploymentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMirroringDeploymentSettings().getRetrySettings(),
              getMirroringDeploymentRetry);
      clientSettingsBuilder
          .getMirroringDeploymentSettings()
          .setRetrySettings(getMirroringDeploymentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMirroringDeployment from properties.");
      }
    }
    Retry listLocationsRetry = clientProperties.getListLocationsRetry();
    if (listLocationsRetry != null) {
      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), listLocationsRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listLocations from properties.");
      }
    }
    Retry getLocationRetry = clientProperties.getGetLocationRetry();
    if (getLocationRetry != null) {
      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), getLocationRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getLocation from properties.");
      }
    }
    Retry setIamPolicyRetry = clientProperties.getSetIamPolicyRetry();
    if (setIamPolicyRetry != null) {
      RetrySettings setIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setIamPolicySettings().getRetrySettings(), setIamPolicyRetry);
      clientSettingsBuilder.setIamPolicySettings().setRetrySettings(setIamPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for setIamPolicy from properties.");
      }
    }
    Retry getIamPolicyRetry = clientProperties.getGetIamPolicyRetry();
    if (getIamPolicyRetry != null) {
      RetrySettings getIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getIamPolicySettings().getRetrySettings(), getIamPolicyRetry);
      clientSettingsBuilder.getIamPolicySettings().setRetrySettings(getIamPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getIamPolicy from properties.");
      }
    }
    Retry testIamPermissionsRetry = clientProperties.getTestIamPermissionsRetry();
    if (testIamPermissionsRetry != null) {
      RetrySettings testIamPermissionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.testIamPermissionsSettings().getRetrySettings(),
              testIamPermissionsRetry);
      clientSettingsBuilder
          .testIamPermissionsSettings()
          .setRetrySettings(testIamPermissionsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for testIamPermissions from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a MirroringClient bean configured with MirroringSettings.
   *
   * @param mirroringSettings settings to configure an instance of client bean.
   * @return a {@link MirroringClient} bean configured with {@link MirroringSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public MirroringClient mirroringClient(MirroringSettings mirroringSettings) throws IOException {
    return MirroringClient.create(mirroringSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-mirroring";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
