/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.networksecurity.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.networksecurity.v1.NetworkSecurityClient;
import com.google.cloud.networksecurity.v1.NetworkSecuritySettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link NetworkSecurityClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(NetworkSecurityClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.networksecurity.v1.network-security.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(NetworkSecuritySpringProperties.class)
public class NetworkSecuritySpringAutoConfiguration {
  private final NetworkSecuritySpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(NetworkSecuritySpringAutoConfiguration.class);

  protected NetworkSecuritySpringAutoConfiguration(
      NetworkSecuritySpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from NetworkSecurity-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultNetworkSecurityTransportChannelProvider")
  public TransportChannelProvider defaultNetworkSecurityTransportChannelProvider() {
    return NetworkSecuritySettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a NetworkSecuritySettings bean configured to use a DefaultCredentialsProvider and the
   * client library's default transport channel provider
   * (defaultNetworkSecurityTransportChannelProvider()). It also configures the quota project ID and
   * executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in NetworkSecuritySpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link NetworkSecuritySettings} bean configured with {@link TransportChannelProvider}
   *     bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public NetworkSecuritySettings networkSecuritySettings(
      @Qualifier("defaultNetworkSecurityTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    NetworkSecuritySettings.Builder clientSettingsBuilder = NetworkSecuritySettings.newBuilder();
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setEndpoint(NetworkSecuritySettings.getDefaultEndpoint())
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          NetworkSecuritySettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listAuthorizationPoliciesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listAuthorizationPoliciesSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listAuthorizationPoliciesSettings()
          .setRetrySettings(listAuthorizationPoliciesRetrySettings);

      RetrySettings getAuthorizationPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAuthorizationPolicySettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getAuthorizationPolicySettings()
          .setRetrySettings(getAuthorizationPolicyRetrySettings);

      RetrySettings listServerTlsPoliciesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listServerTlsPoliciesSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listServerTlsPoliciesSettings()
          .setRetrySettings(listServerTlsPoliciesRetrySettings);

      RetrySettings getServerTlsPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getServerTlsPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getServerTlsPolicySettings()
          .setRetrySettings(getServerTlsPolicyRetrySettings);

      RetrySettings listClientTlsPoliciesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listClientTlsPoliciesSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listClientTlsPoliciesSettings()
          .setRetrySettings(listClientTlsPoliciesRetrySettings);

      RetrySettings getClientTlsPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getClientTlsPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getClientTlsPolicySettings()
          .setRetrySettings(getClientTlsPolicyRetrySettings);

      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);

      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);

      RetrySettings setIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setIamPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.setIamPolicySettings().setRetrySettings(setIamPolicyRetrySettings);

      RetrySettings getIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getIamPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getIamPolicySettings().setRetrySettings(getIamPolicyRetrySettings);

      RetrySettings testIamPermissionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.testIamPermissionsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .testIamPermissionsSettings()
          .setRetrySettings(testIamPermissionsRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listAuthorizationPoliciesRetry = clientProperties.getListAuthorizationPoliciesRetry();
    if (listAuthorizationPoliciesRetry != null) {
      RetrySettings listAuthorizationPoliciesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listAuthorizationPoliciesSettings().getRetrySettings(),
              listAuthorizationPoliciesRetry);
      clientSettingsBuilder
          .listAuthorizationPoliciesSettings()
          .setRetrySettings(listAuthorizationPoliciesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listAuthorizationPolicies from properties.");
      }
    }
    Retry getAuthorizationPolicyRetry = clientProperties.getGetAuthorizationPolicyRetry();
    if (getAuthorizationPolicyRetry != null) {
      RetrySettings getAuthorizationPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAuthorizationPolicySettings().getRetrySettings(),
              getAuthorizationPolicyRetry);
      clientSettingsBuilder
          .getAuthorizationPolicySettings()
          .setRetrySettings(getAuthorizationPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getAuthorizationPolicy from properties.");
      }
    }
    Retry listServerTlsPoliciesRetry = clientProperties.getListServerTlsPoliciesRetry();
    if (listServerTlsPoliciesRetry != null) {
      RetrySettings listServerTlsPoliciesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listServerTlsPoliciesSettings().getRetrySettings(),
              listServerTlsPoliciesRetry);
      clientSettingsBuilder
          .listServerTlsPoliciesSettings()
          .setRetrySettings(listServerTlsPoliciesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listServerTlsPolicies from properties.");
      }
    }
    Retry getServerTlsPolicyRetry = clientProperties.getGetServerTlsPolicyRetry();
    if (getServerTlsPolicyRetry != null) {
      RetrySettings getServerTlsPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getServerTlsPolicySettings().getRetrySettings(),
              getServerTlsPolicyRetry);
      clientSettingsBuilder
          .getServerTlsPolicySettings()
          .setRetrySettings(getServerTlsPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getServerTlsPolicy from properties.");
      }
    }
    Retry listClientTlsPoliciesRetry = clientProperties.getListClientTlsPoliciesRetry();
    if (listClientTlsPoliciesRetry != null) {
      RetrySettings listClientTlsPoliciesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listClientTlsPoliciesSettings().getRetrySettings(),
              listClientTlsPoliciesRetry);
      clientSettingsBuilder
          .listClientTlsPoliciesSettings()
          .setRetrySettings(listClientTlsPoliciesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listClientTlsPolicies from properties.");
      }
    }
    Retry getClientTlsPolicyRetry = clientProperties.getGetClientTlsPolicyRetry();
    if (getClientTlsPolicyRetry != null) {
      RetrySettings getClientTlsPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getClientTlsPolicySettings().getRetrySettings(),
              getClientTlsPolicyRetry);
      clientSettingsBuilder
          .getClientTlsPolicySettings()
          .setRetrySettings(getClientTlsPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getClientTlsPolicy from properties.");
      }
    }
    Retry listLocationsRetry = clientProperties.getListLocationsRetry();
    if (listLocationsRetry != null) {
      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), listLocationsRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listLocations from properties.");
      }
    }
    Retry getLocationRetry = clientProperties.getGetLocationRetry();
    if (getLocationRetry != null) {
      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), getLocationRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getLocation from properties.");
      }
    }
    Retry setIamPolicyRetry = clientProperties.getSetIamPolicyRetry();
    if (setIamPolicyRetry != null) {
      RetrySettings setIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setIamPolicySettings().getRetrySettings(), setIamPolicyRetry);
      clientSettingsBuilder.setIamPolicySettings().setRetrySettings(setIamPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for setIamPolicy from properties.");
      }
    }
    Retry getIamPolicyRetry = clientProperties.getGetIamPolicyRetry();
    if (getIamPolicyRetry != null) {
      RetrySettings getIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getIamPolicySettings().getRetrySettings(), getIamPolicyRetry);
      clientSettingsBuilder.getIamPolicySettings().setRetrySettings(getIamPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getIamPolicy from properties.");
      }
    }
    Retry testIamPermissionsRetry = clientProperties.getTestIamPermissionsRetry();
    if (testIamPermissionsRetry != null) {
      RetrySettings testIamPermissionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.testIamPermissionsSettings().getRetrySettings(),
              testIamPermissionsRetry);
      clientSettingsBuilder
          .testIamPermissionsSettings()
          .setRetrySettings(testIamPermissionsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for testIamPermissions from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a NetworkSecurityClient bean configured with NetworkSecuritySettings.
   *
   * @param networkSecuritySettings settings to configure an instance of client bean.
   * @return a {@link NetworkSecurityClient} bean configured with {@link NetworkSecuritySettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public NetworkSecurityClient networkSecurityClient(
      NetworkSecuritySettings networkSecuritySettings) throws IOException {
    return NetworkSecurityClient.create(networkSecuritySettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-network-security";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
