/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.managedidentities.v1.spring;

import com.google.api.core.BetaApi;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.CredentialsSupplier;
import javax.annotation.Generated;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;
import org.threeten.bp.Duration;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/** Provides default property values for ManagedIdentitiesService client bean */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@ConfigurationProperties(
    "com.google.cloud.managedidentities.v1.spring.auto.managed-identities-service")
public class ManagedIdentitiesServiceSpringProperties implements CredentialsSupplier {
  @NestedConfigurationProperty
  private final Credentials credentials =
      new Credentials("https://www.googleapis.com/auth/cloud-platform");

  private String quotaProjectId;
  private Integer executorThreadCount;
  private Duration createMicrosoftAdDomainInitialRpcTimeout;
  private Double createMicrosoftAdDomainRpcTimeoutMultiplier;
  private Duration createMicrosoftAdDomainMaxRpcTimeout;
  private Duration createMicrosoftAdDomainTotalTimeout;
  private Duration resetAdminPasswordInitialRpcTimeout;
  private Double resetAdminPasswordRpcTimeoutMultiplier;
  private Duration resetAdminPasswordMaxRpcTimeout;
  private Duration resetAdminPasswordTotalTimeout;
  private Duration listDomainsInitialRpcTimeout;
  private Double listDomainsRpcTimeoutMultiplier;
  private Duration listDomainsMaxRpcTimeout;
  private Duration listDomainsTotalTimeout;
  private Duration getDomainInitialRpcTimeout;
  private Double getDomainRpcTimeoutMultiplier;
  private Duration getDomainMaxRpcTimeout;
  private Duration getDomainTotalTimeout;
  private Duration updateDomainInitialRpcTimeout;
  private Double updateDomainRpcTimeoutMultiplier;
  private Duration updateDomainMaxRpcTimeout;
  private Duration updateDomainTotalTimeout;
  private Duration deleteDomainInitialRpcTimeout;
  private Double deleteDomainRpcTimeoutMultiplier;
  private Duration deleteDomainMaxRpcTimeout;
  private Duration deleteDomainTotalTimeout;
  private Duration attachTrustInitialRpcTimeout;
  private Double attachTrustRpcTimeoutMultiplier;
  private Duration attachTrustMaxRpcTimeout;
  private Duration attachTrustTotalTimeout;
  private Duration reconfigureTrustInitialRpcTimeout;
  private Double reconfigureTrustRpcTimeoutMultiplier;
  private Duration reconfigureTrustMaxRpcTimeout;
  private Duration reconfigureTrustTotalTimeout;
  private Duration detachTrustInitialRpcTimeout;
  private Double detachTrustRpcTimeoutMultiplier;
  private Duration detachTrustMaxRpcTimeout;
  private Duration detachTrustTotalTimeout;
  private Duration validateTrustInitialRpcTimeout;
  private Double validateTrustRpcTimeoutMultiplier;
  private Duration validateTrustMaxRpcTimeout;
  private Duration validateTrustTotalTimeout;

  @Override
  public Credentials getCredentials() {
    return this.credentials;
  }

  public String getQuotaProjectId() {
    return this.quotaProjectId;
  }

  public void setQuotaProjectId(String quotaProjectId) {
    this.quotaProjectId = quotaProjectId;
  }

  public Integer getExecutorThreadCount() {
    return this.executorThreadCount;
  }

  public void setExecutorThreadCount(Integer executorThreadCount) {
    this.executorThreadCount = executorThreadCount;
  }

  public Duration getCreateMicrosoftAdDomainInitialRpcTimeout() {
    return this.createMicrosoftAdDomainInitialRpcTimeout;
  }

  public void setCreateMicrosoftAdDomainInitialRpcTimeout(
      java.time.Duration createMicrosoftAdDomainInitialRpcTimeout) {
    this.createMicrosoftAdDomainInitialRpcTimeout =
        Duration.parse(createMicrosoftAdDomainInitialRpcTimeout.toString());
  }

  public Double getCreateMicrosoftAdDomainRpcTimeoutMultiplier() {
    return this.createMicrosoftAdDomainRpcTimeoutMultiplier;
  }

  public void setCreateMicrosoftAdDomainRpcTimeoutMultiplier(
      Double createMicrosoftAdDomainRpcTimeoutMultiplier) {
    this.createMicrosoftAdDomainRpcTimeoutMultiplier = createMicrosoftAdDomainRpcTimeoutMultiplier;
  }

  public Duration getCreateMicrosoftAdDomainMaxRpcTimeout() {
    return this.createMicrosoftAdDomainMaxRpcTimeout;
  }

  public void setCreateMicrosoftAdDomainMaxRpcTimeout(
      java.time.Duration createMicrosoftAdDomainMaxRpcTimeout) {
    this.createMicrosoftAdDomainMaxRpcTimeout =
        Duration.parse(createMicrosoftAdDomainMaxRpcTimeout.toString());
  }

  public Duration getCreateMicrosoftAdDomainTotalTimeout() {
    return this.createMicrosoftAdDomainTotalTimeout;
  }

  public void setCreateMicrosoftAdDomainTotalTimeout(
      java.time.Duration createMicrosoftAdDomainTotalTimeout) {
    this.createMicrosoftAdDomainTotalTimeout =
        Duration.parse(createMicrosoftAdDomainTotalTimeout.toString());
  }

  public Duration getResetAdminPasswordInitialRpcTimeout() {
    return this.resetAdminPasswordInitialRpcTimeout;
  }

  public void setResetAdminPasswordInitialRpcTimeout(
      java.time.Duration resetAdminPasswordInitialRpcTimeout) {
    this.resetAdminPasswordInitialRpcTimeout =
        Duration.parse(resetAdminPasswordInitialRpcTimeout.toString());
  }

  public Double getResetAdminPasswordRpcTimeoutMultiplier() {
    return this.resetAdminPasswordRpcTimeoutMultiplier;
  }

  public void setResetAdminPasswordRpcTimeoutMultiplier(
      Double resetAdminPasswordRpcTimeoutMultiplier) {
    this.resetAdminPasswordRpcTimeoutMultiplier = resetAdminPasswordRpcTimeoutMultiplier;
  }

  public Duration getResetAdminPasswordMaxRpcTimeout() {
    return this.resetAdminPasswordMaxRpcTimeout;
  }

  public void setResetAdminPasswordMaxRpcTimeout(
      java.time.Duration resetAdminPasswordMaxRpcTimeout) {
    this.resetAdminPasswordMaxRpcTimeout =
        Duration.parse(resetAdminPasswordMaxRpcTimeout.toString());
  }

  public Duration getResetAdminPasswordTotalTimeout() {
    return this.resetAdminPasswordTotalTimeout;
  }

  public void setResetAdminPasswordTotalTimeout(java.time.Duration resetAdminPasswordTotalTimeout) {
    this.resetAdminPasswordTotalTimeout = Duration.parse(resetAdminPasswordTotalTimeout.toString());
  }

  public Duration getListDomainsInitialRpcTimeout() {
    return this.listDomainsInitialRpcTimeout;
  }

  public void setListDomainsInitialRpcTimeout(java.time.Duration listDomainsInitialRpcTimeout) {
    this.listDomainsInitialRpcTimeout = Duration.parse(listDomainsInitialRpcTimeout.toString());
  }

  public Double getListDomainsRpcTimeoutMultiplier() {
    return this.listDomainsRpcTimeoutMultiplier;
  }

  public void setListDomainsRpcTimeoutMultiplier(Double listDomainsRpcTimeoutMultiplier) {
    this.listDomainsRpcTimeoutMultiplier = listDomainsRpcTimeoutMultiplier;
  }

  public Duration getListDomainsMaxRpcTimeout() {
    return this.listDomainsMaxRpcTimeout;
  }

  public void setListDomainsMaxRpcTimeout(java.time.Duration listDomainsMaxRpcTimeout) {
    this.listDomainsMaxRpcTimeout = Duration.parse(listDomainsMaxRpcTimeout.toString());
  }

  public Duration getListDomainsTotalTimeout() {
    return this.listDomainsTotalTimeout;
  }

  public void setListDomainsTotalTimeout(java.time.Duration listDomainsTotalTimeout) {
    this.listDomainsTotalTimeout = Duration.parse(listDomainsTotalTimeout.toString());
  }

  public Duration getGetDomainInitialRpcTimeout() {
    return this.getDomainInitialRpcTimeout;
  }

  public void setGetDomainInitialRpcTimeout(java.time.Duration getDomainInitialRpcTimeout) {
    this.getDomainInitialRpcTimeout = Duration.parse(getDomainInitialRpcTimeout.toString());
  }

  public Double getGetDomainRpcTimeoutMultiplier() {
    return this.getDomainRpcTimeoutMultiplier;
  }

  public void setGetDomainRpcTimeoutMultiplier(Double getDomainRpcTimeoutMultiplier) {
    this.getDomainRpcTimeoutMultiplier = getDomainRpcTimeoutMultiplier;
  }

  public Duration getGetDomainMaxRpcTimeout() {
    return this.getDomainMaxRpcTimeout;
  }

  public void setGetDomainMaxRpcTimeout(java.time.Duration getDomainMaxRpcTimeout) {
    this.getDomainMaxRpcTimeout = Duration.parse(getDomainMaxRpcTimeout.toString());
  }

  public Duration getGetDomainTotalTimeout() {
    return this.getDomainTotalTimeout;
  }

  public void setGetDomainTotalTimeout(java.time.Duration getDomainTotalTimeout) {
    this.getDomainTotalTimeout = Duration.parse(getDomainTotalTimeout.toString());
  }

  public Duration getUpdateDomainInitialRpcTimeout() {
    return this.updateDomainInitialRpcTimeout;
  }

  public void setUpdateDomainInitialRpcTimeout(java.time.Duration updateDomainInitialRpcTimeout) {
    this.updateDomainInitialRpcTimeout = Duration.parse(updateDomainInitialRpcTimeout.toString());
  }

  public Double getUpdateDomainRpcTimeoutMultiplier() {
    return this.updateDomainRpcTimeoutMultiplier;
  }

  public void setUpdateDomainRpcTimeoutMultiplier(Double updateDomainRpcTimeoutMultiplier) {
    this.updateDomainRpcTimeoutMultiplier = updateDomainRpcTimeoutMultiplier;
  }

  public Duration getUpdateDomainMaxRpcTimeout() {
    return this.updateDomainMaxRpcTimeout;
  }

  public void setUpdateDomainMaxRpcTimeout(java.time.Duration updateDomainMaxRpcTimeout) {
    this.updateDomainMaxRpcTimeout = Duration.parse(updateDomainMaxRpcTimeout.toString());
  }

  public Duration getUpdateDomainTotalTimeout() {
    return this.updateDomainTotalTimeout;
  }

  public void setUpdateDomainTotalTimeout(java.time.Duration updateDomainTotalTimeout) {
    this.updateDomainTotalTimeout = Duration.parse(updateDomainTotalTimeout.toString());
  }

  public Duration getDeleteDomainInitialRpcTimeout() {
    return this.deleteDomainInitialRpcTimeout;
  }

  public void setDeleteDomainInitialRpcTimeout(java.time.Duration deleteDomainInitialRpcTimeout) {
    this.deleteDomainInitialRpcTimeout = Duration.parse(deleteDomainInitialRpcTimeout.toString());
  }

  public Double getDeleteDomainRpcTimeoutMultiplier() {
    return this.deleteDomainRpcTimeoutMultiplier;
  }

  public void setDeleteDomainRpcTimeoutMultiplier(Double deleteDomainRpcTimeoutMultiplier) {
    this.deleteDomainRpcTimeoutMultiplier = deleteDomainRpcTimeoutMultiplier;
  }

  public Duration getDeleteDomainMaxRpcTimeout() {
    return this.deleteDomainMaxRpcTimeout;
  }

  public void setDeleteDomainMaxRpcTimeout(java.time.Duration deleteDomainMaxRpcTimeout) {
    this.deleteDomainMaxRpcTimeout = Duration.parse(deleteDomainMaxRpcTimeout.toString());
  }

  public Duration getDeleteDomainTotalTimeout() {
    return this.deleteDomainTotalTimeout;
  }

  public void setDeleteDomainTotalTimeout(java.time.Duration deleteDomainTotalTimeout) {
    this.deleteDomainTotalTimeout = Duration.parse(deleteDomainTotalTimeout.toString());
  }

  public Duration getAttachTrustInitialRpcTimeout() {
    return this.attachTrustInitialRpcTimeout;
  }

  public void setAttachTrustInitialRpcTimeout(java.time.Duration attachTrustInitialRpcTimeout) {
    this.attachTrustInitialRpcTimeout = Duration.parse(attachTrustInitialRpcTimeout.toString());
  }

  public Double getAttachTrustRpcTimeoutMultiplier() {
    return this.attachTrustRpcTimeoutMultiplier;
  }

  public void setAttachTrustRpcTimeoutMultiplier(Double attachTrustRpcTimeoutMultiplier) {
    this.attachTrustRpcTimeoutMultiplier = attachTrustRpcTimeoutMultiplier;
  }

  public Duration getAttachTrustMaxRpcTimeout() {
    return this.attachTrustMaxRpcTimeout;
  }

  public void setAttachTrustMaxRpcTimeout(java.time.Duration attachTrustMaxRpcTimeout) {
    this.attachTrustMaxRpcTimeout = Duration.parse(attachTrustMaxRpcTimeout.toString());
  }

  public Duration getAttachTrustTotalTimeout() {
    return this.attachTrustTotalTimeout;
  }

  public void setAttachTrustTotalTimeout(java.time.Duration attachTrustTotalTimeout) {
    this.attachTrustTotalTimeout = Duration.parse(attachTrustTotalTimeout.toString());
  }

  public Duration getReconfigureTrustInitialRpcTimeout() {
    return this.reconfigureTrustInitialRpcTimeout;
  }

  public void setReconfigureTrustInitialRpcTimeout(
      java.time.Duration reconfigureTrustInitialRpcTimeout) {
    this.reconfigureTrustInitialRpcTimeout =
        Duration.parse(reconfigureTrustInitialRpcTimeout.toString());
  }

  public Double getReconfigureTrustRpcTimeoutMultiplier() {
    return this.reconfigureTrustRpcTimeoutMultiplier;
  }

  public void setReconfigureTrustRpcTimeoutMultiplier(Double reconfigureTrustRpcTimeoutMultiplier) {
    this.reconfigureTrustRpcTimeoutMultiplier = reconfigureTrustRpcTimeoutMultiplier;
  }

  public Duration getReconfigureTrustMaxRpcTimeout() {
    return this.reconfigureTrustMaxRpcTimeout;
  }

  public void setReconfigureTrustMaxRpcTimeout(java.time.Duration reconfigureTrustMaxRpcTimeout) {
    this.reconfigureTrustMaxRpcTimeout = Duration.parse(reconfigureTrustMaxRpcTimeout.toString());
  }

  public Duration getReconfigureTrustTotalTimeout() {
    return this.reconfigureTrustTotalTimeout;
  }

  public void setReconfigureTrustTotalTimeout(java.time.Duration reconfigureTrustTotalTimeout) {
    this.reconfigureTrustTotalTimeout = Duration.parse(reconfigureTrustTotalTimeout.toString());
  }

  public Duration getDetachTrustInitialRpcTimeout() {
    return this.detachTrustInitialRpcTimeout;
  }

  public void setDetachTrustInitialRpcTimeout(java.time.Duration detachTrustInitialRpcTimeout) {
    this.detachTrustInitialRpcTimeout = Duration.parse(detachTrustInitialRpcTimeout.toString());
  }

  public Double getDetachTrustRpcTimeoutMultiplier() {
    return this.detachTrustRpcTimeoutMultiplier;
  }

  public void setDetachTrustRpcTimeoutMultiplier(Double detachTrustRpcTimeoutMultiplier) {
    this.detachTrustRpcTimeoutMultiplier = detachTrustRpcTimeoutMultiplier;
  }

  public Duration getDetachTrustMaxRpcTimeout() {
    return this.detachTrustMaxRpcTimeout;
  }

  public void setDetachTrustMaxRpcTimeout(java.time.Duration detachTrustMaxRpcTimeout) {
    this.detachTrustMaxRpcTimeout = Duration.parse(detachTrustMaxRpcTimeout.toString());
  }

  public Duration getDetachTrustTotalTimeout() {
    return this.detachTrustTotalTimeout;
  }

  public void setDetachTrustTotalTimeout(java.time.Duration detachTrustTotalTimeout) {
    this.detachTrustTotalTimeout = Duration.parse(detachTrustTotalTimeout.toString());
  }

  public Duration getValidateTrustInitialRpcTimeout() {
    return this.validateTrustInitialRpcTimeout;
  }

  public void setValidateTrustInitialRpcTimeout(java.time.Duration validateTrustInitialRpcTimeout) {
    this.validateTrustInitialRpcTimeout = Duration.parse(validateTrustInitialRpcTimeout.toString());
  }

  public Double getValidateTrustRpcTimeoutMultiplier() {
    return this.validateTrustRpcTimeoutMultiplier;
  }

  public void setValidateTrustRpcTimeoutMultiplier(Double validateTrustRpcTimeoutMultiplier) {
    this.validateTrustRpcTimeoutMultiplier = validateTrustRpcTimeoutMultiplier;
  }

  public Duration getValidateTrustMaxRpcTimeout() {
    return this.validateTrustMaxRpcTimeout;
  }

  public void setValidateTrustMaxRpcTimeout(java.time.Duration validateTrustMaxRpcTimeout) {
    this.validateTrustMaxRpcTimeout = Duration.parse(validateTrustMaxRpcTimeout.toString());
  }

  public Duration getValidateTrustTotalTimeout() {
    return this.validateTrustTotalTimeout;
  }

  public void setValidateTrustTotalTimeout(java.time.Duration validateTrustTotalTimeout) {
    this.validateTrustTotalTimeout = Duration.parse(validateTrustTotalTimeout.toString());
  }
}
