/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.managedidentities.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.managedidentities.v1.ManagedIdentitiesServiceClient;
import com.google.cloud.managedidentities.v1.ManagedIdentitiesServiceSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link ManagedIdentitiesServiceClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(ManagedIdentitiesServiceClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.managedidentities.v1.managed-identities-service.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(ManagedIdentitiesServiceSpringProperties.class)
public class ManagedIdentitiesServiceSpringAutoConfiguration {
  private final ManagedIdentitiesServiceSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER =
      LogFactory.getLog(ManagedIdentitiesServiceSpringAutoConfiguration.class);

  protected ManagedIdentitiesServiceSpringAutoConfiguration(
      ManagedIdentitiesServiceSpringProperties clientProperties,
      CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from ManagedIdentitiesService-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultManagedIdentitiesServiceTransportChannelProvider")
  public TransportChannelProvider defaultManagedIdentitiesServiceTransportChannelProvider() {
    return ManagedIdentitiesServiceSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a ManagedIdentitiesServiceSettings bean configured to use a DefaultCredentialsProvider
   * and the client library's default transport channel provider
   * (defaultManagedIdentitiesServiceTransportChannelProvider()). It also configures the quota
   * project ID and executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in ManagedIdentitiesServiceSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link ManagedIdentitiesServiceSettings} bean configured with {@link
   *     TransportChannelProvider} bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public ManagedIdentitiesServiceSettings managedIdentitiesServiceSettings(
      @Qualifier("defaultManagedIdentitiesServiceTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    ManagedIdentitiesServiceSettings.Builder clientSettingsBuilder =
        ManagedIdentitiesServiceSettings.newBuilder();
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          ManagedIdentitiesServiceSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings resetAdminPasswordRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.resetAdminPasswordSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .resetAdminPasswordSettings()
          .setRetrySettings(resetAdminPasswordRetrySettings);

      RetrySettings listDomainsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listDomainsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listDomainsSettings().setRetrySettings(listDomainsRetrySettings);

      RetrySettings getDomainRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getDomainSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getDomainSettings().setRetrySettings(getDomainRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry resetAdminPasswordRetry = clientProperties.getResetAdminPasswordRetry();
    if (resetAdminPasswordRetry != null) {
      RetrySettings resetAdminPasswordRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.resetAdminPasswordSettings().getRetrySettings(),
              resetAdminPasswordRetry);
      clientSettingsBuilder
          .resetAdminPasswordSettings()
          .setRetrySettings(resetAdminPasswordRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for resetAdminPassword from properties.");
      }
    }
    Retry listDomainsRetry = clientProperties.getListDomainsRetry();
    if (listDomainsRetry != null) {
      RetrySettings listDomainsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listDomainsSettings().getRetrySettings(), listDomainsRetry);
      clientSettingsBuilder.listDomainsSettings().setRetrySettings(listDomainsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listDomains from properties.");
      }
    }
    Retry getDomainRetry = clientProperties.getGetDomainRetry();
    if (getDomainRetry != null) {
      RetrySettings getDomainRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getDomainSettings().getRetrySettings(), getDomainRetry);
      clientSettingsBuilder.getDomainSettings().setRetrySettings(getDomainRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getDomain from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a ManagedIdentitiesServiceClient bean configured with
   * ManagedIdentitiesServiceSettings.
   *
   * @param managedIdentitiesServiceSettings settings to configure an instance of client bean.
   * @return a {@link ManagedIdentitiesServiceClient} bean configured with {@link
   *     ManagedIdentitiesServiceSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public ManagedIdentitiesServiceClient managedIdentitiesServiceClient(
      ManagedIdentitiesServiceSettings managedIdentitiesServiceSettings) throws IOException {
    return ManagedIdentitiesServiceClient.create(managedIdentitiesServiceSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-managed-identities-service";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
