/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.accessapproval.v1.spring;

import com.google.api.core.BetaApi;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.CredentialsSupplier;
import javax.annotation.Generated;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;
import org.threeten.bp.Duration;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/** Provides default property values for AccessApproval client bean */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@ConfigurationProperties("com.google.cloud.accessapproval.v1.spring.auto.access-approval")
public class AccessApprovalSpringProperties implements CredentialsSupplier {
  @NestedConfigurationProperty
  private final Credentials credentials =
      new Credentials("https://www.googleapis.com/auth/cloud-platform");

  private String quotaProjectId;
  private Integer executorThreadCount;
  private boolean useRest = false;
  private Duration listApprovalRequestsInitialRetryDelay;
  private Double listApprovalRequestsRetryDelayMultiplier;
  private Duration listApprovalRequestsMaxRetryDelay;
  private Duration listApprovalRequestsInitialRpcTimeout;
  private Double listApprovalRequestsRpcTimeoutMultiplier;
  private Duration listApprovalRequestsMaxRpcTimeout;
  private Duration listApprovalRequestsTotalTimeout;
  private Duration getApprovalRequestInitialRetryDelay;
  private Double getApprovalRequestRetryDelayMultiplier;
  private Duration getApprovalRequestMaxRetryDelay;
  private Duration getApprovalRequestInitialRpcTimeout;
  private Double getApprovalRequestRpcTimeoutMultiplier;
  private Duration getApprovalRequestMaxRpcTimeout;
  private Duration getApprovalRequestTotalTimeout;
  private Duration approveApprovalRequestInitialRpcTimeout;
  private Double approveApprovalRequestRpcTimeoutMultiplier;
  private Duration approveApprovalRequestMaxRpcTimeout;
  private Duration approveApprovalRequestTotalTimeout;
  private Duration dismissApprovalRequestInitialRpcTimeout;
  private Double dismissApprovalRequestRpcTimeoutMultiplier;
  private Duration dismissApprovalRequestMaxRpcTimeout;
  private Duration dismissApprovalRequestTotalTimeout;
  private Duration invalidateApprovalRequestInitialRpcTimeout;
  private Double invalidateApprovalRequestRpcTimeoutMultiplier;
  private Duration invalidateApprovalRequestMaxRpcTimeout;
  private Duration invalidateApprovalRequestTotalTimeout;
  private Duration getAccessApprovalSettingsInitialRetryDelay;
  private Double getAccessApprovalSettingsRetryDelayMultiplier;
  private Duration getAccessApprovalSettingsMaxRetryDelay;
  private Duration getAccessApprovalSettingsInitialRpcTimeout;
  private Double getAccessApprovalSettingsRpcTimeoutMultiplier;
  private Duration getAccessApprovalSettingsMaxRpcTimeout;
  private Duration getAccessApprovalSettingsTotalTimeout;
  private Duration updateAccessApprovalSettingsInitialRpcTimeout;
  private Double updateAccessApprovalSettingsRpcTimeoutMultiplier;
  private Duration updateAccessApprovalSettingsMaxRpcTimeout;
  private Duration updateAccessApprovalSettingsTotalTimeout;
  private Duration deleteAccessApprovalSettingsInitialRpcTimeout;
  private Double deleteAccessApprovalSettingsRpcTimeoutMultiplier;
  private Duration deleteAccessApprovalSettingsMaxRpcTimeout;
  private Duration deleteAccessApprovalSettingsTotalTimeout;
  private Double getAccessApprovalServiceAccountRpcTimeoutMultiplier;

  @Override
  public Credentials getCredentials() {
    return this.credentials;
  }

  public String getQuotaProjectId() {
    return this.quotaProjectId;
  }

  public void setQuotaProjectId(String quotaProjectId) {
    this.quotaProjectId = quotaProjectId;
  }

  public boolean getUseRest() {
    return this.useRest;
  }

  public void setUseRest(boolean useRest) {
    this.useRest = useRest;
  }

  public Integer getExecutorThreadCount() {
    return this.executorThreadCount;
  }

  public void setExecutorThreadCount(Integer executorThreadCount) {
    this.executorThreadCount = executorThreadCount;
  }

  public Duration getListApprovalRequestsInitialRetryDelay() {
    return this.listApprovalRequestsInitialRetryDelay;
  }

  public void setListApprovalRequestsInitialRetryDelay(
      java.time.Duration listApprovalRequestsInitialRetryDelay) {
    this.listApprovalRequestsInitialRetryDelay =
        Duration.parse(listApprovalRequestsInitialRetryDelay.toString());
  }

  public Double getListApprovalRequestsRetryDelayMultiplier() {
    return this.listApprovalRequestsRetryDelayMultiplier;
  }

  public void setListApprovalRequestsRetryDelayMultiplier(
      Double listApprovalRequestsRetryDelayMultiplier) {
    this.listApprovalRequestsRetryDelayMultiplier = listApprovalRequestsRetryDelayMultiplier;
  }

  public Duration getListApprovalRequestsMaxRetryDelay() {
    return this.listApprovalRequestsMaxRetryDelay;
  }

  public void setListApprovalRequestsMaxRetryDelay(
      java.time.Duration listApprovalRequestsMaxRetryDelay) {
    this.listApprovalRequestsMaxRetryDelay =
        Duration.parse(listApprovalRequestsMaxRetryDelay.toString());
  }

  public Duration getListApprovalRequestsInitialRpcTimeout() {
    return this.listApprovalRequestsInitialRpcTimeout;
  }

  public void setListApprovalRequestsInitialRpcTimeout(
      java.time.Duration listApprovalRequestsInitialRpcTimeout) {
    this.listApprovalRequestsInitialRpcTimeout =
        Duration.parse(listApprovalRequestsInitialRpcTimeout.toString());
  }

  public Double getListApprovalRequestsRpcTimeoutMultiplier() {
    return this.listApprovalRequestsRpcTimeoutMultiplier;
  }

  public void setListApprovalRequestsRpcTimeoutMultiplier(
      Double listApprovalRequestsRpcTimeoutMultiplier) {
    this.listApprovalRequestsRpcTimeoutMultiplier = listApprovalRequestsRpcTimeoutMultiplier;
  }

  public Duration getListApprovalRequestsMaxRpcTimeout() {
    return this.listApprovalRequestsMaxRpcTimeout;
  }

  public void setListApprovalRequestsMaxRpcTimeout(
      java.time.Duration listApprovalRequestsMaxRpcTimeout) {
    this.listApprovalRequestsMaxRpcTimeout =
        Duration.parse(listApprovalRequestsMaxRpcTimeout.toString());
  }

  public Duration getListApprovalRequestsTotalTimeout() {
    return this.listApprovalRequestsTotalTimeout;
  }

  public void setListApprovalRequestsTotalTimeout(
      java.time.Duration listApprovalRequestsTotalTimeout) {
    this.listApprovalRequestsTotalTimeout =
        Duration.parse(listApprovalRequestsTotalTimeout.toString());
  }

  public Duration getGetApprovalRequestInitialRetryDelay() {
    return this.getApprovalRequestInitialRetryDelay;
  }

  public void setGetApprovalRequestInitialRetryDelay(
      java.time.Duration getApprovalRequestInitialRetryDelay) {
    this.getApprovalRequestInitialRetryDelay =
        Duration.parse(getApprovalRequestInitialRetryDelay.toString());
  }

  public Double getGetApprovalRequestRetryDelayMultiplier() {
    return this.getApprovalRequestRetryDelayMultiplier;
  }

  public void setGetApprovalRequestRetryDelayMultiplier(
      Double getApprovalRequestRetryDelayMultiplier) {
    this.getApprovalRequestRetryDelayMultiplier = getApprovalRequestRetryDelayMultiplier;
  }

  public Duration getGetApprovalRequestMaxRetryDelay() {
    return this.getApprovalRequestMaxRetryDelay;
  }

  public void setGetApprovalRequestMaxRetryDelay(
      java.time.Duration getApprovalRequestMaxRetryDelay) {
    this.getApprovalRequestMaxRetryDelay =
        Duration.parse(getApprovalRequestMaxRetryDelay.toString());
  }

  public Duration getGetApprovalRequestInitialRpcTimeout() {
    return this.getApprovalRequestInitialRpcTimeout;
  }

  public void setGetApprovalRequestInitialRpcTimeout(
      java.time.Duration getApprovalRequestInitialRpcTimeout) {
    this.getApprovalRequestInitialRpcTimeout =
        Duration.parse(getApprovalRequestInitialRpcTimeout.toString());
  }

  public Double getGetApprovalRequestRpcTimeoutMultiplier() {
    return this.getApprovalRequestRpcTimeoutMultiplier;
  }

  public void setGetApprovalRequestRpcTimeoutMultiplier(
      Double getApprovalRequestRpcTimeoutMultiplier) {
    this.getApprovalRequestRpcTimeoutMultiplier = getApprovalRequestRpcTimeoutMultiplier;
  }

  public Duration getGetApprovalRequestMaxRpcTimeout() {
    return this.getApprovalRequestMaxRpcTimeout;
  }

  public void setGetApprovalRequestMaxRpcTimeout(
      java.time.Duration getApprovalRequestMaxRpcTimeout) {
    this.getApprovalRequestMaxRpcTimeout =
        Duration.parse(getApprovalRequestMaxRpcTimeout.toString());
  }

  public Duration getGetApprovalRequestTotalTimeout() {
    return this.getApprovalRequestTotalTimeout;
  }

  public void setGetApprovalRequestTotalTimeout(java.time.Duration getApprovalRequestTotalTimeout) {
    this.getApprovalRequestTotalTimeout = Duration.parse(getApprovalRequestTotalTimeout.toString());
  }

  public Duration getApproveApprovalRequestInitialRpcTimeout() {
    return this.approveApprovalRequestInitialRpcTimeout;
  }

  public void setApproveApprovalRequestInitialRpcTimeout(
      java.time.Duration approveApprovalRequestInitialRpcTimeout) {
    this.approveApprovalRequestInitialRpcTimeout =
        Duration.parse(approveApprovalRequestInitialRpcTimeout.toString());
  }

  public Double getApproveApprovalRequestRpcTimeoutMultiplier() {
    return this.approveApprovalRequestRpcTimeoutMultiplier;
  }

  public void setApproveApprovalRequestRpcTimeoutMultiplier(
      Double approveApprovalRequestRpcTimeoutMultiplier) {
    this.approveApprovalRequestRpcTimeoutMultiplier = approveApprovalRequestRpcTimeoutMultiplier;
  }

  public Duration getApproveApprovalRequestMaxRpcTimeout() {
    return this.approveApprovalRequestMaxRpcTimeout;
  }

  public void setApproveApprovalRequestMaxRpcTimeout(
      java.time.Duration approveApprovalRequestMaxRpcTimeout) {
    this.approveApprovalRequestMaxRpcTimeout =
        Duration.parse(approveApprovalRequestMaxRpcTimeout.toString());
  }

  public Duration getApproveApprovalRequestTotalTimeout() {
    return this.approveApprovalRequestTotalTimeout;
  }

  public void setApproveApprovalRequestTotalTimeout(
      java.time.Duration approveApprovalRequestTotalTimeout) {
    this.approveApprovalRequestTotalTimeout =
        Duration.parse(approveApprovalRequestTotalTimeout.toString());
  }

  public Duration getDismissApprovalRequestInitialRpcTimeout() {
    return this.dismissApprovalRequestInitialRpcTimeout;
  }

  public void setDismissApprovalRequestInitialRpcTimeout(
      java.time.Duration dismissApprovalRequestInitialRpcTimeout) {
    this.dismissApprovalRequestInitialRpcTimeout =
        Duration.parse(dismissApprovalRequestInitialRpcTimeout.toString());
  }

  public Double getDismissApprovalRequestRpcTimeoutMultiplier() {
    return this.dismissApprovalRequestRpcTimeoutMultiplier;
  }

  public void setDismissApprovalRequestRpcTimeoutMultiplier(
      Double dismissApprovalRequestRpcTimeoutMultiplier) {
    this.dismissApprovalRequestRpcTimeoutMultiplier = dismissApprovalRequestRpcTimeoutMultiplier;
  }

  public Duration getDismissApprovalRequestMaxRpcTimeout() {
    return this.dismissApprovalRequestMaxRpcTimeout;
  }

  public void setDismissApprovalRequestMaxRpcTimeout(
      java.time.Duration dismissApprovalRequestMaxRpcTimeout) {
    this.dismissApprovalRequestMaxRpcTimeout =
        Duration.parse(dismissApprovalRequestMaxRpcTimeout.toString());
  }

  public Duration getDismissApprovalRequestTotalTimeout() {
    return this.dismissApprovalRequestTotalTimeout;
  }

  public void setDismissApprovalRequestTotalTimeout(
      java.time.Duration dismissApprovalRequestTotalTimeout) {
    this.dismissApprovalRequestTotalTimeout =
        Duration.parse(dismissApprovalRequestTotalTimeout.toString());
  }

  public Duration getInvalidateApprovalRequestInitialRpcTimeout() {
    return this.invalidateApprovalRequestInitialRpcTimeout;
  }

  public void setInvalidateApprovalRequestInitialRpcTimeout(
      java.time.Duration invalidateApprovalRequestInitialRpcTimeout) {
    this.invalidateApprovalRequestInitialRpcTimeout =
        Duration.parse(invalidateApprovalRequestInitialRpcTimeout.toString());
  }

  public Double getInvalidateApprovalRequestRpcTimeoutMultiplier() {
    return this.invalidateApprovalRequestRpcTimeoutMultiplier;
  }

  public void setInvalidateApprovalRequestRpcTimeoutMultiplier(
      Double invalidateApprovalRequestRpcTimeoutMultiplier) {
    this.invalidateApprovalRequestRpcTimeoutMultiplier =
        invalidateApprovalRequestRpcTimeoutMultiplier;
  }

  public Duration getInvalidateApprovalRequestMaxRpcTimeout() {
    return this.invalidateApprovalRequestMaxRpcTimeout;
  }

  public void setInvalidateApprovalRequestMaxRpcTimeout(
      java.time.Duration invalidateApprovalRequestMaxRpcTimeout) {
    this.invalidateApprovalRequestMaxRpcTimeout =
        Duration.parse(invalidateApprovalRequestMaxRpcTimeout.toString());
  }

  public Duration getInvalidateApprovalRequestTotalTimeout() {
    return this.invalidateApprovalRequestTotalTimeout;
  }

  public void setInvalidateApprovalRequestTotalTimeout(
      java.time.Duration invalidateApprovalRequestTotalTimeout) {
    this.invalidateApprovalRequestTotalTimeout =
        Duration.parse(invalidateApprovalRequestTotalTimeout.toString());
  }

  public Duration getGetAccessApprovalSettingsInitialRetryDelay() {
    return this.getAccessApprovalSettingsInitialRetryDelay;
  }

  public void setGetAccessApprovalSettingsInitialRetryDelay(
      java.time.Duration getAccessApprovalSettingsInitialRetryDelay) {
    this.getAccessApprovalSettingsInitialRetryDelay =
        Duration.parse(getAccessApprovalSettingsInitialRetryDelay.toString());
  }

  public Double getGetAccessApprovalSettingsRetryDelayMultiplier() {
    return this.getAccessApprovalSettingsRetryDelayMultiplier;
  }

  public void setGetAccessApprovalSettingsRetryDelayMultiplier(
      Double getAccessApprovalSettingsRetryDelayMultiplier) {
    this.getAccessApprovalSettingsRetryDelayMultiplier =
        getAccessApprovalSettingsRetryDelayMultiplier;
  }

  public Duration getGetAccessApprovalSettingsMaxRetryDelay() {
    return this.getAccessApprovalSettingsMaxRetryDelay;
  }

  public void setGetAccessApprovalSettingsMaxRetryDelay(
      java.time.Duration getAccessApprovalSettingsMaxRetryDelay) {
    this.getAccessApprovalSettingsMaxRetryDelay =
        Duration.parse(getAccessApprovalSettingsMaxRetryDelay.toString());
  }

  public Duration getGetAccessApprovalSettingsInitialRpcTimeout() {
    return this.getAccessApprovalSettingsInitialRpcTimeout;
  }

  public void setGetAccessApprovalSettingsInitialRpcTimeout(
      java.time.Duration getAccessApprovalSettingsInitialRpcTimeout) {
    this.getAccessApprovalSettingsInitialRpcTimeout =
        Duration.parse(getAccessApprovalSettingsInitialRpcTimeout.toString());
  }

  public Double getGetAccessApprovalSettingsRpcTimeoutMultiplier() {
    return this.getAccessApprovalSettingsRpcTimeoutMultiplier;
  }

  public void setGetAccessApprovalSettingsRpcTimeoutMultiplier(
      Double getAccessApprovalSettingsRpcTimeoutMultiplier) {
    this.getAccessApprovalSettingsRpcTimeoutMultiplier =
        getAccessApprovalSettingsRpcTimeoutMultiplier;
  }

  public Duration getGetAccessApprovalSettingsMaxRpcTimeout() {
    return this.getAccessApprovalSettingsMaxRpcTimeout;
  }

  public void setGetAccessApprovalSettingsMaxRpcTimeout(
      java.time.Duration getAccessApprovalSettingsMaxRpcTimeout) {
    this.getAccessApprovalSettingsMaxRpcTimeout =
        Duration.parse(getAccessApprovalSettingsMaxRpcTimeout.toString());
  }

  public Duration getGetAccessApprovalSettingsTotalTimeout() {
    return this.getAccessApprovalSettingsTotalTimeout;
  }

  public void setGetAccessApprovalSettingsTotalTimeout(
      java.time.Duration getAccessApprovalSettingsTotalTimeout) {
    this.getAccessApprovalSettingsTotalTimeout =
        Duration.parse(getAccessApprovalSettingsTotalTimeout.toString());
  }

  public Duration getUpdateAccessApprovalSettingsInitialRpcTimeout() {
    return this.updateAccessApprovalSettingsInitialRpcTimeout;
  }

  public void setUpdateAccessApprovalSettingsInitialRpcTimeout(
      java.time.Duration updateAccessApprovalSettingsInitialRpcTimeout) {
    this.updateAccessApprovalSettingsInitialRpcTimeout =
        Duration.parse(updateAccessApprovalSettingsInitialRpcTimeout.toString());
  }

  public Double getUpdateAccessApprovalSettingsRpcTimeoutMultiplier() {
    return this.updateAccessApprovalSettingsRpcTimeoutMultiplier;
  }

  public void setUpdateAccessApprovalSettingsRpcTimeoutMultiplier(
      Double updateAccessApprovalSettingsRpcTimeoutMultiplier) {
    this.updateAccessApprovalSettingsRpcTimeoutMultiplier =
        updateAccessApprovalSettingsRpcTimeoutMultiplier;
  }

  public Duration getUpdateAccessApprovalSettingsMaxRpcTimeout() {
    return this.updateAccessApprovalSettingsMaxRpcTimeout;
  }

  public void setUpdateAccessApprovalSettingsMaxRpcTimeout(
      java.time.Duration updateAccessApprovalSettingsMaxRpcTimeout) {
    this.updateAccessApprovalSettingsMaxRpcTimeout =
        Duration.parse(updateAccessApprovalSettingsMaxRpcTimeout.toString());
  }

  public Duration getUpdateAccessApprovalSettingsTotalTimeout() {
    return this.updateAccessApprovalSettingsTotalTimeout;
  }

  public void setUpdateAccessApprovalSettingsTotalTimeout(
      java.time.Duration updateAccessApprovalSettingsTotalTimeout) {
    this.updateAccessApprovalSettingsTotalTimeout =
        Duration.parse(updateAccessApprovalSettingsTotalTimeout.toString());
  }

  public Duration getDeleteAccessApprovalSettingsInitialRpcTimeout() {
    return this.deleteAccessApprovalSettingsInitialRpcTimeout;
  }

  public void setDeleteAccessApprovalSettingsInitialRpcTimeout(
      java.time.Duration deleteAccessApprovalSettingsInitialRpcTimeout) {
    this.deleteAccessApprovalSettingsInitialRpcTimeout =
        Duration.parse(deleteAccessApprovalSettingsInitialRpcTimeout.toString());
  }

  public Double getDeleteAccessApprovalSettingsRpcTimeoutMultiplier() {
    return this.deleteAccessApprovalSettingsRpcTimeoutMultiplier;
  }

  public void setDeleteAccessApprovalSettingsRpcTimeoutMultiplier(
      Double deleteAccessApprovalSettingsRpcTimeoutMultiplier) {
    this.deleteAccessApprovalSettingsRpcTimeoutMultiplier =
        deleteAccessApprovalSettingsRpcTimeoutMultiplier;
  }

  public Duration getDeleteAccessApprovalSettingsMaxRpcTimeout() {
    return this.deleteAccessApprovalSettingsMaxRpcTimeout;
  }

  public void setDeleteAccessApprovalSettingsMaxRpcTimeout(
      java.time.Duration deleteAccessApprovalSettingsMaxRpcTimeout) {
    this.deleteAccessApprovalSettingsMaxRpcTimeout =
        Duration.parse(deleteAccessApprovalSettingsMaxRpcTimeout.toString());
  }

  public Duration getDeleteAccessApprovalSettingsTotalTimeout() {
    return this.deleteAccessApprovalSettingsTotalTimeout;
  }

  public void setDeleteAccessApprovalSettingsTotalTimeout(
      java.time.Duration deleteAccessApprovalSettingsTotalTimeout) {
    this.deleteAccessApprovalSettingsTotalTimeout =
        Duration.parse(deleteAccessApprovalSettingsTotalTimeout.toString());
  }

  public Double getGetAccessApprovalServiceAccountRpcTimeoutMultiplier() {
    return this.getAccessApprovalServiceAccountRpcTimeoutMultiplier;
  }

  public void setGetAccessApprovalServiceAccountRpcTimeoutMultiplier(
      Double getAccessApprovalServiceAccountRpcTimeoutMultiplier) {
    this.getAccessApprovalServiceAccountRpcTimeoutMultiplier =
        getAccessApprovalServiceAccountRpcTimeoutMultiplier;
  }
}
