/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.gkehub.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.gkehub.v1.GkeHubClient;
import com.google.cloud.gkehub.v1.GkeHubSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link GkeHubClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(GkeHubClient.class)
@ConditionalOnProperty(value = "com.google.cloud.gkehub.v1.gke-hub.enabled", matchIfMissing = true)
@EnableConfigurationProperties(GkeHubSpringProperties.class)
public class GkeHubSpringAutoConfiguration {
  private final GkeHubSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(GkeHubSpringAutoConfiguration.class);

  protected GkeHubSpringAutoConfiguration(
      GkeHubSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from GkeHub-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultGkeHubTransportChannelProvider")
  public TransportChannelProvider defaultGkeHubTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return GkeHubSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return GkeHubSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a GkeHubSettings bean configured to use a DefaultCredentialsProvider and the client
   * library's default transport channel provider (defaultGkeHubTransportChannelProvider()). It also
   * configures the quota project ID and executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in GkeHubSpringProperties. Method-level properties will take precedence over service-level
   * properties if available, and client library defaults will be used if neither are specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link GkeHubSettings} bean configured with {@link TransportChannelProvider} bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public GkeHubSettings gkeHubSettings(
      @Qualifier("defaultGkeHubTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    GkeHubSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = GkeHubSettings.newHttpJsonBuilder();
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using REST (HTTP/JSON) transport.");
      }
    } else {
      clientSettingsBuilder = GkeHubSettings.newBuilder();
    }
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setEndpoint(GkeHubSettings.getDefaultEndpoint())
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          GkeHubSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listMembershipsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMembershipsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listMembershipsSettings()
          .setRetrySettings(listMembershipsRetrySettings);

      RetrySettings listBoundMembershipsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBoundMembershipsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listBoundMembershipsSettings()
          .setRetrySettings(listBoundMembershipsRetrySettings);

      RetrySettings listFeaturesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFeaturesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listFeaturesSettings().setRetrySettings(listFeaturesRetrySettings);

      RetrySettings getMembershipRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMembershipSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getMembershipSettings().setRetrySettings(getMembershipRetrySettings);

      RetrySettings getFeatureRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFeatureSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getFeatureSettings().setRetrySettings(getFeatureRetrySettings);

      RetrySettings generateConnectManifestRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.generateConnectManifestSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .generateConnectManifestSettings()
          .setRetrySettings(generateConnectManifestRetrySettings);

      RetrySettings getFleetRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFleetSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getFleetSettings().setRetrySettings(getFleetRetrySettings);

      RetrySettings listFleetsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFleetsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listFleetsSettings().setRetrySettings(listFleetsRetrySettings);

      RetrySettings getScopeNamespaceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getScopeNamespaceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getScopeNamespaceSettings()
          .setRetrySettings(getScopeNamespaceRetrySettings);

      RetrySettings listScopeNamespacesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listScopeNamespacesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listScopeNamespacesSettings()
          .setRetrySettings(listScopeNamespacesRetrySettings);

      RetrySettings getScopeRBACRoleBindingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getScopeRBACRoleBindingSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getScopeRBACRoleBindingSettings()
          .setRetrySettings(getScopeRBACRoleBindingRetrySettings);

      RetrySettings listScopeRBACRoleBindingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listScopeRBACRoleBindingsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listScopeRBACRoleBindingsSettings()
          .setRetrySettings(listScopeRBACRoleBindingsRetrySettings);

      RetrySettings getScopeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getScopeSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getScopeSettings().setRetrySettings(getScopeRetrySettings);

      RetrySettings listScopesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listScopesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listScopesSettings().setRetrySettings(listScopesRetrySettings);

      RetrySettings listPermittedScopesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listPermittedScopesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listPermittedScopesSettings()
          .setRetrySettings(listPermittedScopesRetrySettings);

      RetrySettings getMembershipBindingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMembershipBindingSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getMembershipBindingSettings()
          .setRetrySettings(getMembershipBindingRetrySettings);

      RetrySettings listMembershipBindingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMembershipBindingsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMembershipBindingsSettings()
          .setRetrySettings(listMembershipBindingsRetrySettings);

      RetrySettings getMembershipRBACRoleBindingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMembershipRBACRoleBindingSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getMembershipRBACRoleBindingSettings()
          .setRetrySettings(getMembershipRBACRoleBindingRetrySettings);

      RetrySettings listMembershipRBACRoleBindingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMembershipRBACRoleBindingsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMembershipRBACRoleBindingsSettings()
          .setRetrySettings(listMembershipRBACRoleBindingsRetrySettings);

      RetrySettings generateMembershipRBACRoleBindingYAMLRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder
                  .generateMembershipRBACRoleBindingYAMLSettings()
                  .getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .generateMembershipRBACRoleBindingYAMLSettings()
          .setRetrySettings(generateMembershipRBACRoleBindingYAMLRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listMembershipsRetry = clientProperties.getListMembershipsRetry();
    if (listMembershipsRetry != null) {
      RetrySettings listMembershipsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMembershipsSettings().getRetrySettings(),
              listMembershipsRetry);
      clientSettingsBuilder
          .listMembershipsSettings()
          .setRetrySettings(listMembershipsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listMemberships from properties.");
      }
    }
    Retry listBoundMembershipsRetry = clientProperties.getListBoundMembershipsRetry();
    if (listBoundMembershipsRetry != null) {
      RetrySettings listBoundMembershipsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBoundMembershipsSettings().getRetrySettings(),
              listBoundMembershipsRetry);
      clientSettingsBuilder
          .listBoundMembershipsSettings()
          .setRetrySettings(listBoundMembershipsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listBoundMemberships from properties.");
      }
    }
    Retry listFeaturesRetry = clientProperties.getListFeaturesRetry();
    if (listFeaturesRetry != null) {
      RetrySettings listFeaturesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFeaturesSettings().getRetrySettings(), listFeaturesRetry);
      clientSettingsBuilder.listFeaturesSettings().setRetrySettings(listFeaturesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listFeatures from properties.");
      }
    }
    Retry getMembershipRetry = clientProperties.getGetMembershipRetry();
    if (getMembershipRetry != null) {
      RetrySettings getMembershipRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMembershipSettings().getRetrySettings(), getMembershipRetry);
      clientSettingsBuilder.getMembershipSettings().setRetrySettings(getMembershipRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getMembership from properties.");
      }
    }
    Retry getFeatureRetry = clientProperties.getGetFeatureRetry();
    if (getFeatureRetry != null) {
      RetrySettings getFeatureRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFeatureSettings().getRetrySettings(), getFeatureRetry);
      clientSettingsBuilder.getFeatureSettings().setRetrySettings(getFeatureRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getFeature from properties.");
      }
    }
    Retry generateConnectManifestRetry = clientProperties.getGenerateConnectManifestRetry();
    if (generateConnectManifestRetry != null) {
      RetrySettings generateConnectManifestRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.generateConnectManifestSettings().getRetrySettings(),
              generateConnectManifestRetry);
      clientSettingsBuilder
          .generateConnectManifestSettings()
          .setRetrySettings(generateConnectManifestRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for generateConnectManifest from properties.");
      }
    }
    Retry getFleetRetry = clientProperties.getGetFleetRetry();
    if (getFleetRetry != null) {
      RetrySettings getFleetRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFleetSettings().getRetrySettings(), getFleetRetry);
      clientSettingsBuilder.getFleetSettings().setRetrySettings(getFleetRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getFleet from properties.");
      }
    }
    Retry listFleetsRetry = clientProperties.getListFleetsRetry();
    if (listFleetsRetry != null) {
      RetrySettings listFleetsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFleetsSettings().getRetrySettings(), listFleetsRetry);
      clientSettingsBuilder.listFleetsSettings().setRetrySettings(listFleetsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listFleets from properties.");
      }
    }
    Retry getScopeNamespaceRetry = clientProperties.getGetScopeNamespaceRetry();
    if (getScopeNamespaceRetry != null) {
      RetrySettings getScopeNamespaceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getScopeNamespaceSettings().getRetrySettings(),
              getScopeNamespaceRetry);
      clientSettingsBuilder
          .getScopeNamespaceSettings()
          .setRetrySettings(getScopeNamespaceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getScopeNamespace from properties.");
      }
    }
    Retry listScopeNamespacesRetry = clientProperties.getListScopeNamespacesRetry();
    if (listScopeNamespacesRetry != null) {
      RetrySettings listScopeNamespacesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listScopeNamespacesSettings().getRetrySettings(),
              listScopeNamespacesRetry);
      clientSettingsBuilder
          .listScopeNamespacesSettings()
          .setRetrySettings(listScopeNamespacesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listScopeNamespaces from properties.");
      }
    }
    Retry getScopeRBACRoleBindingRetry = clientProperties.getGetScopeRBACRoleBindingRetry();
    if (getScopeRBACRoleBindingRetry != null) {
      RetrySettings getScopeRBACRoleBindingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getScopeRBACRoleBindingSettings().getRetrySettings(),
              getScopeRBACRoleBindingRetry);
      clientSettingsBuilder
          .getScopeRBACRoleBindingSettings()
          .setRetrySettings(getScopeRBACRoleBindingRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getScopeRBACRoleBinding from properties.");
      }
    }
    Retry listScopeRBACRoleBindingsRetry = clientProperties.getListScopeRBACRoleBindingsRetry();
    if (listScopeRBACRoleBindingsRetry != null) {
      RetrySettings listScopeRBACRoleBindingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listScopeRBACRoleBindingsSettings().getRetrySettings(),
              listScopeRBACRoleBindingsRetry);
      clientSettingsBuilder
          .listScopeRBACRoleBindingsSettings()
          .setRetrySettings(listScopeRBACRoleBindingsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listScopeRBACRoleBindings from properties.");
      }
    }
    Retry getScopeRetry = clientProperties.getGetScopeRetry();
    if (getScopeRetry != null) {
      RetrySettings getScopeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getScopeSettings().getRetrySettings(), getScopeRetry);
      clientSettingsBuilder.getScopeSettings().setRetrySettings(getScopeRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getScope from properties.");
      }
    }
    Retry listScopesRetry = clientProperties.getListScopesRetry();
    if (listScopesRetry != null) {
      RetrySettings listScopesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listScopesSettings().getRetrySettings(), listScopesRetry);
      clientSettingsBuilder.listScopesSettings().setRetrySettings(listScopesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listScopes from properties.");
      }
    }
    Retry listPermittedScopesRetry = clientProperties.getListPermittedScopesRetry();
    if (listPermittedScopesRetry != null) {
      RetrySettings listPermittedScopesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listPermittedScopesSettings().getRetrySettings(),
              listPermittedScopesRetry);
      clientSettingsBuilder
          .listPermittedScopesSettings()
          .setRetrySettings(listPermittedScopesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listPermittedScopes from properties.");
      }
    }
    Retry getMembershipBindingRetry = clientProperties.getGetMembershipBindingRetry();
    if (getMembershipBindingRetry != null) {
      RetrySettings getMembershipBindingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMembershipBindingSettings().getRetrySettings(),
              getMembershipBindingRetry);
      clientSettingsBuilder
          .getMembershipBindingSettings()
          .setRetrySettings(getMembershipBindingRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMembershipBinding from properties.");
      }
    }
    Retry listMembershipBindingsRetry = clientProperties.getListMembershipBindingsRetry();
    if (listMembershipBindingsRetry != null) {
      RetrySettings listMembershipBindingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMembershipBindingsSettings().getRetrySettings(),
              listMembershipBindingsRetry);
      clientSettingsBuilder
          .listMembershipBindingsSettings()
          .setRetrySettings(listMembershipBindingsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMembershipBindings from properties.");
      }
    }
    Retry getMembershipRBACRoleBindingRetry =
        clientProperties.getGetMembershipRBACRoleBindingRetry();
    if (getMembershipRBACRoleBindingRetry != null) {
      RetrySettings getMembershipRBACRoleBindingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMembershipRBACRoleBindingSettings().getRetrySettings(),
              getMembershipRBACRoleBindingRetry);
      clientSettingsBuilder
          .getMembershipRBACRoleBindingSettings()
          .setRetrySettings(getMembershipRBACRoleBindingRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMembershipRBACRoleBinding from properties.");
      }
    }
    Retry listMembershipRBACRoleBindingsRetry =
        clientProperties.getListMembershipRBACRoleBindingsRetry();
    if (listMembershipRBACRoleBindingsRetry != null) {
      RetrySettings listMembershipRBACRoleBindingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMembershipRBACRoleBindingsSettings().getRetrySettings(),
              listMembershipRBACRoleBindingsRetry);
      clientSettingsBuilder
          .listMembershipRBACRoleBindingsSettings()
          .setRetrySettings(listMembershipRBACRoleBindingsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMembershipRBACRoleBindings from properties.");
      }
    }
    Retry generateMembershipRBACRoleBindingYAMLRetry =
        clientProperties.getGenerateMembershipRBACRoleBindingYAMLRetry();
    if (generateMembershipRBACRoleBindingYAMLRetry != null) {
      RetrySettings generateMembershipRBACRoleBindingYAMLRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder
                  .generateMembershipRBACRoleBindingYAMLSettings()
                  .getRetrySettings(),
              generateMembershipRBACRoleBindingYAMLRetry);
      clientSettingsBuilder
          .generateMembershipRBACRoleBindingYAMLSettings()
          .setRetrySettings(generateMembershipRBACRoleBindingYAMLRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for generateMembershipRBACRoleBindingYAML from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a GkeHubClient bean configured with GkeHubSettings.
   *
   * @param gkeHubSettings settings to configure an instance of client bean.
   * @return a {@link GkeHubClient} bean configured with {@link GkeHubSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public GkeHubClient gkeHubClient(GkeHubSettings gkeHubSettings) throws IOException {
    return GkeHubClient.create(gkeHubSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-gke-hub";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
