/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.monitoring.v3.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.monitoring.v3.MetricServiceClient;
import com.google.cloud.monitoring.v3.MetricServiceSettings;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link MetricServiceClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@ConditionalOnClass(MetricServiceClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.monitoring.v3.spring.auto.metric-service.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(MetricServiceSpringProperties.class)
public class MetricServiceSpringAutoConfiguration {
  private final MetricServiceSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(MetricServiceSpringAutoConfiguration.class);

  protected MetricServiceSpringAutoConfiguration(
      MetricServiceSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from MetricService-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Returns the default channel provider. The default is gRPC and will default to it unless the
   * useRest option is provided to use HTTP transport instead
   */
  @Bean
  @ConditionalOnMissingBean
  public TransportChannelProvider defaultMetricServiceTransportChannelProvider() {
    return MetricServiceSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a MetricServiceClient bean configured to use the default credentials provider
   * (obtained with metricServiceCredentials()) and its default transport channel provider
   * (defaultMetricServiceTransportChannelProvider()). It also configures the quota project ID if
   * provided. It will configure an executor provider in case there is more than one thread
   * configured in the client
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in MetricServiceSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   */
  @Bean
  @ConditionalOnMissingBean
  public MetricServiceSettings metricServiceSettings(
      @Qualifier("defaultMetricServiceTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    MetricServiceSettings.Builder clientSettingsBuilder =
        MetricServiceSettings.newBuilder()
            .setCredentialsProvider(this.credentialsProvider)
            .setTransportChannelProvider(defaultTransportChannelProvider)
            .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          MetricServiceSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listMonitoredResourceDescriptorsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMonitoredResourceDescriptorsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMonitoredResourceDescriptorsSettings()
          .setRetrySettings(listMonitoredResourceDescriptorsRetrySettings);

      RetrySettings getMonitoredResourceDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMonitoredResourceDescriptorSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getMonitoredResourceDescriptorSettings()
          .setRetrySettings(getMonitoredResourceDescriptorRetrySettings);

      RetrySettings listMetricDescriptorsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMetricDescriptorsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listMetricDescriptorsSettings()
          .setRetrySettings(listMetricDescriptorsRetrySettings);

      RetrySettings getMetricDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMetricDescriptorSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getMetricDescriptorSettings()
          .setRetrySettings(getMetricDescriptorRetrySettings);

      RetrySettings createMetricDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createMetricDescriptorSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .createMetricDescriptorSettings()
          .setRetrySettings(createMetricDescriptorRetrySettings);

      RetrySettings deleteMetricDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteMetricDescriptorSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .deleteMetricDescriptorSettings()
          .setRetrySettings(deleteMetricDescriptorRetrySettings);

      RetrySettings listTimeSeriesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listTimeSeriesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listTimeSeriesSettings().setRetrySettings(listTimeSeriesRetrySettings);

      RetrySettings createTimeSeriesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createTimeSeriesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .createTimeSeriesSettings()
          .setRetrySettings(createTimeSeriesRetrySettings);

      RetrySettings createServiceTimeSeriesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createServiceTimeSeriesSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .createServiceTimeSeriesSettings()
          .setRetrySettings(createServiceTimeSeriesRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listMonitoredResourceDescriptorsRetry =
        clientProperties.getListMonitoredResourceDescriptorsRetry();
    if (listMonitoredResourceDescriptorsRetry != null) {
      RetrySettings listMonitoredResourceDescriptorsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMonitoredResourceDescriptorsSettings().getRetrySettings(),
              listMonitoredResourceDescriptorsRetry);
      clientSettingsBuilder
          .listMonitoredResourceDescriptorsSettings()
          .setRetrySettings(listMonitoredResourceDescriptorsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMonitoredResourceDescriptors from properties.");
      }
    }
    Retry getMonitoredResourceDescriptorRetry =
        clientProperties.getGetMonitoredResourceDescriptorRetry();
    if (getMonitoredResourceDescriptorRetry != null) {
      RetrySettings getMonitoredResourceDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMonitoredResourceDescriptorSettings().getRetrySettings(),
              getMonitoredResourceDescriptorRetry);
      clientSettingsBuilder
          .getMonitoredResourceDescriptorSettings()
          .setRetrySettings(getMonitoredResourceDescriptorRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMonitoredResourceDescriptor from properties.");
      }
    }
    Retry listMetricDescriptorsRetry = clientProperties.getListMetricDescriptorsRetry();
    if (listMetricDescriptorsRetry != null) {
      RetrySettings listMetricDescriptorsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listMetricDescriptorsSettings().getRetrySettings(),
              listMetricDescriptorsRetry);
      clientSettingsBuilder
          .listMetricDescriptorsSettings()
          .setRetrySettings(listMetricDescriptorsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listMetricDescriptors from properties.");
      }
    }
    Retry getMetricDescriptorRetry = clientProperties.getGetMetricDescriptorRetry();
    if (getMetricDescriptorRetry != null) {
      RetrySettings getMetricDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getMetricDescriptorSettings().getRetrySettings(),
              getMetricDescriptorRetry);
      clientSettingsBuilder
          .getMetricDescriptorSettings()
          .setRetrySettings(getMetricDescriptorRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getMetricDescriptor from properties.");
      }
    }
    Retry createMetricDescriptorRetry = clientProperties.getCreateMetricDescriptorRetry();
    if (createMetricDescriptorRetry != null) {
      RetrySettings createMetricDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createMetricDescriptorSettings().getRetrySettings(),
              createMetricDescriptorRetry);
      clientSettingsBuilder
          .createMetricDescriptorSettings()
          .setRetrySettings(createMetricDescriptorRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for createMetricDescriptor from properties.");
      }
    }
    Retry deleteMetricDescriptorRetry = clientProperties.getDeleteMetricDescriptorRetry();
    if (deleteMetricDescriptorRetry != null) {
      RetrySettings deleteMetricDescriptorRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteMetricDescriptorSettings().getRetrySettings(),
              deleteMetricDescriptorRetry);
      clientSettingsBuilder
          .deleteMetricDescriptorSettings()
          .setRetrySettings(deleteMetricDescriptorRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for deleteMetricDescriptor from properties.");
      }
    }
    Retry listTimeSeriesRetry = clientProperties.getListTimeSeriesRetry();
    if (listTimeSeriesRetry != null) {
      RetrySettings listTimeSeriesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listTimeSeriesSettings().getRetrySettings(),
              listTimeSeriesRetry);
      clientSettingsBuilder.listTimeSeriesSettings().setRetrySettings(listTimeSeriesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listTimeSeries from properties.");
      }
    }
    Retry createTimeSeriesRetry = clientProperties.getCreateTimeSeriesRetry();
    if (createTimeSeriesRetry != null) {
      RetrySettings createTimeSeriesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createTimeSeriesSettings().getRetrySettings(),
              createTimeSeriesRetry);
      clientSettingsBuilder
          .createTimeSeriesSettings()
          .setRetrySettings(createTimeSeriesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for createTimeSeries from properties.");
      }
    }
    Retry createServiceTimeSeriesRetry = clientProperties.getCreateServiceTimeSeriesRetry();
    if (createServiceTimeSeriesRetry != null) {
      RetrySettings createServiceTimeSeriesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createServiceTimeSeriesSettings().getRetrySettings(),
              createServiceTimeSeriesRetry);
      clientSettingsBuilder
          .createServiceTimeSeriesSettings()
          .setRetrySettings(createServiceTimeSeriesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for createServiceTimeSeries from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public MetricServiceClient metricServiceClient(MetricServiceSettings metricServiceSettings)
      throws IOException {
    return MetricServiceClient.create(metricServiceSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-metric-service";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
