/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.dialogflow.v2.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.dialogflow.v2.AgentsClient;
import com.google.cloud.dialogflow.v2.AgentsSettings;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link AgentsClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@ConditionalOnClass(AgentsClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.dialogflow.v2.spring.auto.agents.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(AgentsSpringProperties.class)
public class AgentsSpringAutoConfiguration {
  private final AgentsSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(AgentsSpringAutoConfiguration.class);

  protected AgentsSpringAutoConfiguration(
      AgentsSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from Agents-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Returns the default channel provider. The default is gRPC and will default to it unless the
   * useRest option is provided to use HTTP transport instead
   */
  @Bean
  @ConditionalOnMissingBean
  public TransportChannelProvider defaultAgentsTransportChannelProvider() {
    return AgentsSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a AgentsClient bean configured to use the default credentials provider (obtained with
   * agentsCredentials()) and its default transport channel provider
   * (defaultAgentsTransportChannelProvider()). It also configures the quota project ID if provided.
   * It will configure an executor provider in case there is more than one thread configured in the
   * client
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in AgentsSpringProperties. Method-level properties will take precedence over service-level
   * properties if available, and client library defaults will be used if neither are specified.
   */
  @Bean
  @ConditionalOnMissingBean
  public AgentsSettings agentsSettings(
      @Qualifier("defaultAgentsTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    AgentsSettings.Builder clientSettingsBuilder =
        AgentsSettings.newBuilder()
            .setCredentialsProvider(this.credentialsProvider)
            .setTransportChannelProvider(defaultTransportChannelProvider)
            .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          AgentsSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder.setTransportChannelProvider(
          AgentsSettings.defaultHttpJsonTransportProviderBuilder().build());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using HTTP transport channel");
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings getAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAgentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getAgentSettings().setRetrySettings(getAgentRetrySettings);

      RetrySettings setAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setAgentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.setAgentSettings().setRetrySettings(setAgentRetrySettings);

      RetrySettings deleteAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteAgentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.deleteAgentSettings().setRetrySettings(deleteAgentRetrySettings);

      RetrySettings searchAgentsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.searchAgentsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.searchAgentsSettings().setRetrySettings(searchAgentsRetrySettings);

      RetrySettings trainAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.trainAgentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.trainAgentSettings().setRetrySettings(trainAgentRetrySettings);

      RetrySettings exportAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.exportAgentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.exportAgentSettings().setRetrySettings(exportAgentRetrySettings);

      RetrySettings importAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.importAgentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.importAgentSettings().setRetrySettings(importAgentRetrySettings);

      RetrySettings restoreAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.restoreAgentSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.restoreAgentSettings().setRetrySettings(restoreAgentRetrySettings);

      RetrySettings getValidationResultRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getValidationResultSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getValidationResultSettings()
          .setRetrySettings(getValidationResultRetrySettings);

      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);

      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry getAgentRetry = clientProperties.getGetAgentRetry();
    if (getAgentRetry != null) {
      RetrySettings getAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAgentSettings().getRetrySettings(), getAgentRetry);
      clientSettingsBuilder.getAgentSettings().setRetrySettings(getAgentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getAgent from properties.");
      }
    }
    Retry setAgentRetry = clientProperties.getSetAgentRetry();
    if (setAgentRetry != null) {
      RetrySettings setAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setAgentSettings().getRetrySettings(), setAgentRetry);
      clientSettingsBuilder.setAgentSettings().setRetrySettings(setAgentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for setAgent from properties.");
      }
    }
    Retry deleteAgentRetry = clientProperties.getDeleteAgentRetry();
    if (deleteAgentRetry != null) {
      RetrySettings deleteAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteAgentSettings().getRetrySettings(), deleteAgentRetry);
      clientSettingsBuilder.deleteAgentSettings().setRetrySettings(deleteAgentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for deleteAgent from properties.");
      }
    }
    Retry searchAgentsRetry = clientProperties.getSearchAgentsRetry();
    if (searchAgentsRetry != null) {
      RetrySettings searchAgentsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.searchAgentsSettings().getRetrySettings(), searchAgentsRetry);
      clientSettingsBuilder.searchAgentsSettings().setRetrySettings(searchAgentsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for searchAgents from properties.");
      }
    }
    Retry trainAgentRetry = clientProperties.getTrainAgentRetry();
    if (trainAgentRetry != null) {
      RetrySettings trainAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.trainAgentSettings().getRetrySettings(), trainAgentRetry);
      clientSettingsBuilder.trainAgentSettings().setRetrySettings(trainAgentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for trainAgent from properties.");
      }
    }
    Retry exportAgentRetry = clientProperties.getExportAgentRetry();
    if (exportAgentRetry != null) {
      RetrySettings exportAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.exportAgentSettings().getRetrySettings(), exportAgentRetry);
      clientSettingsBuilder.exportAgentSettings().setRetrySettings(exportAgentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for exportAgent from properties.");
      }
    }
    Retry importAgentRetry = clientProperties.getImportAgentRetry();
    if (importAgentRetry != null) {
      RetrySettings importAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.importAgentSettings().getRetrySettings(), importAgentRetry);
      clientSettingsBuilder.importAgentSettings().setRetrySettings(importAgentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for importAgent from properties.");
      }
    }
    Retry restoreAgentRetry = clientProperties.getRestoreAgentRetry();
    if (restoreAgentRetry != null) {
      RetrySettings restoreAgentRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.restoreAgentSettings().getRetrySettings(), restoreAgentRetry);
      clientSettingsBuilder.restoreAgentSettings().setRetrySettings(restoreAgentRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for restoreAgent from properties.");
      }
    }
    Retry getValidationResultRetry = clientProperties.getGetValidationResultRetry();
    if (getValidationResultRetry != null) {
      RetrySettings getValidationResultRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getValidationResultSettings().getRetrySettings(),
              getValidationResultRetry);
      clientSettingsBuilder
          .getValidationResultSettings()
          .setRetrySettings(getValidationResultRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getValidationResult from properties.");
      }
    }
    Retry listLocationsRetry = clientProperties.getListLocationsRetry();
    if (listLocationsRetry != null) {
      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), listLocationsRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listLocations from properties.");
      }
    }
    Retry getLocationRetry = clientProperties.getGetLocationRetry();
    if (getLocationRetry != null) {
      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), getLocationRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getLocation from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public AgentsClient agentsClient(AgentsSettings agentsSettings) throws IOException {
    return AgentsClient.create(agentsSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-agents";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
