/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.dialogflow.v2.spring;

import com.google.api.core.BetaApi;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.CredentialsSupplier;
import com.google.cloud.spring.core.Retry;
import javax.annotation.Generated;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/** Provides default property values for KnowledgeBases client bean */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@ConfigurationProperties("com.google.cloud.dialogflow.v2.knowledge-bases")
public class KnowledgeBasesSpringProperties implements CredentialsSupplier {
  /** OAuth2 credentials to authenticate and authorize calls to Google Cloud Client Libraries. */
  @NestedConfigurationProperty
  private final Credentials credentials =
      new Credentials(
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/dialogflow");
  /** Quota project to use for billing. */
  private String quotaProjectId;
  /** Number of threads used for executors. */
  private Integer executorThreadCount;
  /** Allow override of default transport channel provider to use REST instead of gRPC. */
  private boolean useRest = false;
  /** Allow override of retry settings at service level, applying to all of its RPC methods. */
  @NestedConfigurationProperty private Retry retry;
  /**
   * Allow override of retry settings at method-level for listKnowledgeBases. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listKnowledgeBasesRetry;
  /**
   * Allow override of retry settings at method-level for getKnowledgeBase. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getKnowledgeBaseRetry;
  /**
   * Allow override of retry settings at method-level for createKnowledgeBase. If defined, this
   * takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry createKnowledgeBaseRetry;
  /**
   * Allow override of retry settings at method-level for deleteKnowledgeBase. If defined, this
   * takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry deleteKnowledgeBaseRetry;
  /**
   * Allow override of retry settings at method-level for updateKnowledgeBase. If defined, this
   * takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry updateKnowledgeBaseRetry;
  /**
   * Allow override of retry settings at method-level for listLocations. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listLocationsRetry;
  /**
   * Allow override of retry settings at method-level for getLocation. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getLocationRetry;

  @Override
  public Credentials getCredentials() {
    return this.credentials;
  }

  public String getQuotaProjectId() {
    return this.quotaProjectId;
  }

  public void setQuotaProjectId(String quotaProjectId) {
    this.quotaProjectId = quotaProjectId;
  }

  public boolean getUseRest() {
    return this.useRest;
  }

  public void setUseRest(boolean useRest) {
    this.useRest = useRest;
  }

  public Integer getExecutorThreadCount() {
    return this.executorThreadCount;
  }

  public void setExecutorThreadCount(Integer executorThreadCount) {
    this.executorThreadCount = executorThreadCount;
  }

  public Retry getRetry() {
    return this.retry;
  }

  public void setRetry(Retry retry) {
    this.retry = retry;
  }

  public Retry getListKnowledgeBasesRetry() {
    return this.listKnowledgeBasesRetry;
  }

  public void setListKnowledgeBasesRetry(Retry listKnowledgeBasesRetry) {
    this.listKnowledgeBasesRetry = listKnowledgeBasesRetry;
  }

  public Retry getGetKnowledgeBaseRetry() {
    return this.getKnowledgeBaseRetry;
  }

  public void setGetKnowledgeBaseRetry(Retry getKnowledgeBaseRetry) {
    this.getKnowledgeBaseRetry = getKnowledgeBaseRetry;
  }

  public Retry getCreateKnowledgeBaseRetry() {
    return this.createKnowledgeBaseRetry;
  }

  public void setCreateKnowledgeBaseRetry(Retry createKnowledgeBaseRetry) {
    this.createKnowledgeBaseRetry = createKnowledgeBaseRetry;
  }

  public Retry getDeleteKnowledgeBaseRetry() {
    return this.deleteKnowledgeBaseRetry;
  }

  public void setDeleteKnowledgeBaseRetry(Retry deleteKnowledgeBaseRetry) {
    this.deleteKnowledgeBaseRetry = deleteKnowledgeBaseRetry;
  }

  public Retry getUpdateKnowledgeBaseRetry() {
    return this.updateKnowledgeBaseRetry;
  }

  public void setUpdateKnowledgeBaseRetry(Retry updateKnowledgeBaseRetry) {
    this.updateKnowledgeBaseRetry = updateKnowledgeBaseRetry;
  }

  public Retry getListLocationsRetry() {
    return this.listLocationsRetry;
  }

  public void setListLocationsRetry(Retry listLocationsRetry) {
    this.listLocationsRetry = listLocationsRetry;
  }

  public Retry getGetLocationRetry() {
    return this.getLocationRetry;
  }

  public void setGetLocationRetry(Retry getLocationRetry) {
    this.getLocationRetry = getLocationRetry;
  }
}
