/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.dialogflow.v2.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.dialogflow.v2.ToolsClient;
import com.google.cloud.dialogflow.v2.ToolsSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link ToolsClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(ToolsClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.dialogflow.v2.tools.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(ToolsSpringProperties.class)
public class ToolsSpringAutoConfiguration {
  private final ToolsSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(ToolsSpringAutoConfiguration.class);

  protected ToolsSpringAutoConfiguration(
      ToolsSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from Tools-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultToolsTransportChannelProvider")
  public TransportChannelProvider defaultToolsTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return ToolsSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return ToolsSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a ToolsSettings bean configured to use a DefaultCredentialsProvider and the client
   * library's default transport channel provider (defaultToolsTransportChannelProvider()). It also
   * configures the quota project ID and executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in ToolsSpringProperties. Method-level properties will take precedence over service-level
   * properties if available, and client library defaults will be used if neither are specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link ToolsSettings} bean configured with {@link TransportChannelProvider} bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public ToolsSettings toolsSettings(
      @Qualifier("defaultToolsTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    ToolsSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = ToolsSettings.newHttpJsonBuilder();
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using REST (HTTP/JSON) transport.");
      }
    } else {
      clientSettingsBuilder = ToolsSettings.newBuilder();
    }
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setEndpoint(ToolsSettings.getDefaultEndpoint())
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          ToolsSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings createToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createToolSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.createToolSettings().setRetrySettings(createToolRetrySettings);

      RetrySettings getToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getToolSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getToolSettings().setRetrySettings(getToolRetrySettings);

      RetrySettings listToolsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listToolsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listToolsSettings().setRetrySettings(listToolsRetrySettings);

      RetrySettings deleteToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteToolSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.deleteToolSettings().setRetrySettings(deleteToolRetrySettings);

      RetrySettings updateToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateToolSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.updateToolSettings().setRetrySettings(updateToolRetrySettings);

      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);

      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry createToolRetry = clientProperties.getCreateToolRetry();
    if (createToolRetry != null) {
      RetrySettings createToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createToolSettings().getRetrySettings(), createToolRetry);
      clientSettingsBuilder.createToolSettings().setRetrySettings(createToolRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for createTool from properties.");
      }
    }
    Retry getToolRetry = clientProperties.getGetToolRetry();
    if (getToolRetry != null) {
      RetrySettings getToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getToolSettings().getRetrySettings(), getToolRetry);
      clientSettingsBuilder.getToolSettings().setRetrySettings(getToolRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getTool from properties.");
      }
    }
    Retry listToolsRetry = clientProperties.getListToolsRetry();
    if (listToolsRetry != null) {
      RetrySettings listToolsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listToolsSettings().getRetrySettings(), listToolsRetry);
      clientSettingsBuilder.listToolsSettings().setRetrySettings(listToolsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listTools from properties.");
      }
    }
    Retry deleteToolRetry = clientProperties.getDeleteToolRetry();
    if (deleteToolRetry != null) {
      RetrySettings deleteToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteToolSettings().getRetrySettings(), deleteToolRetry);
      clientSettingsBuilder.deleteToolSettings().setRetrySettings(deleteToolRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for deleteTool from properties.");
      }
    }
    Retry updateToolRetry = clientProperties.getUpdateToolRetry();
    if (updateToolRetry != null) {
      RetrySettings updateToolRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateToolSettings().getRetrySettings(), updateToolRetry);
      clientSettingsBuilder.updateToolSettings().setRetrySettings(updateToolRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for updateTool from properties.");
      }
    }
    Retry listLocationsRetry = clientProperties.getListLocationsRetry();
    if (listLocationsRetry != null) {
      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), listLocationsRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listLocations from properties.");
      }
    }
    Retry getLocationRetry = clientProperties.getGetLocationRetry();
    if (getLocationRetry != null) {
      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), getLocationRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getLocation from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a ToolsClient bean configured with ToolsSettings.
   *
   * @param toolsSettings settings to configure an instance of client bean.
   * @return a {@link ToolsClient} bean configured with {@link ToolsSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public ToolsClient toolsClient(ToolsSettings toolsSettings) throws IOException {
    return ToolsClient.create(toolsSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-tools";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
