# Cloud Spanner R2DBC Driver V2 (Client Library-based)

The original version of Cloud Spanner R2DBC driver was based on direct communication to Cloud Spanner gRPC endpoints.
V2 is built on top of the Cloud Spanner client library, allowing for consistent behavior between JDBC and R2DBC drivers.

To activate V2, provide an option named `client-implementation` with the value of `client-library`, as in the example below.
```java
ConnectionFactories.get(
          ConnectionFactoryOptions.builder()
              ...
              .option(Option.valueOf("client-implementation"), "client-library")
              .build());
```

## Authentication

The driver allows the following options for authentication:

* a `String` property `credentials` containing the local file location of the JSON credentials file.
* a `Credentials` object provided as `google_credentials`. This will only work with programmatically constructed `ConnectionFactoryOptions`.
* a `String` OAuth token provided as `oauthToken`.

If no authentication options are provided, Application Default Credentials will be automatically determined.
The only exception is when the connection is in plain-text, indicating the use of Cloud Spanner emulator, in which case no credentials will be used.

## Supported connection options

All connection options of primitive and String type can be passed through the connection URL in the `?key1=value1&key2=value2` format.
Object-typed options can only be passed in programmatically.

|===
|Property name |Type |Allowed in URL connection |Default |Comments

|`credentials`
|String
|Yes
|null
|The location of the credentials file to use for this connection

|`oauthToken`
|String
|Yes
|null
|A valid pre-existing OAuth token to use for authentication

|`google_credentials`
|com.google.auth.oauth2.OAuth2Credentials
|No
|null
|A pre-authenticated authentication object that can only be supplied with programmatic connection options

|`thread_pool_size`
|int
|Yes
|Equal to the number of available processors
|Determines the size of thread pool used to process `Future` callbacks

|`usePlainText`
|boolean
|Yes
|false
|Turns off SSL and credentials use (only valid when using Cloud Spanner emulator)

|optimizerVersion
|String
|Yes
|null
= ``|``Determines version of Cloud Spanner https://cloud.google.com/spanner/docs/query-optimizer/query-optimizer-versions[optimizer] to use in queries

|===


## Transactions

### Read-Write Transactions
Read-write transactions are supported natively through R2DBC SPI.

```java
Mono.from(connectionFactory.create())
            .flatMapMany(c -> Flux.concat(
                c.beginTransaction(),
                ...
                c.commitTransaction(),
                c.close()))
```

### Read-Only Transactions
Read-only transactions, including stale transactions, can be used by downcasting the `Connection` object to `com.google.cloud.spanner.r2dbc.api.SpannerConnection` and calling `beginReadonlyTransaction()` on it.
Invoking `beginReadonlyTransaction()` without parameters will begin a new strongly consistent readonly transaction.
To customize staleness, pass in a `TimestampBound` parameter.
```java
Mono.from(connectionFactory.create())
            .flatMapMany(c ->
                Flux.concat(
                          ((SpannerConnection) conn).beginReadonlyTransaction(TimestampBound.ofExactStaleness(1, TimeUnit.SECONDS)),
                            ...
                          conn.commitTransaction(),
                    )
```
NOTE: Readonly transactions must be closed by calling `commit()` before starting a new read-write or a read-only transaction.

### Partitioned DML transactions
Partitioned DML transactions are not supported at this time.

### Nesting transactions
Cloud Spanner does not support nested transactions, so each transaction must be either committed or rolled back.
For readonly transactions, either committing or rolling back will result in closing of the readonly transaction.

## Cleaning Up

Client library-based `ConnectionFactory` must be closed as part of application shutdown process to ensure all server-side Cloud Spanner sessions are cleaned up.

```
Mono.from(((Closeable) connectionFactory).close()).subscribe();
```
