languages: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_efeaa5860646_key -iv $encrypted_efeaa5860646_iv -in admin.json.enc -out admin.json -d
  - export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/admin.json
  - export GOOGLE_CLOUD_PROJECT=cloud-spanner-r2dbc-ci

script:
  - mvn clean verify -B -V -q
