= Spring Framework on Google Cloud Parameter Manager Sample Application

This code sample demonstrates how to use the Spring Framework on Google Cloud Parameter Manager integration.
The sample shows how to access Parameter Manager parameters through a `@ConfigurationProperties` class and also through `@Value` annotations on fields.

== Running the Sample

image:http://gstatic.com/cloudssh/images/open-btn.svg[link=https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fspring-cloud-gcp&cloudshell_open_in_editor=spring-cloud-gcp-samples/spring-cloud-gcp-parametermanager-sample/README.adoc]

1. Create a Google Cloud project with https://cloud.google.com/billing/docs/how-to/modify-project#enable-billing[billing enabled], if you don't have one already.

2. Enable the Parameter Manager API from the "APIs & Services" menu of the Google Cloud Console.
This can be done using the gcloud command line tool:
+
[source]
----
gcloud services enable parametermanager.googleapis.com
----

3. Authenticate in one of two ways:

a. Use the Google Cloud SDK to https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login[authenticate with application default credentials].
This method is convenient but should only be used in local development.
b. https://cloud.google.com/iam/docs/creating-managing-service-accounts[Create a new service account], download its private key and point the `spring.cloud.gcp.parametermanager.credentials.location` property to it.
+
Such as: `spring.cloud.gcp.parametermanager.credentials.location=file:/path/to/creds.json`

4. Using the https://console.cloud.google.com/security/parametermanager/parameters[Parameter Manager UI in Cloud Console], create a new parameter named `application-parameter` and set it to any value.
Instructions for using the Parameter Manager UI can be found in the https://cloud.google.com/secret-manager/parameter-manager/docs/create-parameter#gcloud[https://cloud.google.com/parameter-manager/docs/quickstart][Parameter Manager documentation].

5. Run `$ mvn clean install` from the root directory of the project.

6. Run `$ mvn spring-boot:run` command from the same directory as this sample's `pom.xml` file.

7. Go to http://localhost:8080 in your browser or use the `Web Preview` button in Cloud Shell to preview the app on port 8080. Your parameter value is injected into your application through the `WebController` and you will see it displayed.
+
[source]
----
applicationParameter: {"message": "Hello World from GCP PM!!"}
----
+
You will also see some web forms that allow you to create, read, and update parameters in Parameter Manager.
This is done by using the `ParameterManagerTemplate`.
+
Finally, you can view all of your parameters using the https://console.cloud.google.com/security/parametermanager/parameters[Parameter Manager Cloud Console UI], which is the source of truth for all of your parameters in Parameter Manager.

8. Refresh the parameters without restarting the application:

a. After running the application, change your parameters using https://console.cloud.google.com/security/parametermanager/parameters[Parameter Manager UI in Cloud Console]

b. To refresh the parameter, send the following command to your server from which hosting the application:
+
[source]
----
curl -X POST http://localhost:8080/actuator/refresh
----

Note that only `@ConfigurationProperties` annotated with `@RefreshScope` got the updated value.

== What's Next

Now that you've seen how to use Parameter Manager with Spring, you might want to explore more advanced use cases:

1. Use Parameter Manager with Spring Cloud Config Server to centralize your configuration
2. Set up different parameters for different environments (dev, test, prod)
3. Use Parameter Manager for sensitive configuration data in your Spring applications

For more information about Parameter Manager, see the https://cloud.google.com/secret-manager/parameter-manager/docs/overview[Parameter Manager documentation].