/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.texttospeech.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.httpjson.InstantiatingHttpJsonChannelProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.global.GlobalProperties;
import com.google.cloud.texttospeech.v1.TextToSpeechClient;
import com.google.cloud.texttospeech.v1.TextToSpeechSettings;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.threeten.bp.Duration;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link TextToSpeechClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@ConditionalOnClass(TextToSpeechClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.texttospeech.v1.spring.auto.text-to-speech.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties({TextToSpeechSpringProperties.class, GlobalProperties.class})
public class TextToSpeechSpringAutoConfiguration {
  private final TextToSpeechSpringProperties clientProperties;
  private final GlobalProperties globalProperties;
  private static final Log LOGGER = LogFactory.getLog(TextToSpeechSpringAutoConfiguration.class);

  protected TextToSpeechSpringAutoConfiguration(
      TextToSpeechSpringProperties clientProperties, GlobalProperties globalProperties) {
    this.clientProperties = clientProperties;
    this.globalProperties = globalProperties;
  }

  /**
   * Obtains the default credentials provider. The used key will be obtained from Spring Boot
   * configuration data files.
   */
  @Bean
  @ConditionalOnMissingBean
  public CredentialsProvider textToSpeechCredentials() throws IOException {
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from TextToSpeech-specific configuration");
      }
      return ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    }
    if (LOGGER.isTraceEnabled()) {
      LOGGER.trace("Using credentials from global configuration");
    }
    return ((CredentialsProvider) new DefaultCredentialsProvider(this.globalProperties));
  }

  /**
   * Returns the default channel provider. The default is gRPC and will default to it unless the
   * useRest option is provided to use HTTP transport instead
   */
  @Bean
  @ConditionalOnMissingBean
  public TransportChannelProvider defaultTextToSpeechTransportChannelProvider() {
    return TextToSpeechSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a TextToSpeechClient bean configured to use the default credentials provider (obtained
   * with textToSpeechCredentials()) and its default transport channel provider
   * (defaultTextToSpeechTransportChannelProvider()). It also configures the quota project ID if
   * provided. It will configure an executor provider in case there is more than one thread
   * configured in the client
   *
   * <p>Individual retry settings are configured as well. It will use the relevant client library's
   * default retry settings when they are not specified in TextToSpeechSpringProperties.
   */
  @Bean
  @ConditionalOnMissingBean
  public TextToSpeechSettings textToSpeechSettings(
      @Qualifier("textToSpeechCredentials") CredentialsProvider credentialsProvider,
      @Qualifier("defaultTextToSpeechTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    TextToSpeechSettings.Builder clientSettingsBuilder =
        TextToSpeechSettings.newBuilder()
            .setCredentialsProvider(credentialsProvider)
            .setTransportChannelProvider(defaultTransportChannelProvider)
            .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          TextToSpeechSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder.setTransportChannelProvider(
          TextToSpeechSettings.defaultHttpJsonTransportProviderBuilder().build());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using HTTP transport channel");
      }
    }
    RetrySettings.Builder listVoicesRetrySettingBuilder =
        clientSettingsBuilder.listVoicesSettings().getRetrySettings().toBuilder();
    if (this.clientProperties.getListVoicesInitialRetryDelay() != null) {
      listVoicesRetrySettingBuilder.setInitialRetryDelay(
          this.clientProperties.getListVoicesInitialRetryDelay());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListVoicesInitialRetryDelay set to "
                + this.clientProperties.getListVoicesInitialRetryDelay());
      }
    }
    if (this.clientProperties.getListVoicesRetryDelayMultiplier() != null) {
      listVoicesRetrySettingBuilder.setRetryDelayMultiplier(
          this.clientProperties.getListVoicesRetryDelayMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListVoicesRetryDelayMultiplier set to "
                + this.clientProperties.getListVoicesRetryDelayMultiplier());
      }
    }
    if (this.clientProperties.getListVoicesMaxRetryDelay() != null) {
      listVoicesRetrySettingBuilder.setMaxRetryDelay(
          this.clientProperties.getListVoicesMaxRetryDelay());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListVoicesMaxRetryDelay set to " + this.clientProperties.getListVoicesMaxRetryDelay());
      }
    }
    if (this.clientProperties.getListVoicesInitialRpcTimeout() != null) {
      listVoicesRetrySettingBuilder.setInitialRpcTimeout(
          this.clientProperties.getListVoicesInitialRpcTimeout());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListVoicesInitialRpcTimeout set to "
                + this.clientProperties.getListVoicesInitialRpcTimeout());
      }
    }
    if (this.clientProperties.getListVoicesRpcTimeoutMultiplier() != null) {
      listVoicesRetrySettingBuilder.setRpcTimeoutMultiplier(
          this.clientProperties.getListVoicesRpcTimeoutMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListVoicesRpcTimeoutMultiplier set to "
                + this.clientProperties.getListVoicesRpcTimeoutMultiplier());
      }
    }
    if (this.clientProperties.getListVoicesMaxRpcTimeout() != null) {
      listVoicesRetrySettingBuilder.setMaxRpcTimeout(
          this.clientProperties.getListVoicesMaxRpcTimeout());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListVoicesMaxRpcTimeout set to " + this.clientProperties.getListVoicesMaxRpcTimeout());
      }
    }
    if (this.clientProperties.getListVoicesTotalTimeout() != null) {
      listVoicesRetrySettingBuilder.setTotalTimeout(
          this.clientProperties.getListVoicesTotalTimeout());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListVoicesTotalTimeout set to " + this.clientProperties.getListVoicesTotalTimeout());
      }
    }
    clientSettingsBuilder
        .listVoicesSettings()
        .setRetrySettings(listVoicesRetrySettingBuilder.build());
    RetrySettings.Builder synthesizeSpeechRetrySettingBuilder =
        clientSettingsBuilder.synthesizeSpeechSettings().getRetrySettings().toBuilder();
    if (this.clientProperties.getSynthesizeSpeechInitialRetryDelay() != null) {
      synthesizeSpeechRetrySettingBuilder.setInitialRetryDelay(
          this.clientProperties.getSynthesizeSpeechInitialRetryDelay());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "SynthesizeSpeechInitialRetryDelay set to "
                + this.clientProperties.getSynthesizeSpeechInitialRetryDelay());
      }
    }
    if (this.clientProperties.getSynthesizeSpeechRetryDelayMultiplier() != null) {
      synthesizeSpeechRetrySettingBuilder.setRetryDelayMultiplier(
          this.clientProperties.getSynthesizeSpeechRetryDelayMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "SynthesizeSpeechRetryDelayMultiplier set to "
                + this.clientProperties.getSynthesizeSpeechRetryDelayMultiplier());
      }
    }
    if (this.clientProperties.getSynthesizeSpeechMaxRetryDelay() != null) {
      synthesizeSpeechRetrySettingBuilder.setMaxRetryDelay(
          this.clientProperties.getSynthesizeSpeechMaxRetryDelay());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "SynthesizeSpeechMaxRetryDelay set to "
                + this.clientProperties.getSynthesizeSpeechMaxRetryDelay());
      }
    }
    if (this.clientProperties.getSynthesizeSpeechInitialRpcTimeout() != null) {
      synthesizeSpeechRetrySettingBuilder.setInitialRpcTimeout(
          this.clientProperties.getSynthesizeSpeechInitialRpcTimeout());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "SynthesizeSpeechInitialRpcTimeout set to "
                + this.clientProperties.getSynthesizeSpeechInitialRpcTimeout());
      }
    }
    if (this.clientProperties.getSynthesizeSpeechRpcTimeoutMultiplier() != null) {
      synthesizeSpeechRetrySettingBuilder.setRpcTimeoutMultiplier(
          this.clientProperties.getSynthesizeSpeechRpcTimeoutMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "SynthesizeSpeechRpcTimeoutMultiplier set to "
                + this.clientProperties.getSynthesizeSpeechRpcTimeoutMultiplier());
      }
    }
    if (this.clientProperties.getSynthesizeSpeechMaxRpcTimeout() != null) {
      synthesizeSpeechRetrySettingBuilder.setMaxRpcTimeout(
          this.clientProperties.getSynthesizeSpeechMaxRpcTimeout());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "SynthesizeSpeechMaxRpcTimeout set to "
                + this.clientProperties.getSynthesizeSpeechMaxRpcTimeout());
      }
    }
    if (this.clientProperties.getSynthesizeSpeechTotalTimeout() != null) {
      synthesizeSpeechRetrySettingBuilder.setTotalTimeout(
          this.clientProperties.getSynthesizeSpeechTotalTimeout());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "SynthesizeSpeechTotalTimeout set to "
                + this.clientProperties.getSynthesizeSpeechTotalTimeout());
      }
    }
    clientSettingsBuilder
        .synthesizeSpeechSettings()
        .setRetrySettings(synthesizeSpeechRetrySettingBuilder.build());
    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public TextToSpeechClient textToSpeechClient(TextToSpeechSettings textToSpeechSettings)
      throws IOException {
    return TextToSpeechClient.create(textToSpeechSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-text-to-speech";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
