/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.osconfig.v1.spring;

import com.google.api.core.BetaApi;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.CredentialsSupplier;
import javax.annotation.Generated;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;
import org.threeten.bp.Duration;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/** Provides default property values for OsConfigService client bean */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@ConfigurationProperties("com.google.cloud.osconfig.v1.spring.auto.os-config-service")
public class OsConfigServiceSpringProperties implements CredentialsSupplier {
  @NestedConfigurationProperty
  private final Credentials credentials =
      new Credentials("https://www.googleapis.com/auth/cloud-platform");

  private String quotaProjectId;
  private Integer executorThreadCount;
  private boolean useRest = false;
  private Duration executePatchJobInitialRetryDelay;
  private Double executePatchJobRetryDelayMultiplier;
  private Duration executePatchJobMaxRetryDelay;
  private Duration executePatchJobInitialRpcTimeout;
  private Double executePatchJobRpcTimeoutMultiplier;
  private Duration executePatchJobMaxRpcTimeout;
  private Duration executePatchJobTotalTimeout;
  private Duration getPatchJobInitialRetryDelay;
  private Double getPatchJobRetryDelayMultiplier;
  private Duration getPatchJobMaxRetryDelay;
  private Duration getPatchJobInitialRpcTimeout;
  private Double getPatchJobRpcTimeoutMultiplier;
  private Duration getPatchJobMaxRpcTimeout;
  private Duration getPatchJobTotalTimeout;
  private Duration cancelPatchJobInitialRetryDelay;
  private Double cancelPatchJobRetryDelayMultiplier;
  private Duration cancelPatchJobMaxRetryDelay;
  private Duration cancelPatchJobInitialRpcTimeout;
  private Double cancelPatchJobRpcTimeoutMultiplier;
  private Duration cancelPatchJobMaxRpcTimeout;
  private Duration cancelPatchJobTotalTimeout;
  private Duration listPatchJobsInitialRetryDelay;
  private Double listPatchJobsRetryDelayMultiplier;
  private Duration listPatchJobsMaxRetryDelay;
  private Duration listPatchJobsInitialRpcTimeout;
  private Double listPatchJobsRpcTimeoutMultiplier;
  private Duration listPatchJobsMaxRpcTimeout;
  private Duration listPatchJobsTotalTimeout;
  private Duration listPatchJobInstanceDetailsInitialRetryDelay;
  private Double listPatchJobInstanceDetailsRetryDelayMultiplier;
  private Duration listPatchJobInstanceDetailsMaxRetryDelay;
  private Duration listPatchJobInstanceDetailsInitialRpcTimeout;
  private Double listPatchJobInstanceDetailsRpcTimeoutMultiplier;
  private Duration listPatchJobInstanceDetailsMaxRpcTimeout;
  private Duration listPatchJobInstanceDetailsTotalTimeout;
  private Duration createPatchDeploymentInitialRetryDelay;
  private Double createPatchDeploymentRetryDelayMultiplier;
  private Duration createPatchDeploymentMaxRetryDelay;
  private Duration createPatchDeploymentInitialRpcTimeout;
  private Double createPatchDeploymentRpcTimeoutMultiplier;
  private Duration createPatchDeploymentMaxRpcTimeout;
  private Duration createPatchDeploymentTotalTimeout;
  private Duration getPatchDeploymentInitialRetryDelay;
  private Double getPatchDeploymentRetryDelayMultiplier;
  private Duration getPatchDeploymentMaxRetryDelay;
  private Duration getPatchDeploymentInitialRpcTimeout;
  private Double getPatchDeploymentRpcTimeoutMultiplier;
  private Duration getPatchDeploymentMaxRpcTimeout;
  private Duration getPatchDeploymentTotalTimeout;
  private Duration listPatchDeploymentsInitialRetryDelay;
  private Double listPatchDeploymentsRetryDelayMultiplier;
  private Duration listPatchDeploymentsMaxRetryDelay;
  private Duration listPatchDeploymentsInitialRpcTimeout;
  private Double listPatchDeploymentsRpcTimeoutMultiplier;
  private Duration listPatchDeploymentsMaxRpcTimeout;
  private Duration listPatchDeploymentsTotalTimeout;
  private Duration deletePatchDeploymentInitialRetryDelay;
  private Double deletePatchDeploymentRetryDelayMultiplier;
  private Duration deletePatchDeploymentMaxRetryDelay;
  private Duration deletePatchDeploymentInitialRpcTimeout;
  private Double deletePatchDeploymentRpcTimeoutMultiplier;
  private Duration deletePatchDeploymentMaxRpcTimeout;
  private Duration deletePatchDeploymentTotalTimeout;
  private Duration updatePatchDeploymentInitialRetryDelay;
  private Double updatePatchDeploymentRetryDelayMultiplier;
  private Duration updatePatchDeploymentMaxRetryDelay;
  private Duration updatePatchDeploymentInitialRpcTimeout;
  private Double updatePatchDeploymentRpcTimeoutMultiplier;
  private Duration updatePatchDeploymentMaxRpcTimeout;
  private Duration updatePatchDeploymentTotalTimeout;
  private Duration pausePatchDeploymentInitialRetryDelay;
  private Double pausePatchDeploymentRetryDelayMultiplier;
  private Duration pausePatchDeploymentMaxRetryDelay;
  private Duration pausePatchDeploymentInitialRpcTimeout;
  private Double pausePatchDeploymentRpcTimeoutMultiplier;
  private Duration pausePatchDeploymentMaxRpcTimeout;
  private Duration pausePatchDeploymentTotalTimeout;
  private Duration resumePatchDeploymentInitialRetryDelay;
  private Double resumePatchDeploymentRetryDelayMultiplier;
  private Duration resumePatchDeploymentMaxRetryDelay;
  private Duration resumePatchDeploymentInitialRpcTimeout;
  private Double resumePatchDeploymentRpcTimeoutMultiplier;
  private Duration resumePatchDeploymentMaxRpcTimeout;
  private Duration resumePatchDeploymentTotalTimeout;

  @Override
  public Credentials getCredentials() {
    return this.credentials;
  }

  public String getQuotaProjectId() {
    return this.quotaProjectId;
  }

  public void setQuotaProjectId(String quotaProjectId) {
    this.quotaProjectId = quotaProjectId;
  }

  public boolean getUseRest() {
    return this.useRest;
  }

  public void setUseRest(boolean useRest) {
    this.useRest = useRest;
  }

  public Integer getExecutorThreadCount() {
    return this.executorThreadCount;
  }

  public void setExecutorThreadCount(Integer executorThreadCount) {
    this.executorThreadCount = executorThreadCount;
  }

  public Duration getExecutePatchJobInitialRetryDelay() {
    return this.executePatchJobInitialRetryDelay;
  }

  public void setExecutePatchJobInitialRetryDelay(
      java.time.Duration executePatchJobInitialRetryDelay) {
    this.executePatchJobInitialRetryDelay =
        Duration.parse(executePatchJobInitialRetryDelay.toString());
  }

  public Double getExecutePatchJobRetryDelayMultiplier() {
    return this.executePatchJobRetryDelayMultiplier;
  }

  public void setExecutePatchJobRetryDelayMultiplier(Double executePatchJobRetryDelayMultiplier) {
    this.executePatchJobRetryDelayMultiplier = executePatchJobRetryDelayMultiplier;
  }

  public Duration getExecutePatchJobMaxRetryDelay() {
    return this.executePatchJobMaxRetryDelay;
  }

  public void setExecutePatchJobMaxRetryDelay(java.time.Duration executePatchJobMaxRetryDelay) {
    this.executePatchJobMaxRetryDelay = Duration.parse(executePatchJobMaxRetryDelay.toString());
  }

  public Duration getExecutePatchJobInitialRpcTimeout() {
    return this.executePatchJobInitialRpcTimeout;
  }

  public void setExecutePatchJobInitialRpcTimeout(
      java.time.Duration executePatchJobInitialRpcTimeout) {
    this.executePatchJobInitialRpcTimeout =
        Duration.parse(executePatchJobInitialRpcTimeout.toString());
  }

  public Double getExecutePatchJobRpcTimeoutMultiplier() {
    return this.executePatchJobRpcTimeoutMultiplier;
  }

  public void setExecutePatchJobRpcTimeoutMultiplier(Double executePatchJobRpcTimeoutMultiplier) {
    this.executePatchJobRpcTimeoutMultiplier = executePatchJobRpcTimeoutMultiplier;
  }

  public Duration getExecutePatchJobMaxRpcTimeout() {
    return this.executePatchJobMaxRpcTimeout;
  }

  public void setExecutePatchJobMaxRpcTimeout(java.time.Duration executePatchJobMaxRpcTimeout) {
    this.executePatchJobMaxRpcTimeout = Duration.parse(executePatchJobMaxRpcTimeout.toString());
  }

  public Duration getExecutePatchJobTotalTimeout() {
    return this.executePatchJobTotalTimeout;
  }

  public void setExecutePatchJobTotalTimeout(java.time.Duration executePatchJobTotalTimeout) {
    this.executePatchJobTotalTimeout = Duration.parse(executePatchJobTotalTimeout.toString());
  }

  public Duration getGetPatchJobInitialRetryDelay() {
    return this.getPatchJobInitialRetryDelay;
  }

  public void setGetPatchJobInitialRetryDelay(java.time.Duration getPatchJobInitialRetryDelay) {
    this.getPatchJobInitialRetryDelay = Duration.parse(getPatchJobInitialRetryDelay.toString());
  }

  public Double getGetPatchJobRetryDelayMultiplier() {
    return this.getPatchJobRetryDelayMultiplier;
  }

  public void setGetPatchJobRetryDelayMultiplier(Double getPatchJobRetryDelayMultiplier) {
    this.getPatchJobRetryDelayMultiplier = getPatchJobRetryDelayMultiplier;
  }

  public Duration getGetPatchJobMaxRetryDelay() {
    return this.getPatchJobMaxRetryDelay;
  }

  public void setGetPatchJobMaxRetryDelay(java.time.Duration getPatchJobMaxRetryDelay) {
    this.getPatchJobMaxRetryDelay = Duration.parse(getPatchJobMaxRetryDelay.toString());
  }

  public Duration getGetPatchJobInitialRpcTimeout() {
    return this.getPatchJobInitialRpcTimeout;
  }

  public void setGetPatchJobInitialRpcTimeout(java.time.Duration getPatchJobInitialRpcTimeout) {
    this.getPatchJobInitialRpcTimeout = Duration.parse(getPatchJobInitialRpcTimeout.toString());
  }

  public Double getGetPatchJobRpcTimeoutMultiplier() {
    return this.getPatchJobRpcTimeoutMultiplier;
  }

  public void setGetPatchJobRpcTimeoutMultiplier(Double getPatchJobRpcTimeoutMultiplier) {
    this.getPatchJobRpcTimeoutMultiplier = getPatchJobRpcTimeoutMultiplier;
  }

  public Duration getGetPatchJobMaxRpcTimeout() {
    return this.getPatchJobMaxRpcTimeout;
  }

  public void setGetPatchJobMaxRpcTimeout(java.time.Duration getPatchJobMaxRpcTimeout) {
    this.getPatchJobMaxRpcTimeout = Duration.parse(getPatchJobMaxRpcTimeout.toString());
  }

  public Duration getGetPatchJobTotalTimeout() {
    return this.getPatchJobTotalTimeout;
  }

  public void setGetPatchJobTotalTimeout(java.time.Duration getPatchJobTotalTimeout) {
    this.getPatchJobTotalTimeout = Duration.parse(getPatchJobTotalTimeout.toString());
  }

  public Duration getCancelPatchJobInitialRetryDelay() {
    return this.cancelPatchJobInitialRetryDelay;
  }

  public void setCancelPatchJobInitialRetryDelay(
      java.time.Duration cancelPatchJobInitialRetryDelay) {
    this.cancelPatchJobInitialRetryDelay =
        Duration.parse(cancelPatchJobInitialRetryDelay.toString());
  }

  public Double getCancelPatchJobRetryDelayMultiplier() {
    return this.cancelPatchJobRetryDelayMultiplier;
  }

  public void setCancelPatchJobRetryDelayMultiplier(Double cancelPatchJobRetryDelayMultiplier) {
    this.cancelPatchJobRetryDelayMultiplier = cancelPatchJobRetryDelayMultiplier;
  }

  public Duration getCancelPatchJobMaxRetryDelay() {
    return this.cancelPatchJobMaxRetryDelay;
  }

  public void setCancelPatchJobMaxRetryDelay(java.time.Duration cancelPatchJobMaxRetryDelay) {
    this.cancelPatchJobMaxRetryDelay = Duration.parse(cancelPatchJobMaxRetryDelay.toString());
  }

  public Duration getCancelPatchJobInitialRpcTimeout() {
    return this.cancelPatchJobInitialRpcTimeout;
  }

  public void setCancelPatchJobInitialRpcTimeout(
      java.time.Duration cancelPatchJobInitialRpcTimeout) {
    this.cancelPatchJobInitialRpcTimeout =
        Duration.parse(cancelPatchJobInitialRpcTimeout.toString());
  }

  public Double getCancelPatchJobRpcTimeoutMultiplier() {
    return this.cancelPatchJobRpcTimeoutMultiplier;
  }

  public void setCancelPatchJobRpcTimeoutMultiplier(Double cancelPatchJobRpcTimeoutMultiplier) {
    this.cancelPatchJobRpcTimeoutMultiplier = cancelPatchJobRpcTimeoutMultiplier;
  }

  public Duration getCancelPatchJobMaxRpcTimeout() {
    return this.cancelPatchJobMaxRpcTimeout;
  }

  public void setCancelPatchJobMaxRpcTimeout(java.time.Duration cancelPatchJobMaxRpcTimeout) {
    this.cancelPatchJobMaxRpcTimeout = Duration.parse(cancelPatchJobMaxRpcTimeout.toString());
  }

  public Duration getCancelPatchJobTotalTimeout() {
    return this.cancelPatchJobTotalTimeout;
  }

  public void setCancelPatchJobTotalTimeout(java.time.Duration cancelPatchJobTotalTimeout) {
    this.cancelPatchJobTotalTimeout = Duration.parse(cancelPatchJobTotalTimeout.toString());
  }

  public Duration getListPatchJobsInitialRetryDelay() {
    return this.listPatchJobsInitialRetryDelay;
  }

  public void setListPatchJobsInitialRetryDelay(java.time.Duration listPatchJobsInitialRetryDelay) {
    this.listPatchJobsInitialRetryDelay = Duration.parse(listPatchJobsInitialRetryDelay.toString());
  }

  public Double getListPatchJobsRetryDelayMultiplier() {
    return this.listPatchJobsRetryDelayMultiplier;
  }

  public void setListPatchJobsRetryDelayMultiplier(Double listPatchJobsRetryDelayMultiplier) {
    this.listPatchJobsRetryDelayMultiplier = listPatchJobsRetryDelayMultiplier;
  }

  public Duration getListPatchJobsMaxRetryDelay() {
    return this.listPatchJobsMaxRetryDelay;
  }

  public void setListPatchJobsMaxRetryDelay(java.time.Duration listPatchJobsMaxRetryDelay) {
    this.listPatchJobsMaxRetryDelay = Duration.parse(listPatchJobsMaxRetryDelay.toString());
  }

  public Duration getListPatchJobsInitialRpcTimeout() {
    return this.listPatchJobsInitialRpcTimeout;
  }

  public void setListPatchJobsInitialRpcTimeout(java.time.Duration listPatchJobsInitialRpcTimeout) {
    this.listPatchJobsInitialRpcTimeout = Duration.parse(listPatchJobsInitialRpcTimeout.toString());
  }

  public Double getListPatchJobsRpcTimeoutMultiplier() {
    return this.listPatchJobsRpcTimeoutMultiplier;
  }

  public void setListPatchJobsRpcTimeoutMultiplier(Double listPatchJobsRpcTimeoutMultiplier) {
    this.listPatchJobsRpcTimeoutMultiplier = listPatchJobsRpcTimeoutMultiplier;
  }

  public Duration getListPatchJobsMaxRpcTimeout() {
    return this.listPatchJobsMaxRpcTimeout;
  }

  public void setListPatchJobsMaxRpcTimeout(java.time.Duration listPatchJobsMaxRpcTimeout) {
    this.listPatchJobsMaxRpcTimeout = Duration.parse(listPatchJobsMaxRpcTimeout.toString());
  }

  public Duration getListPatchJobsTotalTimeout() {
    return this.listPatchJobsTotalTimeout;
  }

  public void setListPatchJobsTotalTimeout(java.time.Duration listPatchJobsTotalTimeout) {
    this.listPatchJobsTotalTimeout = Duration.parse(listPatchJobsTotalTimeout.toString());
  }

  public Duration getListPatchJobInstanceDetailsInitialRetryDelay() {
    return this.listPatchJobInstanceDetailsInitialRetryDelay;
  }

  public void setListPatchJobInstanceDetailsInitialRetryDelay(
      java.time.Duration listPatchJobInstanceDetailsInitialRetryDelay) {
    this.listPatchJobInstanceDetailsInitialRetryDelay =
        Duration.parse(listPatchJobInstanceDetailsInitialRetryDelay.toString());
  }

  public Double getListPatchJobInstanceDetailsRetryDelayMultiplier() {
    return this.listPatchJobInstanceDetailsRetryDelayMultiplier;
  }

  public void setListPatchJobInstanceDetailsRetryDelayMultiplier(
      Double listPatchJobInstanceDetailsRetryDelayMultiplier) {
    this.listPatchJobInstanceDetailsRetryDelayMultiplier =
        listPatchJobInstanceDetailsRetryDelayMultiplier;
  }

  public Duration getListPatchJobInstanceDetailsMaxRetryDelay() {
    return this.listPatchJobInstanceDetailsMaxRetryDelay;
  }

  public void setListPatchJobInstanceDetailsMaxRetryDelay(
      java.time.Duration listPatchJobInstanceDetailsMaxRetryDelay) {
    this.listPatchJobInstanceDetailsMaxRetryDelay =
        Duration.parse(listPatchJobInstanceDetailsMaxRetryDelay.toString());
  }

  public Duration getListPatchJobInstanceDetailsInitialRpcTimeout() {
    return this.listPatchJobInstanceDetailsInitialRpcTimeout;
  }

  public void setListPatchJobInstanceDetailsInitialRpcTimeout(
      java.time.Duration listPatchJobInstanceDetailsInitialRpcTimeout) {
    this.listPatchJobInstanceDetailsInitialRpcTimeout =
        Duration.parse(listPatchJobInstanceDetailsInitialRpcTimeout.toString());
  }

  public Double getListPatchJobInstanceDetailsRpcTimeoutMultiplier() {
    return this.listPatchJobInstanceDetailsRpcTimeoutMultiplier;
  }

  public void setListPatchJobInstanceDetailsRpcTimeoutMultiplier(
      Double listPatchJobInstanceDetailsRpcTimeoutMultiplier) {
    this.listPatchJobInstanceDetailsRpcTimeoutMultiplier =
        listPatchJobInstanceDetailsRpcTimeoutMultiplier;
  }

  public Duration getListPatchJobInstanceDetailsMaxRpcTimeout() {
    return this.listPatchJobInstanceDetailsMaxRpcTimeout;
  }

  public void setListPatchJobInstanceDetailsMaxRpcTimeout(
      java.time.Duration listPatchJobInstanceDetailsMaxRpcTimeout) {
    this.listPatchJobInstanceDetailsMaxRpcTimeout =
        Duration.parse(listPatchJobInstanceDetailsMaxRpcTimeout.toString());
  }

  public Duration getListPatchJobInstanceDetailsTotalTimeout() {
    return this.listPatchJobInstanceDetailsTotalTimeout;
  }

  public void setListPatchJobInstanceDetailsTotalTimeout(
      java.time.Duration listPatchJobInstanceDetailsTotalTimeout) {
    this.listPatchJobInstanceDetailsTotalTimeout =
        Duration.parse(listPatchJobInstanceDetailsTotalTimeout.toString());
  }

  public Duration getCreatePatchDeploymentInitialRetryDelay() {
    return this.createPatchDeploymentInitialRetryDelay;
  }

  public void setCreatePatchDeploymentInitialRetryDelay(
      java.time.Duration createPatchDeploymentInitialRetryDelay) {
    this.createPatchDeploymentInitialRetryDelay =
        Duration.parse(createPatchDeploymentInitialRetryDelay.toString());
  }

  public Double getCreatePatchDeploymentRetryDelayMultiplier() {
    return this.createPatchDeploymentRetryDelayMultiplier;
  }

  public void setCreatePatchDeploymentRetryDelayMultiplier(
      Double createPatchDeploymentRetryDelayMultiplier) {
    this.createPatchDeploymentRetryDelayMultiplier = createPatchDeploymentRetryDelayMultiplier;
  }

  public Duration getCreatePatchDeploymentMaxRetryDelay() {
    return this.createPatchDeploymentMaxRetryDelay;
  }

  public void setCreatePatchDeploymentMaxRetryDelay(
      java.time.Duration createPatchDeploymentMaxRetryDelay) {
    this.createPatchDeploymentMaxRetryDelay =
        Duration.parse(createPatchDeploymentMaxRetryDelay.toString());
  }

  public Duration getCreatePatchDeploymentInitialRpcTimeout() {
    return this.createPatchDeploymentInitialRpcTimeout;
  }

  public void setCreatePatchDeploymentInitialRpcTimeout(
      java.time.Duration createPatchDeploymentInitialRpcTimeout) {
    this.createPatchDeploymentInitialRpcTimeout =
        Duration.parse(createPatchDeploymentInitialRpcTimeout.toString());
  }

  public Double getCreatePatchDeploymentRpcTimeoutMultiplier() {
    return this.createPatchDeploymentRpcTimeoutMultiplier;
  }

  public void setCreatePatchDeploymentRpcTimeoutMultiplier(
      Double createPatchDeploymentRpcTimeoutMultiplier) {
    this.createPatchDeploymentRpcTimeoutMultiplier = createPatchDeploymentRpcTimeoutMultiplier;
  }

  public Duration getCreatePatchDeploymentMaxRpcTimeout() {
    return this.createPatchDeploymentMaxRpcTimeout;
  }

  public void setCreatePatchDeploymentMaxRpcTimeout(
      java.time.Duration createPatchDeploymentMaxRpcTimeout) {
    this.createPatchDeploymentMaxRpcTimeout =
        Duration.parse(createPatchDeploymentMaxRpcTimeout.toString());
  }

  public Duration getCreatePatchDeploymentTotalTimeout() {
    return this.createPatchDeploymentTotalTimeout;
  }

  public void setCreatePatchDeploymentTotalTimeout(
      java.time.Duration createPatchDeploymentTotalTimeout) {
    this.createPatchDeploymentTotalTimeout =
        Duration.parse(createPatchDeploymentTotalTimeout.toString());
  }

  public Duration getGetPatchDeploymentInitialRetryDelay() {
    return this.getPatchDeploymentInitialRetryDelay;
  }

  public void setGetPatchDeploymentInitialRetryDelay(
      java.time.Duration getPatchDeploymentInitialRetryDelay) {
    this.getPatchDeploymentInitialRetryDelay =
        Duration.parse(getPatchDeploymentInitialRetryDelay.toString());
  }

  public Double getGetPatchDeploymentRetryDelayMultiplier() {
    return this.getPatchDeploymentRetryDelayMultiplier;
  }

  public void setGetPatchDeploymentRetryDelayMultiplier(
      Double getPatchDeploymentRetryDelayMultiplier) {
    this.getPatchDeploymentRetryDelayMultiplier = getPatchDeploymentRetryDelayMultiplier;
  }

  public Duration getGetPatchDeploymentMaxRetryDelay() {
    return this.getPatchDeploymentMaxRetryDelay;
  }

  public void setGetPatchDeploymentMaxRetryDelay(
      java.time.Duration getPatchDeploymentMaxRetryDelay) {
    this.getPatchDeploymentMaxRetryDelay =
        Duration.parse(getPatchDeploymentMaxRetryDelay.toString());
  }

  public Duration getGetPatchDeploymentInitialRpcTimeout() {
    return this.getPatchDeploymentInitialRpcTimeout;
  }

  public void setGetPatchDeploymentInitialRpcTimeout(
      java.time.Duration getPatchDeploymentInitialRpcTimeout) {
    this.getPatchDeploymentInitialRpcTimeout =
        Duration.parse(getPatchDeploymentInitialRpcTimeout.toString());
  }

  public Double getGetPatchDeploymentRpcTimeoutMultiplier() {
    return this.getPatchDeploymentRpcTimeoutMultiplier;
  }

  public void setGetPatchDeploymentRpcTimeoutMultiplier(
      Double getPatchDeploymentRpcTimeoutMultiplier) {
    this.getPatchDeploymentRpcTimeoutMultiplier = getPatchDeploymentRpcTimeoutMultiplier;
  }

  public Duration getGetPatchDeploymentMaxRpcTimeout() {
    return this.getPatchDeploymentMaxRpcTimeout;
  }

  public void setGetPatchDeploymentMaxRpcTimeout(
      java.time.Duration getPatchDeploymentMaxRpcTimeout) {
    this.getPatchDeploymentMaxRpcTimeout =
        Duration.parse(getPatchDeploymentMaxRpcTimeout.toString());
  }

  public Duration getGetPatchDeploymentTotalTimeout() {
    return this.getPatchDeploymentTotalTimeout;
  }

  public void setGetPatchDeploymentTotalTimeout(java.time.Duration getPatchDeploymentTotalTimeout) {
    this.getPatchDeploymentTotalTimeout = Duration.parse(getPatchDeploymentTotalTimeout.toString());
  }

  public Duration getListPatchDeploymentsInitialRetryDelay() {
    return this.listPatchDeploymentsInitialRetryDelay;
  }

  public void setListPatchDeploymentsInitialRetryDelay(
      java.time.Duration listPatchDeploymentsInitialRetryDelay) {
    this.listPatchDeploymentsInitialRetryDelay =
        Duration.parse(listPatchDeploymentsInitialRetryDelay.toString());
  }

  public Double getListPatchDeploymentsRetryDelayMultiplier() {
    return this.listPatchDeploymentsRetryDelayMultiplier;
  }

  public void setListPatchDeploymentsRetryDelayMultiplier(
      Double listPatchDeploymentsRetryDelayMultiplier) {
    this.listPatchDeploymentsRetryDelayMultiplier = listPatchDeploymentsRetryDelayMultiplier;
  }

  public Duration getListPatchDeploymentsMaxRetryDelay() {
    return this.listPatchDeploymentsMaxRetryDelay;
  }

  public void setListPatchDeploymentsMaxRetryDelay(
      java.time.Duration listPatchDeploymentsMaxRetryDelay) {
    this.listPatchDeploymentsMaxRetryDelay =
        Duration.parse(listPatchDeploymentsMaxRetryDelay.toString());
  }

  public Duration getListPatchDeploymentsInitialRpcTimeout() {
    return this.listPatchDeploymentsInitialRpcTimeout;
  }

  public void setListPatchDeploymentsInitialRpcTimeout(
      java.time.Duration listPatchDeploymentsInitialRpcTimeout) {
    this.listPatchDeploymentsInitialRpcTimeout =
        Duration.parse(listPatchDeploymentsInitialRpcTimeout.toString());
  }

  public Double getListPatchDeploymentsRpcTimeoutMultiplier() {
    return this.listPatchDeploymentsRpcTimeoutMultiplier;
  }

  public void setListPatchDeploymentsRpcTimeoutMultiplier(
      Double listPatchDeploymentsRpcTimeoutMultiplier) {
    this.listPatchDeploymentsRpcTimeoutMultiplier = listPatchDeploymentsRpcTimeoutMultiplier;
  }

  public Duration getListPatchDeploymentsMaxRpcTimeout() {
    return this.listPatchDeploymentsMaxRpcTimeout;
  }

  public void setListPatchDeploymentsMaxRpcTimeout(
      java.time.Duration listPatchDeploymentsMaxRpcTimeout) {
    this.listPatchDeploymentsMaxRpcTimeout =
        Duration.parse(listPatchDeploymentsMaxRpcTimeout.toString());
  }

  public Duration getListPatchDeploymentsTotalTimeout() {
    return this.listPatchDeploymentsTotalTimeout;
  }

  public void setListPatchDeploymentsTotalTimeout(
      java.time.Duration listPatchDeploymentsTotalTimeout) {
    this.listPatchDeploymentsTotalTimeout =
        Duration.parse(listPatchDeploymentsTotalTimeout.toString());
  }

  public Duration getDeletePatchDeploymentInitialRetryDelay() {
    return this.deletePatchDeploymentInitialRetryDelay;
  }

  public void setDeletePatchDeploymentInitialRetryDelay(
      java.time.Duration deletePatchDeploymentInitialRetryDelay) {
    this.deletePatchDeploymentInitialRetryDelay =
        Duration.parse(deletePatchDeploymentInitialRetryDelay.toString());
  }

  public Double getDeletePatchDeploymentRetryDelayMultiplier() {
    return this.deletePatchDeploymentRetryDelayMultiplier;
  }

  public void setDeletePatchDeploymentRetryDelayMultiplier(
      Double deletePatchDeploymentRetryDelayMultiplier) {
    this.deletePatchDeploymentRetryDelayMultiplier = deletePatchDeploymentRetryDelayMultiplier;
  }

  public Duration getDeletePatchDeploymentMaxRetryDelay() {
    return this.deletePatchDeploymentMaxRetryDelay;
  }

  public void setDeletePatchDeploymentMaxRetryDelay(
      java.time.Duration deletePatchDeploymentMaxRetryDelay) {
    this.deletePatchDeploymentMaxRetryDelay =
        Duration.parse(deletePatchDeploymentMaxRetryDelay.toString());
  }

  public Duration getDeletePatchDeploymentInitialRpcTimeout() {
    return this.deletePatchDeploymentInitialRpcTimeout;
  }

  public void setDeletePatchDeploymentInitialRpcTimeout(
      java.time.Duration deletePatchDeploymentInitialRpcTimeout) {
    this.deletePatchDeploymentInitialRpcTimeout =
        Duration.parse(deletePatchDeploymentInitialRpcTimeout.toString());
  }

  public Double getDeletePatchDeploymentRpcTimeoutMultiplier() {
    return this.deletePatchDeploymentRpcTimeoutMultiplier;
  }

  public void setDeletePatchDeploymentRpcTimeoutMultiplier(
      Double deletePatchDeploymentRpcTimeoutMultiplier) {
    this.deletePatchDeploymentRpcTimeoutMultiplier = deletePatchDeploymentRpcTimeoutMultiplier;
  }

  public Duration getDeletePatchDeploymentMaxRpcTimeout() {
    return this.deletePatchDeploymentMaxRpcTimeout;
  }

  public void setDeletePatchDeploymentMaxRpcTimeout(
      java.time.Duration deletePatchDeploymentMaxRpcTimeout) {
    this.deletePatchDeploymentMaxRpcTimeout =
        Duration.parse(deletePatchDeploymentMaxRpcTimeout.toString());
  }

  public Duration getDeletePatchDeploymentTotalTimeout() {
    return this.deletePatchDeploymentTotalTimeout;
  }

  public void setDeletePatchDeploymentTotalTimeout(
      java.time.Duration deletePatchDeploymentTotalTimeout) {
    this.deletePatchDeploymentTotalTimeout =
        Duration.parse(deletePatchDeploymentTotalTimeout.toString());
  }

  public Duration getUpdatePatchDeploymentInitialRetryDelay() {
    return this.updatePatchDeploymentInitialRetryDelay;
  }

  public void setUpdatePatchDeploymentInitialRetryDelay(
      java.time.Duration updatePatchDeploymentInitialRetryDelay) {
    this.updatePatchDeploymentInitialRetryDelay =
        Duration.parse(updatePatchDeploymentInitialRetryDelay.toString());
  }

  public Double getUpdatePatchDeploymentRetryDelayMultiplier() {
    return this.updatePatchDeploymentRetryDelayMultiplier;
  }

  public void setUpdatePatchDeploymentRetryDelayMultiplier(
      Double updatePatchDeploymentRetryDelayMultiplier) {
    this.updatePatchDeploymentRetryDelayMultiplier = updatePatchDeploymentRetryDelayMultiplier;
  }

  public Duration getUpdatePatchDeploymentMaxRetryDelay() {
    return this.updatePatchDeploymentMaxRetryDelay;
  }

  public void setUpdatePatchDeploymentMaxRetryDelay(
      java.time.Duration updatePatchDeploymentMaxRetryDelay) {
    this.updatePatchDeploymentMaxRetryDelay =
        Duration.parse(updatePatchDeploymentMaxRetryDelay.toString());
  }

  public Duration getUpdatePatchDeploymentInitialRpcTimeout() {
    return this.updatePatchDeploymentInitialRpcTimeout;
  }

  public void setUpdatePatchDeploymentInitialRpcTimeout(
      java.time.Duration updatePatchDeploymentInitialRpcTimeout) {
    this.updatePatchDeploymentInitialRpcTimeout =
        Duration.parse(updatePatchDeploymentInitialRpcTimeout.toString());
  }

  public Double getUpdatePatchDeploymentRpcTimeoutMultiplier() {
    return this.updatePatchDeploymentRpcTimeoutMultiplier;
  }

  public void setUpdatePatchDeploymentRpcTimeoutMultiplier(
      Double updatePatchDeploymentRpcTimeoutMultiplier) {
    this.updatePatchDeploymentRpcTimeoutMultiplier = updatePatchDeploymentRpcTimeoutMultiplier;
  }

  public Duration getUpdatePatchDeploymentMaxRpcTimeout() {
    return this.updatePatchDeploymentMaxRpcTimeout;
  }

  public void setUpdatePatchDeploymentMaxRpcTimeout(
      java.time.Duration updatePatchDeploymentMaxRpcTimeout) {
    this.updatePatchDeploymentMaxRpcTimeout =
        Duration.parse(updatePatchDeploymentMaxRpcTimeout.toString());
  }

  public Duration getUpdatePatchDeploymentTotalTimeout() {
    return this.updatePatchDeploymentTotalTimeout;
  }

  public void setUpdatePatchDeploymentTotalTimeout(
      java.time.Duration updatePatchDeploymentTotalTimeout) {
    this.updatePatchDeploymentTotalTimeout =
        Duration.parse(updatePatchDeploymentTotalTimeout.toString());
  }

  public Duration getPausePatchDeploymentInitialRetryDelay() {
    return this.pausePatchDeploymentInitialRetryDelay;
  }

  public void setPausePatchDeploymentInitialRetryDelay(
      java.time.Duration pausePatchDeploymentInitialRetryDelay) {
    this.pausePatchDeploymentInitialRetryDelay =
        Duration.parse(pausePatchDeploymentInitialRetryDelay.toString());
  }

  public Double getPausePatchDeploymentRetryDelayMultiplier() {
    return this.pausePatchDeploymentRetryDelayMultiplier;
  }

  public void setPausePatchDeploymentRetryDelayMultiplier(
      Double pausePatchDeploymentRetryDelayMultiplier) {
    this.pausePatchDeploymentRetryDelayMultiplier = pausePatchDeploymentRetryDelayMultiplier;
  }

  public Duration getPausePatchDeploymentMaxRetryDelay() {
    return this.pausePatchDeploymentMaxRetryDelay;
  }

  public void setPausePatchDeploymentMaxRetryDelay(
      java.time.Duration pausePatchDeploymentMaxRetryDelay) {
    this.pausePatchDeploymentMaxRetryDelay =
        Duration.parse(pausePatchDeploymentMaxRetryDelay.toString());
  }

  public Duration getPausePatchDeploymentInitialRpcTimeout() {
    return this.pausePatchDeploymentInitialRpcTimeout;
  }

  public void setPausePatchDeploymentInitialRpcTimeout(
      java.time.Duration pausePatchDeploymentInitialRpcTimeout) {
    this.pausePatchDeploymentInitialRpcTimeout =
        Duration.parse(pausePatchDeploymentInitialRpcTimeout.toString());
  }

  public Double getPausePatchDeploymentRpcTimeoutMultiplier() {
    return this.pausePatchDeploymentRpcTimeoutMultiplier;
  }

  public void setPausePatchDeploymentRpcTimeoutMultiplier(
      Double pausePatchDeploymentRpcTimeoutMultiplier) {
    this.pausePatchDeploymentRpcTimeoutMultiplier = pausePatchDeploymentRpcTimeoutMultiplier;
  }

  public Duration getPausePatchDeploymentMaxRpcTimeout() {
    return this.pausePatchDeploymentMaxRpcTimeout;
  }

  public void setPausePatchDeploymentMaxRpcTimeout(
      java.time.Duration pausePatchDeploymentMaxRpcTimeout) {
    this.pausePatchDeploymentMaxRpcTimeout =
        Duration.parse(pausePatchDeploymentMaxRpcTimeout.toString());
  }

  public Duration getPausePatchDeploymentTotalTimeout() {
    return this.pausePatchDeploymentTotalTimeout;
  }

  public void setPausePatchDeploymentTotalTimeout(
      java.time.Duration pausePatchDeploymentTotalTimeout) {
    this.pausePatchDeploymentTotalTimeout =
        Duration.parse(pausePatchDeploymentTotalTimeout.toString());
  }

  public Duration getResumePatchDeploymentInitialRetryDelay() {
    return this.resumePatchDeploymentInitialRetryDelay;
  }

  public void setResumePatchDeploymentInitialRetryDelay(
      java.time.Duration resumePatchDeploymentInitialRetryDelay) {
    this.resumePatchDeploymentInitialRetryDelay =
        Duration.parse(resumePatchDeploymentInitialRetryDelay.toString());
  }

  public Double getResumePatchDeploymentRetryDelayMultiplier() {
    return this.resumePatchDeploymentRetryDelayMultiplier;
  }

  public void setResumePatchDeploymentRetryDelayMultiplier(
      Double resumePatchDeploymentRetryDelayMultiplier) {
    this.resumePatchDeploymentRetryDelayMultiplier = resumePatchDeploymentRetryDelayMultiplier;
  }

  public Duration getResumePatchDeploymentMaxRetryDelay() {
    return this.resumePatchDeploymentMaxRetryDelay;
  }

  public void setResumePatchDeploymentMaxRetryDelay(
      java.time.Duration resumePatchDeploymentMaxRetryDelay) {
    this.resumePatchDeploymentMaxRetryDelay =
        Duration.parse(resumePatchDeploymentMaxRetryDelay.toString());
  }

  public Duration getResumePatchDeploymentInitialRpcTimeout() {
    return this.resumePatchDeploymentInitialRpcTimeout;
  }

  public void setResumePatchDeploymentInitialRpcTimeout(
      java.time.Duration resumePatchDeploymentInitialRpcTimeout) {
    this.resumePatchDeploymentInitialRpcTimeout =
        Duration.parse(resumePatchDeploymentInitialRpcTimeout.toString());
  }

  public Double getResumePatchDeploymentRpcTimeoutMultiplier() {
    return this.resumePatchDeploymentRpcTimeoutMultiplier;
  }

  public void setResumePatchDeploymentRpcTimeoutMultiplier(
      Double resumePatchDeploymentRpcTimeoutMultiplier) {
    this.resumePatchDeploymentRpcTimeoutMultiplier = resumePatchDeploymentRpcTimeoutMultiplier;
  }

  public Duration getResumePatchDeploymentMaxRpcTimeout() {
    return this.resumePatchDeploymentMaxRpcTimeout;
  }

  public void setResumePatchDeploymentMaxRpcTimeout(
      java.time.Duration resumePatchDeploymentMaxRpcTimeout) {
    this.resumePatchDeploymentMaxRpcTimeout =
        Duration.parse(resumePatchDeploymentMaxRpcTimeout.toString());
  }

  public Duration getResumePatchDeploymentTotalTimeout() {
    return this.resumePatchDeploymentTotalTimeout;
  }

  public void setResumePatchDeploymentTotalTimeout(
      java.time.Duration resumePatchDeploymentTotalTimeout) {
    this.resumePatchDeploymentTotalTimeout =
        Duration.parse(resumePatchDeploymentTotalTimeout.toString());
  }
}
