/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.memorystore.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.memorystore.v1.MemorystoreClient;
import com.google.cloud.memorystore.v1.MemorystoreSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link MemorystoreClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(MemorystoreClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.memorystore.v1.memorystore.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(MemorystoreSpringProperties.class)
public class MemorystoreSpringAutoConfiguration {
  private final MemorystoreSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(MemorystoreSpringAutoConfiguration.class);

  protected MemorystoreSpringAutoConfiguration(
      MemorystoreSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from Memorystore-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultMemorystoreTransportChannelProvider")
  public TransportChannelProvider defaultMemorystoreTransportChannelProvider() {
    return MemorystoreSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a MemorystoreSettings bean configured to use a DefaultCredentialsProvider and the
   * client library's default transport channel provider
   * (defaultMemorystoreTransportChannelProvider()). It also configures the quota project ID and
   * executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in MemorystoreSpringProperties. Method-level properties will take precedence over service-level
   * properties if available, and client library defaults will be used if neither are specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link MemorystoreSettings} bean configured with {@link TransportChannelProvider}
   *     bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public MemorystoreSettings memorystoreSettings(
      @Qualifier("defaultMemorystoreTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    MemorystoreSettings.Builder clientSettingsBuilder = MemorystoreSettings.newBuilder();
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setEndpoint(MemorystoreSettings.getDefaultEndpoint())
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          MemorystoreSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listInstancesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listInstancesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listInstancesSettings().setRetrySettings(listInstancesRetrySettings);

      RetrySettings getInstanceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getInstanceSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getInstanceSettings().setRetrySettings(getInstanceRetrySettings);

      RetrySettings getCertificateAuthorityRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getCertificateAuthoritySettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getCertificateAuthoritySettings()
          .setRetrySettings(getCertificateAuthorityRetrySettings);

      RetrySettings listBackupCollectionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBackupCollectionsSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listBackupCollectionsSettings()
          .setRetrySettings(listBackupCollectionsRetrySettings);

      RetrySettings getBackupCollectionRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getBackupCollectionSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getBackupCollectionSettings()
          .setRetrySettings(getBackupCollectionRetrySettings);

      RetrySettings listBackupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBackupsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listBackupsSettings().setRetrySettings(listBackupsRetrySettings);

      RetrySettings getBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getBackupSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getBackupSettings().setRetrySettings(getBackupRetrySettings);

      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);

      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listInstancesRetry = clientProperties.getListInstancesRetry();
    if (listInstancesRetry != null) {
      RetrySettings listInstancesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listInstancesSettings().getRetrySettings(), listInstancesRetry);
      clientSettingsBuilder.listInstancesSettings().setRetrySettings(listInstancesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listInstances from properties.");
      }
    }
    Retry getInstanceRetry = clientProperties.getGetInstanceRetry();
    if (getInstanceRetry != null) {
      RetrySettings getInstanceRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getInstanceSettings().getRetrySettings(), getInstanceRetry);
      clientSettingsBuilder.getInstanceSettings().setRetrySettings(getInstanceRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getInstance from properties.");
      }
    }
    Retry getCertificateAuthorityRetry = clientProperties.getGetCertificateAuthorityRetry();
    if (getCertificateAuthorityRetry != null) {
      RetrySettings getCertificateAuthorityRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getCertificateAuthoritySettings().getRetrySettings(),
              getCertificateAuthorityRetry);
      clientSettingsBuilder
          .getCertificateAuthoritySettings()
          .setRetrySettings(getCertificateAuthorityRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getCertificateAuthority from properties.");
      }
    }
    Retry listBackupCollectionsRetry = clientProperties.getListBackupCollectionsRetry();
    if (listBackupCollectionsRetry != null) {
      RetrySettings listBackupCollectionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBackupCollectionsSettings().getRetrySettings(),
              listBackupCollectionsRetry);
      clientSettingsBuilder
          .listBackupCollectionsSettings()
          .setRetrySettings(listBackupCollectionsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listBackupCollections from properties.");
      }
    }
    Retry getBackupCollectionRetry = clientProperties.getGetBackupCollectionRetry();
    if (getBackupCollectionRetry != null) {
      RetrySettings getBackupCollectionRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getBackupCollectionSettings().getRetrySettings(),
              getBackupCollectionRetry);
      clientSettingsBuilder
          .getBackupCollectionSettings()
          .setRetrySettings(getBackupCollectionRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getBackupCollection from properties.");
      }
    }
    Retry listBackupsRetry = clientProperties.getListBackupsRetry();
    if (listBackupsRetry != null) {
      RetrySettings listBackupsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listBackupsSettings().getRetrySettings(), listBackupsRetry);
      clientSettingsBuilder.listBackupsSettings().setRetrySettings(listBackupsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listBackups from properties.");
      }
    }
    Retry getBackupRetry = clientProperties.getGetBackupRetry();
    if (getBackupRetry != null) {
      RetrySettings getBackupRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getBackupSettings().getRetrySettings(), getBackupRetry);
      clientSettingsBuilder.getBackupSettings().setRetrySettings(getBackupRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getBackup from properties.");
      }
    }
    Retry listLocationsRetry = clientProperties.getListLocationsRetry();
    if (listLocationsRetry != null) {
      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), listLocationsRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listLocations from properties.");
      }
    }
    Retry getLocationRetry = clientProperties.getGetLocationRetry();
    if (getLocationRetry != null) {
      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), getLocationRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getLocation from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a MemorystoreClient bean configured with MemorystoreSettings.
   *
   * @param memorystoreSettings settings to configure an instance of client bean.
   * @return a {@link MemorystoreClient} bean configured with {@link MemorystoreSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public MemorystoreClient memorystoreClient(MemorystoreSettings memorystoreSettings)
      throws IOException {
    return MemorystoreClient.create(memorystoreSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-memorystore";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
