== Getting Started

This section describes how to get up to speed with Spring Framework on Google Cloud libraries.

=== Compatibility with Spring Project Versions

Spring Framework on Google Cloud has dependency and transitive dependencies on Spring Projects. The table below outlines the versions of Spring Cloud, Spring Boot and Spring Framework versions that are compatible with certain Spring Framework on Google Cloud version.
|===
| Spring Framework on Google Cloud | Spring Cloud | Spring Boot | Spring Framework | Supported

|5.x | https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes[2023.0.x] (Leyton) |https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes[3.2.x]| https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x#whats-new-in-version-61[6.1.x]| Yes
|4.x | https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2022.0-Release-Notes[2022.0.x] (Kilburn) |https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes[3.0.x], https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.1-Release-Notes[3.1.x]| https://github.com/spring-projects/spring-framework/wiki/What%27s-New-in-Spring-Framework-6.x#whats-new-in-version-60[6.x]| Yes
|3.x | https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2021.0-Release-Notes[2021.0.x] (Jubilee) |2.6.x, 2.7.x | 5.3.x| Yes
|2.x | https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes[2020.0.x] (Ilford) |2.4.x, 2.5.x|5.3.x| No
|===



=== Setting up Dependencies

All Spring Framework on Google Cloud artifacts are made available through Maven Central.
The following resources are provided to help you setup the libraries for your project:

- Maven Bill of Materials for dependency management
- Starter Dependencies for depending on Spring Framework on Google Cloud modules

You may also consult our https://github.com/GoogleCloudPlatform/spring-cloud-gcp[Github project] to examine the code or build directly from source.

[#bill-of-materials]
==== Bill of Materials

The Spring Framework on Google Cloud Bill of Materials (BOM) contains the versions of all the dependencies it uses.

If you’re a Maven user, adding the following to your pom.xml file will allow you omit any Spring Framework on Google Cloud dependency version numbers from your configuration.
Instead, the version of the BOM you’re using determines the versions of the used dependencies.

[source,xml,subs="normal"]
----
<dependencyManagement>
   <dependencies>
       <dependency>
           <groupId>com.google.cloud</groupId>
           <artifactId>spring-cloud-gcp-dependencies</artifactId>
           <version>{project-version}</version>
           <type>pom</type>
           <scope>import</scope>
       </dependency>
   </dependencies>
</dependencyManagement>
----

Or, if you're a Gradle user:

[source,subs="normal"]
----
dependencies {
    implementation platform("com.google.cloud:spring-cloud-gcp-dependencies:{project-version}")
}
----

In the following sections, it will be assumed you are using the Spring Framework on Google Cloud BOM and the dependency snippets will not contain versions.

==== Starter Dependencies

Spring Framework on Google Cloud offers https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-starters[starter dependencies] through Maven to easily depend on different modules of the library.
Each starter contains all the dependencies and transitive dependencies needed to begin using their corresponding Spring Framework on Google Cloud module.

For example, if you wish to write a Spring application with Cloud Pub/Sub, you would include the `spring-cloud-gcp-starter-pubsub` dependency in your project.
You do *not* need to include the underlying `spring-cloud-gcp-pubsub` dependency, because the `starter` dependency includes it.

A summary of these artifacts are provided below.

Aside from these modules, we also provide additional starters with auto-configurations to various Google Client Libraries.
Refer for the full list https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-previews/README.md[here].

|===
| Spring Framework on Google Cloud Starter | Description | Maven Artifact Name

| Core
| Automatically configure authentication and Google project settings
| <<core.adoc#spring-cloud-gcp-core, com.google.cloud:spring-cloud-gcp-starter>>

| Cloud Spanner
| Provides integrations with Google Cloud Spanner
| <<spanner.adoc#spring-data-cloud-spanner, com.google.cloud:spring-cloud-gcp-starter-data-spanner>>

| Cloud Datastore
| Provides integrations with Google Cloud Datastore
| <<datastore.adoc#spring-data-cloud-datastore, com.google.cloud:spring-cloud-gcp-starter-data-datastore>>

| Cloud Pub/Sub
| Provides integrations with Google Cloud Pub/Sub
| <<pubsub.adoc#cloud-pubsub, com.google.cloud:spring-cloud-gcp-starter-pubsub>>

| Logging
| Enables Cloud Logging
| <<logging.adoc#cloud-logging, com.google.cloud:spring-cloud-gcp-starter-logging>>

| SQL - MySQL
| Cloud SQL integrations with MySQL
| <<sql.adoc#cloud-sql, com.google.cloud:spring-cloud-gcp-starter-sql-mysql>>

| SQL - PostgreSQL
| Cloud SQL integrations with PostgreSQL
| <<sql.adoc#cloud-sql, com.google.cloud:spring-cloud-gcp-starter-sql-postgresql>>

| Storage
| Provides integrations with Google Cloud Storage and Spring Resource
| <<storage.adoc#cloud-storage, com.google.cloud:spring-cloud-gcp-starter-storage>>

| Config
| Enables usage of Google Runtime Configuration API as a Spring Cloud Config server
| <<config.adoc#cloud-runtime-configuration-api, com.google.cloud:spring-cloud-gcp-starter-config>>

| Trace
| Enables instrumentation with Google Cloud Trace
| <<trace.adoc#cloud-trace, com.google.cloud:spring-cloud-gcp-starter-trace>>

| Vision
| Provides integrations with Google Cloud Vision
| <<vision.adoc#cloud-vision, com.google.cloud:spring-cloud-gcp-starter-vision>>

| Security - IAP
| Provides a security layer over applications deployed to Google Cloud
| <<security-iap.adoc#cloud-iap, com.google.cloud:spring-cloud-gcp-starter-security-iap>>

| Security - Firebase
| Provides a security layer over applications deployed to Firebase
| <<security-firebase.adoc#security-firebase, com.google.cloud:spring-cloud-gcp-starter-security-firebase>>

|===

==== Spring Initializr

https://start.spring.io/[Spring Initializr] is a tool which generates the scaffolding code for a new Spring Boot project.
It handles the work of generating the Maven or Gradle build file so you do not have to manually add the dependencies yourself.

Spring Initializr offers three modules from Spring Framework on Google Cloud that you can use to generate your project.

- *GCP Support*: The GCP Support module contains auto-configuration support for every Spring Framework on Google Cloud integration.
Most of the autoconfiguration code is only enabled if the required dependency is added to your project.
- *GCP Messaging*: Google Cloud Pub/Sub integrations work out of the box.
- *GCP Storage*: Google Cloud Storage integrations work out of the box.

=== Learning Spring Framework on Google Cloud

There are a variety of resources to help you learn how to use Spring Framework on Google Cloud libraries.

==== Sample Applications

The easiest way to learn how to use Spring Framework on Google Cloud is to consult the https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples[sample applications on Github].
Spring Framework on Google Cloud provides sample applications which demonstrate how to use every integration in the library.
The table below highlights several samples of the most commonly used integrations in Spring Framework on Google Cloud.

|===
| Google Cloud Integration | Sample Application

| Cloud Pub/Sub
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample[spring-cloud-gcp-pubsub-sample]

| Cloud Spanner
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-repository-sample[spring-cloud-gcp-data-spanner-repository-sample]

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-spanner-template-sample[spring-cloud-gcp-data-spanner-template-sample]

| Datastore
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample[spring-cloud-gcp-data-datastore-sample]

| Cloud SQL (w/ MySQL)
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample[spring-cloud-gcp-sql-mysql-sample]

| Cloud Storage
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample[spring-cloud-gcp-storage-resource-sample]

| Cloud Logging
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample[spring-cloud-gcp-logging-sample]

| Trace
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample[spring-cloud-gcp-trace-sample]

| Cloud Vision
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-vision-api-sample[spring-cloud-gcp-vision-api-sample]

| Cloud Security - IAP
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-security-iap-sample[spring-cloud-gcp-security-iap-sample]

| Cloud Security - Firebase
| https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-security-firebase-sample[spring-cloud-gcp-security-firebase-sample]
|===

Each sample application demonstrates how to use Spring Framework on Google Cloud libraries in context and how to setup the dependencies for the project.
The applications are fully functional and can be deployed to Google Cloud as well.
If you are interested, you may consult guides for https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html[deploying an application to AppEngine] and https://codelabs.developers.google.com/codelabs/cloud-springboot-kubernetes/index.html[to Google Kubernetes Engine].

==== Codelabs

For a more hands-on approach, there are several guides and codelabs to help you get up to speed.
These guides provide step-by-step instructions for building an application using Spring Framework on Google Cloud.

Some examples include:

- https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html[Deploy a Spring Boot app to App Engine]
- https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-kotlin/index.html[Build a Kotlin Spring Boot app with Cloud SQL and Cloud Pub/Sub]
- https://codelabs.developers.google.com/codelabs/cloud-spring-datastore/index.html[Build a Spring Boot application with Datastore]
- https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-pubsub-integration/index.html[Messaging with Spring Integration and Cloud Pub/Sub]

The full collection of Spring codelabs can be found on the https://codelabs.developers.google.com/spring[Google Developer Codelabs page].
