== Migration Guide from Spring Cloud GCP 5.x to 6.x
=== Before you start
==== Upgrade to the 5.x version
This doc assumes you are running with Spring Cloud GCP 5.x.

If you are currently running with an earlier major version of Spring Cloud GCP, i.e., 1.x or 2.x, we recommend that you upgrade to [Spring Cloud GCP 5.x] before migrating to Spring Cloud GCP 6.x.

* link:migration-guide-1.x.adoc[Migration guide from Spring Cloud GCP 1.x to 2.x]
* link:migration-guide-3.x.adoc[Migration guide from Spring Cloud GCP 3.x to 4.x]

Note that since Spring Cloud GCP 5.0 has few breaking changes, we have only provided release notes
as reference.

==== Review System requirements
Spring Cloud GCP 6.0 is built on Spring Boot 3.4.x and Spring Framework 6.2.x, which requires Java 17 at minimum.
If you are currently on Java 8 or Java 11, you need to upgrade your JDK before you can develop an application based on Spring Cloud GCP 6.0.

=== Upgrade to Spring Cloud GCP 6.0
==== Update Bill of Materials (BOM)
If you’re a Maven user, add our BOM to your pom.xml `<dependencyManagement>` section.
This will allow you to not specify versions for any of the Maven dependencies and instead delegate versioning to the BOM.

[source, xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-dependencies</artifactId>
            <version>6.0.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

===== Review Dependencies
Run `mvn dependency:tree` (`gradlew dependencies` for Gradle projects) to see the dependency tree of your project.
Ensure Spring-related dependencies have matching versions:

* Spring Boot 3.4.x
* Spring Cloud 2024.x
** For detailed dependency versions, see "2024.0 (Moorgate)" column in link:https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions#supported-releases[Spring Cloud: Supported Versions] table.

==== Secret Manager
Introduced support for the `${sm@secret_id}` syntax. This new syntax is encouraged over the (still
supported) `${sm://secret_id}` syntax. Users still relying on the `sm://` syntax will be issued a
warning.

For example:
[source, java]
@Value("${sm@my_secret}")
String mySecret;
---

==== Datastore
Introduced support for `ValueExpressionDelegate`. This class is suggested over
`QueryMethodEvaluationContextProvider`.

==== Spanner
Introduced support for `ValueExpressionDelegate`. This class is suggested over
`QueryMethodEvaluationContextProvider`.


