== Parameter Manager

https://cloud.google.com/secret-manager/parameter-manager/docs/overview[Google Cloud Parameter Manager] is a service that allows you to store and manage configuration parameters for your applications and workload deployments. It provides a centralized way to manage application settings across environments.


Spring Framework on Google Cloud provides:

* A config data resource which allows you to specify and load parameters from your Google Cloud project into your application context using https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4[Spring Boot's Config Data API].
* A `ParameterManagerTemplate` which allows you to read, write, and update parameters in Parameter Manager.

=== Dependency Setup

To begin using this library, add the `spring-cloud-gcp-starter-parametermanager` artifact to your project.

Maven coordinates, using <<getting-started.adoc#bill-of-materials, Spring Framework on Google Cloud BOM>>:

[source,xml]
----
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>spring-cloud-gcp-starter-parametermanager</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
  implementation("com.google.cloud:spring-cloud-gcp-starter-parametermanager")
}
----

==== Configuration

By default, Spring Framework on Google Cloud Parameter Manager will authenticate using Application Default Credentials.
This can be overridden using the authentication properties.

|===
| Name | Description | Required | Default value
| `spring.cloud.gcp.parametermanager.enabled` | Enables the Parameter Manager integration. | No | `true`
| `spring.cloud.gcp.parametermanager.credentials.location` | OAuth2 credentials for authenticating to the Google Cloud Parameter Manager API. | No | By default, infers credentials from https://cloud.google.com/docs/authentication/production[Application Default Credentials].
| `spring.cloud.gcp.parametermanager.credentials.encoded-key` | Base64-encoded contents of OAuth2 account private key for authenticating to the Google Cloud Parameter Manager API. | No | By default, infers credentials from https://cloud.google.com/docs/authentication/production[Application Default Credentials].
| `spring.cloud.gcp.parametermanager.project-id` | The default Google Cloud project used to access Parameter Manager API for the template and property source. | No | Default to the one in the <<spring-cloud-gcp-core,Spring Framework on Google Cloud Core Module>>.
|`spring.cloud.gcp.parametermanager.allow-default-parameter`| Define the behavior when accessing a non-existent parameter. +
If set to `true`, `null` will be returned when accessing a non-existent parameter; otherwise throwing an exception. | No | `false`
|===

=== Parameter Manager Config Data Resource

The Spring Framework on Google Cloud integration for Google Cloud Parameter Manager enables you to use Parameter Manager as an external config data resource.
This allows you to specify and load parameters from Google Cloud Parameter Manager as properties into the application context using https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4[Spring Boot's Config Data API].

The Parameter Manager config data resource uses the following syntax to specify parameters:

[source]
----
# 1. Long form - specify the project ID, location ID, parameter ID, and version ID
pm@projects/<project-id>/locations/<location-id>/parameters/<parameter-id>/versions/<version-id>

# 2. Long form - specify location ID, parameter ID, and version ID, use default GCP project
#
# The project is inferred from the spring.cloud.gcp.parametermanager.project-id setting
# in your application.properties (see Configuration) or from application-default credentials
# if this is not set.
pm@locations/<location-id>/parameters/<parameter-id>/versions/<version-id>

# 3. Short form - specify project ID, location ID, parameter ID, and version ID
pm@<project-id>/<location-id>/<parameter-id>/<version-id>

# 4. Shortest form - specify locationID, parameter ID and version ID, use default GCP project
pm@<location-id>/<parameter-id>/<version-id>
----

You can use this syntax in the following places:

1. In your `application.properties` file:
+
[source]
----
# Example of the project-parameter long-form syntax.
spring.config.import=pm@
spring.datasource=${pm@projects/my-gcp-project/locations/global/parameters/my-parameter/versions/v1}
----
The former is used to enable https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4[Spring Boot's Config Data API].

2. Access the value using the `@Value` annotation.
+
[source]
----
// Example of using shortest form syntax.
@Value("${pm@global/my-parameter/latest}")
----

=== Parameter Manager Template

The `ParameterManagerTemplate` class simplifies operations of creating, reading, and updating parameters.

To begin using this class, you may inject an instance of the class using `@Autowired` after adding the starter dependency to your project.

[source, java]
----
@Autowired
private ParameterManagerTemplate parameterManagerTemplate;
----

Please consult the https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-parametermanager/src/main/java/com/google/cloud/spring/parametermanager/ParameterManagerOperations.java[`ParameterManagerOperations`] interface for information on what operations are available for the Parameter Manager template.

=== Refresh parameters without restarting the application

1. Before running your application, change the project's configuration files as follows:
+
import the actuator starter dependency to your project,
+
[source]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
----
add the following properties to your project's `application.properties`.
+
[source]
----
management.endpoints.web.exposure.include=refresh
----

2. Annotate your configuration properties classes with `@RefreshScope`:
+
[source, java]
----
@Configuration
@RefreshScope
@ConfigurationProperties("myapp")
public class MyAppProperties {
    private String myParameter;
    
    // getters and setters
}
----

3. After running the application, update your version stored in the Parameter Manager. You need to delete and create the version with the same name.

4. When you need to refresh a parameter, send the following command to your application sever:
+
[source]
----
curl -X POST http://[host]:[port]/actuator/refresh
----
Note that only `@ConfigurationProperties` annotated with `@RefreshScope` will get the updated values.

=== Allow default parameter

By default, when accessing a non-existent parameter, the Parameter Manager will throw an exception.

However, if your want to use a default value in such a scenario, you can add the following property to project's properties.
[source]
----
`spring.cloud.gcp.parametermanager.allow-default-parameter=true`
----

Therefore, a variable annotated with `@Value("${${pm@global/fake-parameter/v1}:DEFAULT}")` will be resolved as `DEFAULT` when there is no `fake-parameter` parameter or `v1` version for `fake-parameter` in Parameter Manager.

=== Sample Application

A https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-parametermanager-sample[Parameter Manager Sample Application] is provided which demonstrates basic property source loading and usage of the template class.