/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.dataplex.v1.spring;

import com.google.api.core.BetaApi;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.CredentialsSupplier;
import com.google.cloud.spring.core.Retry;
import javax.annotation.Generated;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.NestedConfigurationProperty;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/** Provides default property values for DataTaxonomyService client bean */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@ConfigurationProperties("com.google.cloud.dataplex.v1.data-taxonomy-service")
public class DataTaxonomyServiceSpringProperties implements CredentialsSupplier {
  /** OAuth2 credentials to authenticate and authorize calls to Google Cloud Client Libraries. */
  @NestedConfigurationProperty
  private final Credentials credentials =
      new Credentials("https://www.googleapis.com/auth/cloud-platform");
  /** Quota project to use for billing. */
  private String quotaProjectId;
  /** Number of threads used for executors. */
  private Integer executorThreadCount;
  /** Allow override of default transport channel provider to use REST instead of gRPC. */
  private boolean useRest = false;
  /** Allow override of retry settings at service level, applying to all of its RPC methods. */
  @NestedConfigurationProperty private Retry retry;
  /**
   * Allow override of retry settings at method-level for listDataTaxonomies. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listDataTaxonomiesRetry;
  /**
   * Allow override of retry settings at method-level for getDataTaxonomy. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getDataTaxonomyRetry;
  /**
   * Allow override of retry settings at method-level for listDataAttributeBindings. If defined,
   * this takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listDataAttributeBindingsRetry;
  /**
   * Allow override of retry settings at method-level for getDataAttributeBinding. If defined, this
   * takes precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getDataAttributeBindingRetry;
  /**
   * Allow override of retry settings at method-level for listDataAttributes. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listDataAttributesRetry;
  /**
   * Allow override of retry settings at method-level for getDataAttribute. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getDataAttributeRetry;
  /**
   * Allow override of retry settings at method-level for listLocations. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry listLocationsRetry;
  /**
   * Allow override of retry settings at method-level for getLocation. If defined, this takes
   * precedence over service-level retry configurations for that RPC method.
   */
  @NestedConfigurationProperty private Retry getLocationRetry;

  @Override
  public Credentials getCredentials() {
    return this.credentials;
  }

  public String getQuotaProjectId() {
    return this.quotaProjectId;
  }

  public void setQuotaProjectId(String quotaProjectId) {
    this.quotaProjectId = quotaProjectId;
  }

  public boolean getUseRest() {
    return this.useRest;
  }

  public void setUseRest(boolean useRest) {
    this.useRest = useRest;
  }

  public Integer getExecutorThreadCount() {
    return this.executorThreadCount;
  }

  public void setExecutorThreadCount(Integer executorThreadCount) {
    this.executorThreadCount = executorThreadCount;
  }

  public Retry getRetry() {
    return this.retry;
  }

  public void setRetry(Retry retry) {
    this.retry = retry;
  }

  public Retry getListDataTaxonomiesRetry() {
    return this.listDataTaxonomiesRetry;
  }

  public void setListDataTaxonomiesRetry(Retry listDataTaxonomiesRetry) {
    this.listDataTaxonomiesRetry = listDataTaxonomiesRetry;
  }

  public Retry getGetDataTaxonomyRetry() {
    return this.getDataTaxonomyRetry;
  }

  public void setGetDataTaxonomyRetry(Retry getDataTaxonomyRetry) {
    this.getDataTaxonomyRetry = getDataTaxonomyRetry;
  }

  public Retry getListDataAttributeBindingsRetry() {
    return this.listDataAttributeBindingsRetry;
  }

  public void setListDataAttributeBindingsRetry(Retry listDataAttributeBindingsRetry) {
    this.listDataAttributeBindingsRetry = listDataAttributeBindingsRetry;
  }

  public Retry getGetDataAttributeBindingRetry() {
    return this.getDataAttributeBindingRetry;
  }

  public void setGetDataAttributeBindingRetry(Retry getDataAttributeBindingRetry) {
    this.getDataAttributeBindingRetry = getDataAttributeBindingRetry;
  }

  public Retry getListDataAttributesRetry() {
    return this.listDataAttributesRetry;
  }

  public void setListDataAttributesRetry(Retry listDataAttributesRetry) {
    this.listDataAttributesRetry = listDataAttributesRetry;
  }

  public Retry getGetDataAttributeRetry() {
    return this.getDataAttributeRetry;
  }

  public void setGetDataAttributeRetry(Retry getDataAttributeRetry) {
    this.getDataAttributeRetry = getDataAttributeRetry;
  }

  public Retry getListLocationsRetry() {
    return this.listLocationsRetry;
  }

  public void setListLocationsRetry(Retry listLocationsRetry) {
    this.listLocationsRetry = listLocationsRetry;
  }

  public Retry getGetLocationRetry() {
    return this.getLocationRetry;
  }

  public void setGetLocationRetry(Retry getLocationRetry) {
    this.getLocationRetry = getLocationRetry;
  }
}
