= Spring Framework on Google Cloud Cloud Datastore Bookshelf Example

This code sample demonstrates how to read and write POJOs from Google Cloud Datastore using the SpringData Cloud Datastore module link:../../spring-cloud-gcp-starters/spring-cloud-gcp-starter-data-datastore[Spring Framework on Google Cloud Cloud Datastore Starter].

== Running the example

image:http://gstatic.com/cloudssh/images/open-btn.svg[link=https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fspring-cloud-gcp&cloudshell_open_in_editor=spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-basic-sample/README.adoc]

. Create a new Cloud Datastore database in your Google Cloud project if this has not already been done to allow Cloud Datastore to create and store entities.

. https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login[If you are authenticated in the Cloud SDK], your credentials will be automatically found by the Spring Boot Starter for Google Cloud Datastore.
+
Alternatively, https://console.cloud.google.com/iam-admin/serviceaccounts[create a service account from the Google Cloud Console] and download its private key.
+
Then, uncomment the `spring.cloud.gcp.datastore.credentials.location` property in the link:src/main/resources/application.properties[application.properties] file and fill its value with the path to your service account private key on your local file system, prepended with `file:`.

. Run `$ mvn clean install` from the root directory of the project.

. In the same directory as this sample's `pom.xml`, execute the following command to run the
`DatastoreBookshelfExample` Spring Boot console app:
+
`$ mvn spring-boot:run`

. Use the following commands to create 4 books
+
----
curl --location --request POST 'localhost:8080/saveBook' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "The Moon Is a Harsh Mistress",
    "author": "Robert A. Heinlein",
    "year": 1966
}'

curl --location --request POST 'localhost:8080/saveBook' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Stranger in a Strange Land",
    "author": "Robert A. Heinlein",
    "year": 1961
}'

curl --location --request POST 'localhost:8080/saveBook' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "The Crack in Space",
    "author": "Philip K. Dick",
    "year": 1966
}'

curl --location --request POST 'localhost:8080/saveBook' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Ubik",
    "author": "Philip K. Dick",
    "year": 1969
}'
----

. Use the following command to query all books
+
----
curl --location --request GET 'localhost:8080/findAllBooks'
----

. Use the following command to find books by author
+
----
curl --location --request GET 'localhost:8080/findByAuthor?author=Robert A. Heinlein'
----

. Use the following command to query books newer than a given publication year
+
----
curl --location --request GET 'localhost:8080/findByYearGreaterThan?year=1960'
----

. Use the following command to query books with a given author and publication year
+
----
curl --location --request GET 'localhost:8080/findByAuthorYear?author=Robert A. Heinlein&year=1966'
----

. Use the following command to delete all books
+
----
curl --location --request DELETE 'localhost:8080/removeAllBooks'
----
