/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.appengine.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.appengine.v1.AuthorizedCertificatesClient;
import com.google.appengine.v1.AuthorizedCertificatesSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link AuthorizedCertificatesClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(AuthorizedCertificatesClient.class)
@ConditionalOnProperty(
    value = "com.google.appengine.v1.authorized-certificates.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(AuthorizedCertificatesSpringProperties.class)
public class AuthorizedCertificatesSpringAutoConfiguration {
  private final AuthorizedCertificatesSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER =
      LogFactory.getLog(AuthorizedCertificatesSpringAutoConfiguration.class);

  protected AuthorizedCertificatesSpringAutoConfiguration(
      AuthorizedCertificatesSpringProperties clientProperties,
      CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from AuthorizedCertificates-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultAuthorizedCertificatesTransportChannelProvider")
  public TransportChannelProvider defaultAuthorizedCertificatesTransportChannelProvider() {
    if (this.clientProperties.getUseRest()) {
      return AuthorizedCertificatesSettings.defaultHttpJsonTransportProviderBuilder().build();
    }
    return AuthorizedCertificatesSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a AuthorizedCertificatesSettings bean configured to use a DefaultCredentialsProvider
   * and the client library's default transport channel provider
   * (defaultAuthorizedCertificatesTransportChannelProvider()). It also configures the quota project
   * ID and executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in AuthorizedCertificatesSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link AuthorizedCertificatesSettings} bean configured with {@link
   *     TransportChannelProvider} bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public AuthorizedCertificatesSettings authorizedCertificatesSettings(
      @Qualifier("defaultAuthorizedCertificatesTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    AuthorizedCertificatesSettings.Builder clientSettingsBuilder;
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder = AuthorizedCertificatesSettings.newHttpJsonBuilder();
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using REST (HTTP/JSON) transport.");
      }
    } else {
      clientSettingsBuilder = AuthorizedCertificatesSettings.newBuilder();
    }
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          AuthorizedCertificatesSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listAuthorizedCertificatesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listAuthorizedCertificatesSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .listAuthorizedCertificatesSettings()
          .setRetrySettings(listAuthorizedCertificatesRetrySettings);

      RetrySettings getAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAuthorizedCertificateSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .getAuthorizedCertificateSettings()
          .setRetrySettings(getAuthorizedCertificateRetrySettings);

      RetrySettings createAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createAuthorizedCertificateSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .createAuthorizedCertificateSettings()
          .setRetrySettings(createAuthorizedCertificateRetrySettings);

      RetrySettings updateAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateAuthorizedCertificateSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .updateAuthorizedCertificateSettings()
          .setRetrySettings(updateAuthorizedCertificateRetrySettings);

      RetrySettings deleteAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteAuthorizedCertificateSettings().getRetrySettings(),
              serviceRetry);
      clientSettingsBuilder
          .deleteAuthorizedCertificateSettings()
          .setRetrySettings(deleteAuthorizedCertificateRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listAuthorizedCertificatesRetry = clientProperties.getListAuthorizedCertificatesRetry();
    if (listAuthorizedCertificatesRetry != null) {
      RetrySettings listAuthorizedCertificatesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listAuthorizedCertificatesSettings().getRetrySettings(),
              listAuthorizedCertificatesRetry);
      clientSettingsBuilder
          .listAuthorizedCertificatesSettings()
          .setRetrySettings(listAuthorizedCertificatesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listAuthorizedCertificates from properties.");
      }
    }
    Retry getAuthorizedCertificateRetry = clientProperties.getGetAuthorizedCertificateRetry();
    if (getAuthorizedCertificateRetry != null) {
      RetrySettings getAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getAuthorizedCertificateSettings().getRetrySettings(),
              getAuthorizedCertificateRetry);
      clientSettingsBuilder
          .getAuthorizedCertificateSettings()
          .setRetrySettings(getAuthorizedCertificateRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getAuthorizedCertificate from properties.");
      }
    }
    Retry createAuthorizedCertificateRetry = clientProperties.getCreateAuthorizedCertificateRetry();
    if (createAuthorizedCertificateRetry != null) {
      RetrySettings createAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createAuthorizedCertificateSettings().getRetrySettings(),
              createAuthorizedCertificateRetry);
      clientSettingsBuilder
          .createAuthorizedCertificateSettings()
          .setRetrySettings(createAuthorizedCertificateRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for createAuthorizedCertificate from properties.");
      }
    }
    Retry updateAuthorizedCertificateRetry = clientProperties.getUpdateAuthorizedCertificateRetry();
    if (updateAuthorizedCertificateRetry != null) {
      RetrySettings updateAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateAuthorizedCertificateSettings().getRetrySettings(),
              updateAuthorizedCertificateRetry);
      clientSettingsBuilder
          .updateAuthorizedCertificateSettings()
          .setRetrySettings(updateAuthorizedCertificateRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for updateAuthorizedCertificate from properties.");
      }
    }
    Retry deleteAuthorizedCertificateRetry = clientProperties.getDeleteAuthorizedCertificateRetry();
    if (deleteAuthorizedCertificateRetry != null) {
      RetrySettings deleteAuthorizedCertificateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteAuthorizedCertificateSettings().getRetrySettings(),
              deleteAuthorizedCertificateRetry);
      clientSettingsBuilder
          .deleteAuthorizedCertificateSettings()
          .setRetrySettings(deleteAuthorizedCertificateRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for deleteAuthorizedCertificate from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a AuthorizedCertificatesClient bean configured with AuthorizedCertificatesSettings.
   *
   * @param authorizedCertificatesSettings settings to configure an instance of client bean.
   * @return a {@link AuthorizedCertificatesClient} bean configured with {@link
   *     AuthorizedCertificatesSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public AuthorizedCertificatesClient authorizedCertificatesClient(
      AuthorizedCertificatesSettings authorizedCertificatesSettings) throws IOException {
    return AuthorizedCertificatesClient.create(authorizedCertificatesSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-authorized-certificates";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
