/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.appengine.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.appengine.v1.DomainMappingsClient;
import com.google.appengine.v1.DomainMappingsSettings;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link DomainMappingsClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@ConditionalOnClass(DomainMappingsClient.class)
@ConditionalOnProperty(
    value = "com.google.appengine.v1.spring.auto.domain-mappings.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(DomainMappingsSpringProperties.class)
public class DomainMappingsSpringAutoConfiguration {
  private final DomainMappingsSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(DomainMappingsSpringAutoConfiguration.class);

  protected DomainMappingsSpringAutoConfiguration(
      DomainMappingsSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from DomainMappings-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Returns the default channel provider. The default is gRPC and will default to it unless the
   * useRest option is provided to use HTTP transport instead
   */
  @Bean
  @ConditionalOnMissingBean
  public TransportChannelProvider defaultDomainMappingsTransportChannelProvider() {
    return DomainMappingsSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a DomainMappingsClient bean configured to use the default credentials provider
   * (obtained with domainMappingsCredentials()) and its default transport channel provider
   * (defaultDomainMappingsTransportChannelProvider()). It also configures the quota project ID if
   * provided. It will configure an executor provider in case there is more than one thread
   * configured in the client
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in DomainMappingsSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   */
  @Bean
  @ConditionalOnMissingBean
  public DomainMappingsSettings domainMappingsSettings(
      @Qualifier("defaultDomainMappingsTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    DomainMappingsSettings.Builder clientSettingsBuilder =
        DomainMappingsSettings.newBuilder()
            .setCredentialsProvider(this.credentialsProvider)
            .setTransportChannelProvider(defaultTransportChannelProvider)
            .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          DomainMappingsSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder.setTransportChannelProvider(
          DomainMappingsSettings.defaultHttpJsonTransportProviderBuilder().build());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using HTTP transport channel");
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listDomainMappingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listDomainMappingsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listDomainMappingsSettings()
          .setRetrySettings(listDomainMappingsRetrySettings);

      RetrySettings getDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getDomainMappingSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getDomainMappingSettings()
          .setRetrySettings(getDomainMappingRetrySettings);

      RetrySettings createDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createDomainMappingSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .createDomainMappingSettings()
          .setRetrySettings(createDomainMappingRetrySettings);

      RetrySettings updateDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateDomainMappingSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .updateDomainMappingSettings()
          .setRetrySettings(updateDomainMappingRetrySettings);

      RetrySettings deleteDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteDomainMappingSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .deleteDomainMappingSettings()
          .setRetrySettings(deleteDomainMappingRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listDomainMappingsRetry = clientProperties.getListDomainMappingsRetry();
    if (listDomainMappingsRetry != null) {
      RetrySettings listDomainMappingsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listDomainMappingsSettings().getRetrySettings(),
              listDomainMappingsRetry);
      clientSettingsBuilder
          .listDomainMappingsSettings()
          .setRetrySettings(listDomainMappingsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listDomainMappings from properties.");
      }
    }
    Retry getDomainMappingRetry = clientProperties.getGetDomainMappingRetry();
    if (getDomainMappingRetry != null) {
      RetrySettings getDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getDomainMappingSettings().getRetrySettings(),
              getDomainMappingRetry);
      clientSettingsBuilder
          .getDomainMappingSettings()
          .setRetrySettings(getDomainMappingRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for getDomainMapping from properties.");
      }
    }
    Retry createDomainMappingRetry = clientProperties.getCreateDomainMappingRetry();
    if (createDomainMappingRetry != null) {
      RetrySettings createDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createDomainMappingSettings().getRetrySettings(),
              createDomainMappingRetry);
      clientSettingsBuilder
          .createDomainMappingSettings()
          .setRetrySettings(createDomainMappingRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for createDomainMapping from properties.");
      }
    }
    Retry updateDomainMappingRetry = clientProperties.getUpdateDomainMappingRetry();
    if (updateDomainMappingRetry != null) {
      RetrySettings updateDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateDomainMappingSettings().getRetrySettings(),
              updateDomainMappingRetry);
      clientSettingsBuilder
          .updateDomainMappingSettings()
          .setRetrySettings(updateDomainMappingRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for updateDomainMapping from properties.");
      }
    }
    Retry deleteDomainMappingRetry = clientProperties.getDeleteDomainMappingRetry();
    if (deleteDomainMappingRetry != null) {
      RetrySettings deleteDomainMappingRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteDomainMappingSettings().getRetrySettings(),
              deleteDomainMappingRetry);
      clientSettingsBuilder
          .deleteDomainMappingSettings()
          .setRetrySettings(deleteDomainMappingRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for deleteDomainMapping from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public DomainMappingsClient domainMappingsClient(DomainMappingsSettings domainMappingsSettings)
      throws IOException {
    return DomainMappingsClient.create(domainMappingsSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-domain-mappings";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
