/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.workflows.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.httpjson.InstantiatingHttpJsonChannelProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.spring.core.Credentials;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.global.GlobalProperties;
import com.google.cloud.workflows.v1.WorkflowsClient;
import com.google.cloud.workflows.v1.WorkflowsSettings;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link WorkflowsClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@ConditionalOnClass(WorkflowsClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.workflows.v1.spring.auto.workflows.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties({WorkflowsSpringProperties.class, GlobalProperties.class})
public class WorkflowsSpringAutoConfiguration {
  private final WorkflowsSpringProperties clientProperties;
  private final GlobalProperties globalProperties;
  private static final Log LOGGER = LogFactory.getLog(WorkflowsSpringAutoConfiguration.class);

  protected WorkflowsSpringAutoConfiguration(
      WorkflowsSpringProperties clientProperties, GlobalProperties globalProperties) {
    this.clientProperties = clientProperties;
    this.globalProperties = globalProperties;
  }

  /**
   * Obtains the default credentials provider. The used key will be obtained from Spring Boot
   * configuration data files.
   */
  @Bean
  @ConditionalOnMissingBean
  public CredentialsProvider workflowsCredentials() throws IOException {
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from Workflows-specific configuration");
      }
      return ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    }
    if (LOGGER.isTraceEnabled()) {
      LOGGER.trace("Using credentials from global configuration");
    }
    return ((CredentialsProvider) new DefaultCredentialsProvider(this.globalProperties));
  }

  /**
   * Returns the default channel provider. The default is gRPC and will default to it unless the
   * useRest option is provided to use HTTP transport instead
   */
  @Bean
  @ConditionalOnMissingBean
  public TransportChannelProvider defaultWorkflowsTransportChannelProvider() {
    return WorkflowsSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a WorkflowsClient bean configured to use the default credentials provider (obtained
   * with workflowsCredentials()) and its default transport channel provider
   * (defaultWorkflowsTransportChannelProvider()). It also configures the quota project ID if
   * provided. It will configure an executor provider in case there is more than one thread
   * configured in the client
   *
   * <p>Individual retry settings are configured as well. It will use the relevant client library's
   * default retry settings when they are not specified in WorkflowsSpringProperties.
   */
  @Bean
  @ConditionalOnMissingBean
  public WorkflowsSettings workflowsSettings(
      @Qualifier("workflowsCredentials") CredentialsProvider credentialsProvider,
      @Qualifier("defaultWorkflowsTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    WorkflowsSettings.Builder clientSettingsBuilder =
        WorkflowsSettings.newBuilder()
            .setCredentialsProvider(credentialsProvider)
            .setTransportChannelProvider(defaultTransportChannelProvider)
            .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          WorkflowsSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder.setTransportChannelProvider(
          WorkflowsSettings.defaultHttpJsonTransportProviderBuilder().build());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using HTTP transport channel");
      }
    }
    RetrySettings.Builder listWorkflowsRetrySettingBuilder =
        clientSettingsBuilder.listWorkflowsSettings().getRetrySettings().toBuilder();
    if (this.clientProperties.getListWorkflowsRpcTimeoutMultiplier() != null) {
      listWorkflowsRetrySettingBuilder.setRpcTimeoutMultiplier(
          this.clientProperties.getListWorkflowsRpcTimeoutMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "ListWorkflowsRpcTimeoutMultiplier set to "
                + this.clientProperties.getListWorkflowsRpcTimeoutMultiplier());
      }
    }
    clientSettingsBuilder
        .listWorkflowsSettings()
        .setRetrySettings(listWorkflowsRetrySettingBuilder.build());
    RetrySettings.Builder getWorkflowRetrySettingBuilder =
        clientSettingsBuilder.getWorkflowSettings().getRetrySettings().toBuilder();
    if (this.clientProperties.getGetWorkflowRpcTimeoutMultiplier() != null) {
      getWorkflowRetrySettingBuilder.setRpcTimeoutMultiplier(
          this.clientProperties.getGetWorkflowRpcTimeoutMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "GetWorkflowRpcTimeoutMultiplier set to "
                + this.clientProperties.getGetWorkflowRpcTimeoutMultiplier());
      }
    }
    clientSettingsBuilder
        .getWorkflowSettings()
        .setRetrySettings(getWorkflowRetrySettingBuilder.build());
    RetrySettings.Builder createWorkflowRetrySettingBuilder =
        clientSettingsBuilder.createWorkflowSettings().getRetrySettings().toBuilder();
    if (this.clientProperties.getCreateWorkflowRpcTimeoutMultiplier() != null) {
      createWorkflowRetrySettingBuilder.setRpcTimeoutMultiplier(
          this.clientProperties.getCreateWorkflowRpcTimeoutMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "CreateWorkflowRpcTimeoutMultiplier set to "
                + this.clientProperties.getCreateWorkflowRpcTimeoutMultiplier());
      }
    }
    clientSettingsBuilder
        .createWorkflowSettings()
        .setRetrySettings(createWorkflowRetrySettingBuilder.build());
    RetrySettings.Builder deleteWorkflowRetrySettingBuilder =
        clientSettingsBuilder.deleteWorkflowSettings().getRetrySettings().toBuilder();
    if (this.clientProperties.getDeleteWorkflowRpcTimeoutMultiplier() != null) {
      deleteWorkflowRetrySettingBuilder.setRpcTimeoutMultiplier(
          this.clientProperties.getDeleteWorkflowRpcTimeoutMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "DeleteWorkflowRpcTimeoutMultiplier set to "
                + this.clientProperties.getDeleteWorkflowRpcTimeoutMultiplier());
      }
    }
    clientSettingsBuilder
        .deleteWorkflowSettings()
        .setRetrySettings(deleteWorkflowRetrySettingBuilder.build());
    RetrySettings.Builder updateWorkflowRetrySettingBuilder =
        clientSettingsBuilder.updateWorkflowSettings().getRetrySettings().toBuilder();
    if (this.clientProperties.getUpdateWorkflowRpcTimeoutMultiplier() != null) {
      updateWorkflowRetrySettingBuilder.setRpcTimeoutMultiplier(
          this.clientProperties.getUpdateWorkflowRpcTimeoutMultiplier());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "UpdateWorkflowRpcTimeoutMultiplier set to "
                + this.clientProperties.getUpdateWorkflowRpcTimeoutMultiplier());
      }
    }
    clientSettingsBuilder
        .updateWorkflowSettings()
        .setRetrySettings(updateWorkflowRetrySettingBuilder.build());
    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public WorkflowsClient workflowsClient(WorkflowsSettings workflowsSettings) throws IOException {
    return WorkflowsClient.create(workflowsSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-workflows";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
