= Cloud Spanner R2DBC Driver Example

This sample application demonstrates performing DDL, DML, and SQL operations on https://cloud.google.com/spanner/[Google Cloud Spanner] using a the Cloud Spanner R2DBC driver.


== Setup & Configuration
1. Create a Google Cloud Platform Project
2. https://cloud.google.com/docs/authentication/getting-started#creating_the_service_account[Create a service account] with Cloud Spanner permission.
Furnish a new JSON key and then set the credentials using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
+
Alternatively, have the https://cloud.google.com/sdk/[Google Cloud SDK] installed and initialized and logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials].

3. Enable the https://console.cloud.google.com/apis/api/spanner.googleapis.com/overview[Cloud Spanner API]

4. Create a Cloud Spanner instance and database in your project and insert those details into the `SAMPLE_INSTANCE` and `SAMPLE_DATABASE` properties of `SampleApplication.java`.
Insert the project ID into the `SAMPLE_PROJECT` property.

== Run the Example
Run the example `main` method in `SampleApplication.java`.

This example creates a table of `BOOKS`.
It then opens a transaction and saves a `BOOKS` rows and reads them from the database after inserting.

The application output will show the sequence of operations:

----
 Table creation completed.
 ...
 Insert books transaction committed.
 ...
 Retrieved book: book1 Book One
 Retrieved book: book2 Book Two
----

