/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.gaming.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.gaming.v1.RealmsServiceClient;
import com.google.cloud.gaming.v1.RealmsServiceSettings;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link RealmsServiceClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@ConditionalOnClass(RealmsServiceClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.gaming.v1.spring.auto.realms-service.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(RealmsServiceSpringProperties.class)
public class RealmsServiceSpringAutoConfiguration {
  private final RealmsServiceSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER = LogFactory.getLog(RealmsServiceSpringAutoConfiguration.class);

  protected RealmsServiceSpringAutoConfiguration(
      RealmsServiceSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from RealmsService-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Returns the default channel provider. The default is gRPC and will default to it unless the
   * useRest option is provided to use HTTP transport instead
   */
  @Bean
  @ConditionalOnMissingBean
  public TransportChannelProvider defaultRealmsServiceTransportChannelProvider() {
    return RealmsServiceSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a RealmsServiceClient bean configured to use the default credentials provider
   * (obtained with realmsServiceCredentials()) and its default transport channel provider
   * (defaultRealmsServiceTransportChannelProvider()). It also configures the quota project ID if
   * provided. It will configure an executor provider in case there is more than one thread
   * configured in the client
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in RealmsServiceSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   */
  @Bean
  @ConditionalOnMissingBean
  public RealmsServiceSettings realmsServiceSettings(
      @Qualifier("defaultRealmsServiceTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    RealmsServiceSettings.Builder clientSettingsBuilder =
        RealmsServiceSettings.newBuilder()
            .setCredentialsProvider(this.credentialsProvider)
            .setTransportChannelProvider(defaultTransportChannelProvider)
            .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          RealmsServiceSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    if (this.clientProperties.getUseRest()) {
      clientSettingsBuilder.setTransportChannelProvider(
          RealmsServiceSettings.defaultHttpJsonTransportProviderBuilder().build());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using HTTP transport channel");
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings listRealmsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listRealmsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listRealmsSettings().setRetrySettings(listRealmsRetrySettings);

      RetrySettings getRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getRealmSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getRealmSettings().setRetrySettings(getRealmRetrySettings);

      RetrySettings createRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createRealmSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.createRealmSettings().setRetrySettings(createRealmRetrySettings);

      RetrySettings deleteRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteRealmSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.deleteRealmSettings().setRetrySettings(deleteRealmRetrySettings);

      RetrySettings updateRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateRealmSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.updateRealmSettings().setRetrySettings(updateRealmRetrySettings);

      RetrySettings previewRealmUpdateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.previewRealmUpdateSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .previewRealmUpdateSettings()
          .setRetrySettings(previewRealmUpdateRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry listRealmsRetry = clientProperties.getListRealmsRetry();
    if (listRealmsRetry != null) {
      RetrySettings listRealmsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listRealmsSettings().getRetrySettings(), listRealmsRetry);
      clientSettingsBuilder.listRealmsSettings().setRetrySettings(listRealmsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listRealms from properties.");
      }
    }
    Retry getRealmRetry = clientProperties.getGetRealmRetry();
    if (getRealmRetry != null) {
      RetrySettings getRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getRealmSettings().getRetrySettings(), getRealmRetry);
      clientSettingsBuilder.getRealmSettings().setRetrySettings(getRealmRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getRealm from properties.");
      }
    }
    Retry createRealmRetry = clientProperties.getCreateRealmRetry();
    if (createRealmRetry != null) {
      RetrySettings createRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.createRealmSettings().getRetrySettings(), createRealmRetry);
      clientSettingsBuilder.createRealmSettings().setRetrySettings(createRealmRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for createRealm from properties.");
      }
    }
    Retry deleteRealmRetry = clientProperties.getDeleteRealmRetry();
    if (deleteRealmRetry != null) {
      RetrySettings deleteRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.deleteRealmSettings().getRetrySettings(), deleteRealmRetry);
      clientSettingsBuilder.deleteRealmSettings().setRetrySettings(deleteRealmRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for deleteRealm from properties.");
      }
    }
    Retry updateRealmRetry = clientProperties.getUpdateRealmRetry();
    if (updateRealmRetry != null) {
      RetrySettings updateRealmRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateRealmSettings().getRetrySettings(), updateRealmRetry);
      clientSettingsBuilder.updateRealmSettings().setRetrySettings(updateRealmRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for updateRealm from properties.");
      }
    }
    Retry previewRealmUpdateRetry = clientProperties.getPreviewRealmUpdateRetry();
    if (previewRealmUpdateRetry != null) {
      RetrySettings previewRealmUpdateRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.previewRealmUpdateSettings().getRetrySettings(),
              previewRealmUpdateRetry);
      clientSettingsBuilder
          .previewRealmUpdateSettings()
          .setRetrySettings(previewRealmUpdateRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for previewRealmUpdate from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  @Bean
  @ConditionalOnMissingBean
  public RealmsServiceClient realmsServiceClient(RealmsServiceSettings realmsServiceSettings)
      throws IOException {
    return RealmsServiceClient.create(realmsServiceSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-realms-service";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
