name: Build And Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * *' # 09:30 UTC every day


jobs:
  unitTests:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: |
      github.repository == 'GoogleCloudPlatform/spring-cloud-gcp' &&
      (
        github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != 'GoogleCloudPlatform/spring-cloud-gcp'
      )
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 15]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Mvn install # Need this when the directory/pom structure changes
      run: |
        ./mvnw \
          --batch-mode \
          --show-version \
          --threads 1.5C \
          --define maven.test.skip=true \
          --define maven.javadoc.skip=true \
          install

    - name: Unit Tests
      run: |
        ./mvnw \
          --batch-mode \
          --fail-at-end \
          --threads 1.5C \
          test
    - name: Archive logs
      if: always()
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Logs - Java ${{ matrix.java }}
        path: "**/target/surefire-reports/*"


  integrationTests:
    if: |
      github.repository == 'GoogleCloudPlatform/spring-cloud-gcp' &&
      (
        github.event_name == 'push' ||
        github.event_name == 'schedule'
      )
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        it:
          - bigquery
          - config
          - datastore
          - firestore
          - logging
          - metrics
          - kotlin
          - pubsub
          - pubsub-emulator
          - secretmanager
          - spanner
          - storage
          - trace
          - vision
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: latest
          project_id: spring-cloud-gcp-ci
          service_account_key: ${{ secrets.SPRING_CLOUD_GCP_CI_SA_KEY }}
          export_default_credentials: true
      - name: Install pubsub-emulator
        if: ${{ matrix.it == 'pubsub-emulator' }}
        run: |
          gcloud components install pubsub-emulator beta && \
            gcloud components update

      - name: Mvn install # Need this when the directory/pom structure changes
        run: |
          ./mvnw \
            --batch-mode \
            --threads 1.5C \
            --define maven.test.skip=true \
            --define maven.javadoc.skip=true \
            install

      - name: Wait our turn for running integration tests
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          continue-after-seconds: 1200 # 30 min
      - name: Integration Tests
        run: |
          ./mvnw \
            --batch-mode \
            --activate-profiles spring-cloud-gcp-ci-it \
            --define maven.javadoc.skip=true \
            --define skip.surefire.tests=true \
            --define it.${{ matrix.it }}=true \
            verify
      - name: Archive logs
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Integration Test Logs - ${{ matrix.it}}
          path: "**/target/failsafe-reports/*"


  releaseCheck:
    if: |
      github.repository == 'GoogleCloudPlatform/spring-cloud-gcp' &&
      (
        github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != 'GoogleCloudPlatform/spring-cloud-gcp'
      )
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: releaseCheck
        run: |
          ./mvnw \
            --batch-mode \
            -Drelease=true \
            -DskipTests \
            -Dgpg.skip \
            -Dcheckstyle.skip \
            clean \
            package
      - name: docsCheck
        run: |
          ./mvnw \
            --batch-mode \
            --activate-profiles docs,spring \
            -DskipTests \
            -Dgpg.skip \
            -Dcheckstyle.skip \
            --projects docs \
            clean \
            package
      - name: Archive Artifacts
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Release Artifacts
          path: |
            **/.flattened-pom.xml
            **/target/**.jar
            target/site/apidocs
            **/target/generated-docs
            !spring-cloud-gcp-samples


  linkageCheck:
    if: |
      github.repository == 'GoogleCloudPlatform/spring-cloud-gcp' &&
      (
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'schedule'
      )
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: install
        # install before running Linkage Checker
        run: |
          ./mvnw \
             --batch-mode \
             --show-version \
             --threads 1.5C \
             --define skipTests=true \
             --define maven.javadoc.skip=true \
             --errors \
             install
      - name: run linkage checker
        run: |
          ./mvnw \
            --activate-profiles linkage-check \
            --batch-mode \
            --show-version \
            --threads 1.5C \
            --define skipTests=true \
            --define maven.javadoc.skip=true \
            --errors \
            verify
