name: Linkage Check

on:
  pull_request:
    branches:
      - 'dependabot/**'
  workflow_dispatch:
  schedule:
    - cron: '00 9 * * *' # 09:00 UTC every day

jobs:
  linkageCheck:
    if: |
      ((
        github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name
      ) || (github.event_name != 'pull_request'))
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d' --utc)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - uses: actions/cache@v4
        id: mvn-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.date }}
      - name: install
        # install before running Linkage Checker
        run: |
          ./mvnw \
             --batch-mode \
             --no-transfer-progress \
             --show-version \
             --threads 1.5C \
             --define skipTests=true \
             --define maven.javadoc.skip=true \
             --errors \
             install
      - name: run linkage checker
        run: |
          ./mvnw \
            --activate-profiles linkage-check \
            --projects spring-cloud-gcp-dependencies \
            --batch-mode \
            --no-transfer-progress \
            --show-version \
            --threads 1.5C \
            --define skipTests=true \
            --define maven.javadoc.skip=true \
            --errors \
            verify
