name: Warm Caches
on:
  workflow_dispatch:
  schedule:
    - cron: '1 0 * * *' # 00:01 UTC every day

jobs:
  warmCache:
    if: github.repository == 'GoogleCloudPlatform/spring-cloud-gcp' # Only run on upstream branch
    name: Warm Cache
    runs-on: ubuntu-20.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d' --utc)"

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        id: loadCache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ steps.date.outputs.date }}

      - name: Fail if cache already warm
        if: steps.loadCache.outputs.cache-hit == 'true'
        run: /bin/false # Do nothing, unsuccessfully.

      - uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ steps.date.outputs.date }}

      - name: Mvn install
        id: install1
        continue-on-error: true
        run: |
          ./mvnw \
            --batch-mode \
            --threads 1.5C \
            --define maven.test.skip=true \
            --define maven.javadoc.skip=true \
            install

      - name: Retry install1 on Failure
        id: install2
        if: steps.install1.outcome == 'failure'
        continue-on-error: true
        run: |
          ./mvnw \
            --batch-mode \
            --threads 1.5C \
            --define maven.test.skip=true \
            --define maven.javadoc.skip=true \
            install

      - name: Retry install2 on Failure
        id: install3
        if: steps.install2.outcome == 'failure'
        continue-on-error: true
        run: |
          ./mvnw \
            --batch-mode \
            --threads 1.5C \
            --define maven.test.skip=true \
            --define maven.javadoc.skip=true \
            install

      - name: Grab Sonar dependencies
        id: sonar1
        continue-on-error: true
        run: ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:help

      - name: Retry Sonar dependencies
        id: sonar2
        if: steps.sonar1.outcome == 'failure'
        continue-on-error: true
        run: ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:help

