/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.cloud.aiplatform.v1.spring;

import com.google.api.core.BetaApi;
import com.google.api.gax.core.CredentialsProvider;
import com.google.api.gax.core.ExecutorProvider;
import com.google.api.gax.retrying.RetrySettings;
import com.google.api.gax.rpc.HeaderProvider;
import com.google.api.gax.rpc.TransportChannelProvider;
import com.google.cloud.aiplatform.v1.FeaturestoreServiceClient;
import com.google.cloud.aiplatform.v1.FeaturestoreServiceSettings;
import com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration;
import com.google.cloud.spring.core.DefaultCredentialsProvider;
import com.google.cloud.spring.core.Retry;
import com.google.cloud.spring.core.util.RetryUtil;
import java.io.IOException;
import java.util.Collections;
import javax.annotation.Generated;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

// AUTO-GENERATED DOCUMENTATION AND CLASS.
/**
 * Auto-configuration for {@link FeaturestoreServiceClient}.
 *
 * <p>Provides auto-configuration for Spring Boot
 *
 * <p>The default instance has everything set to sensible defaults:
 *
 * <ul>
 *   <li>The default transport provider is used.
 *   <li>Credentials are acquired automatically through Application Default Credentials.
 *   <li>Retries are configured for idempotent methods but not for non-idempotent methods.
 * </ul>
 */
@Generated("by google-cloud-spring-generator")
@BetaApi("Autogenerated Spring autoconfiguration is not yet stable")
@AutoConfiguration
@AutoConfigureAfter(GcpContextAutoConfiguration.class)
@ConditionalOnClass(FeaturestoreServiceClient.class)
@ConditionalOnProperty(
    value = "com.google.cloud.aiplatform.v1.featurestore-service.enabled",
    matchIfMissing = true)
@EnableConfigurationProperties(FeaturestoreServiceSpringProperties.class)
public class FeaturestoreServiceSpringAutoConfiguration {
  private final FeaturestoreServiceSpringProperties clientProperties;
  private final CredentialsProvider credentialsProvider;
  private static final Log LOGGER =
      LogFactory.getLog(FeaturestoreServiceSpringAutoConfiguration.class);

  protected FeaturestoreServiceSpringAutoConfiguration(
      FeaturestoreServiceSpringProperties clientProperties, CredentialsProvider credentialsProvider)
      throws IOException {
    this.clientProperties = clientProperties;
    if (this.clientProperties.getCredentials().hasKey()) {
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Using credentials from FeaturestoreService-specific configuration");
      }
      this.credentialsProvider =
          ((CredentialsProvider) new DefaultCredentialsProvider(this.clientProperties));
    } else {
      this.credentialsProvider = credentialsProvider;
    }
  }

  /**
   * Provides a default transport channel provider bean, corresponding to the client library's
   * default transport channel provider. If the library supports both GRPC and REST transport, and
   * the useRest property is configured, the HTTP/JSON transport provider will be used instead of
   * GRPC.
   *
   * @return a default transport channel provider.
   */
  @Bean
  @ConditionalOnMissingBean(name = "defaultFeaturestoreServiceTransportChannelProvider")
  public TransportChannelProvider defaultFeaturestoreServiceTransportChannelProvider() {
    return FeaturestoreServiceSettings.defaultTransportChannelProvider();
  }

  /**
   * Provides a FeaturestoreServiceSettings bean configured to use a DefaultCredentialsProvider and
   * the client library's default transport channel provider
   * (defaultFeaturestoreServiceTransportChannelProvider()). It also configures the quota project ID
   * and executor thread count, if provided through properties.
   *
   * <p>Retry settings are also configured from service-level and method-level properties specified
   * in FeaturestoreServiceSpringProperties. Method-level properties will take precedence over
   * service-level properties if available, and client library defaults will be used if neither are
   * specified.
   *
   * @param defaultTransportChannelProvider TransportChannelProvider to use in the settings.
   * @return a {@link FeaturestoreServiceSettings} bean configured with {@link
   *     TransportChannelProvider} bean.
   */
  @Bean
  @ConditionalOnMissingBean
  public FeaturestoreServiceSettings featurestoreServiceSettings(
      @Qualifier("defaultFeaturestoreServiceTransportChannelProvider")
          TransportChannelProvider defaultTransportChannelProvider)
      throws IOException {
    FeaturestoreServiceSettings.Builder clientSettingsBuilder =
        FeaturestoreServiceSettings.newBuilder();
    clientSettingsBuilder
        .setCredentialsProvider(this.credentialsProvider)
        .setTransportChannelProvider(defaultTransportChannelProvider)
        .setHeaderProvider(this.userAgentHeaderProvider());
    if (this.clientProperties.getQuotaProjectId() != null) {
      clientSettingsBuilder.setQuotaProjectId(this.clientProperties.getQuotaProjectId());
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Quota project id set to "
                + this.clientProperties.getQuotaProjectId()
                + ", this overrides project id from credentials.");
      }
    }
    if (this.clientProperties.getExecutorThreadCount() != null) {
      ExecutorProvider executorProvider =
          FeaturestoreServiceSettings.defaultExecutorProviderBuilder()
              .setExecutorThreadCount(this.clientProperties.getExecutorThreadCount())
              .build();
      clientSettingsBuilder.setBackgroundExecutorProvider(executorProvider);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Background executor thread count is "
                + this.clientProperties.getExecutorThreadCount());
      }
    }
    Retry serviceRetry = clientProperties.getRetry();
    if (serviceRetry != null) {
      RetrySettings getFeaturestoreRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFeaturestoreSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .getFeaturestoreSettings()
          .setRetrySettings(getFeaturestoreRetrySettings);

      RetrySettings listFeaturestoresRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFeaturestoresSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listFeaturestoresSettings()
          .setRetrySettings(listFeaturestoresRetrySettings);

      RetrySettings getEntityTypeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getEntityTypeSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getEntityTypeSettings().setRetrySettings(getEntityTypeRetrySettings);

      RetrySettings listEntityTypesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listEntityTypesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .listEntityTypesSettings()
          .setRetrySettings(listEntityTypesRetrySettings);

      RetrySettings updateEntityTypeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateEntityTypeSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .updateEntityTypeSettings()
          .setRetrySettings(updateEntityTypeRetrySettings);

      RetrySettings getFeatureRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFeatureSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getFeatureSettings().setRetrySettings(getFeatureRetrySettings);

      RetrySettings listFeaturesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFeaturesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listFeaturesSettings().setRetrySettings(listFeaturesRetrySettings);

      RetrySettings updateFeatureRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateFeatureSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.updateFeatureSettings().setRetrySettings(updateFeatureRetrySettings);

      RetrySettings searchFeaturesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.searchFeaturesSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.searchFeaturesSettings().setRetrySettings(searchFeaturesRetrySettings);

      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);

      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);

      RetrySettings setIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setIamPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.setIamPolicySettings().setRetrySettings(setIamPolicyRetrySettings);

      RetrySettings getIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getIamPolicySettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder.getIamPolicySettings().setRetrySettings(getIamPolicyRetrySettings);

      RetrySettings testIamPermissionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.testIamPermissionsSettings().getRetrySettings(), serviceRetry);
      clientSettingsBuilder
          .testIamPermissionsSettings()
          .setRetrySettings(testIamPermissionsRetrySettings);

      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured service-level retry settings from properties.");
      }
    }
    Retry getFeaturestoreRetry = clientProperties.getGetFeaturestoreRetry();
    if (getFeaturestoreRetry != null) {
      RetrySettings getFeaturestoreRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFeaturestoreSettings().getRetrySettings(),
              getFeaturestoreRetry);
      clientSettingsBuilder
          .getFeaturestoreSettings()
          .setRetrySettings(getFeaturestoreRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getFeaturestore from properties.");
      }
    }
    Retry listFeaturestoresRetry = clientProperties.getListFeaturestoresRetry();
    if (listFeaturestoresRetry != null) {
      RetrySettings listFeaturestoresRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFeaturestoresSettings().getRetrySettings(),
              listFeaturestoresRetry);
      clientSettingsBuilder
          .listFeaturestoresSettings()
          .setRetrySettings(listFeaturestoresRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for listFeaturestores from properties.");
      }
    }
    Retry getEntityTypeRetry = clientProperties.getGetEntityTypeRetry();
    if (getEntityTypeRetry != null) {
      RetrySettings getEntityTypeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getEntityTypeSettings().getRetrySettings(), getEntityTypeRetry);
      clientSettingsBuilder.getEntityTypeSettings().setRetrySettings(getEntityTypeRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getEntityType from properties.");
      }
    }
    Retry listEntityTypesRetry = clientProperties.getListEntityTypesRetry();
    if (listEntityTypesRetry != null) {
      RetrySettings listEntityTypesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listEntityTypesSettings().getRetrySettings(),
              listEntityTypesRetry);
      clientSettingsBuilder
          .listEntityTypesSettings()
          .setRetrySettings(listEntityTypesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listEntityTypes from properties.");
      }
    }
    Retry updateEntityTypeRetry = clientProperties.getUpdateEntityTypeRetry();
    if (updateEntityTypeRetry != null) {
      RetrySettings updateEntityTypeRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateEntityTypeSettings().getRetrySettings(),
              updateEntityTypeRetry);
      clientSettingsBuilder
          .updateEntityTypeSettings()
          .setRetrySettings(updateEntityTypeRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for updateEntityType from properties.");
      }
    }
    Retry getFeatureRetry = clientProperties.getGetFeatureRetry();
    if (getFeatureRetry != null) {
      RetrySettings getFeatureRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getFeatureSettings().getRetrySettings(), getFeatureRetry);
      clientSettingsBuilder.getFeatureSettings().setRetrySettings(getFeatureRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getFeature from properties.");
      }
    }
    Retry listFeaturesRetry = clientProperties.getListFeaturesRetry();
    if (listFeaturesRetry != null) {
      RetrySettings listFeaturesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listFeaturesSettings().getRetrySettings(), listFeaturesRetry);
      clientSettingsBuilder.listFeaturesSettings().setRetrySettings(listFeaturesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listFeatures from properties.");
      }
    }
    Retry updateFeatureRetry = clientProperties.getUpdateFeatureRetry();
    if (updateFeatureRetry != null) {
      RetrySettings updateFeatureRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.updateFeatureSettings().getRetrySettings(), updateFeatureRetry);
      clientSettingsBuilder.updateFeatureSettings().setRetrySettings(updateFeatureRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for updateFeature from properties.");
      }
    }
    Retry searchFeaturesRetry = clientProperties.getSearchFeaturesRetry();
    if (searchFeaturesRetry != null) {
      RetrySettings searchFeaturesRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.searchFeaturesSettings().getRetrySettings(),
              searchFeaturesRetry);
      clientSettingsBuilder.searchFeaturesSettings().setRetrySettings(searchFeaturesRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for searchFeatures from properties.");
      }
    }
    Retry listLocationsRetry = clientProperties.getListLocationsRetry();
    if (listLocationsRetry != null) {
      RetrySettings listLocationsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.listLocationsSettings().getRetrySettings(), listLocationsRetry);
      clientSettingsBuilder.listLocationsSettings().setRetrySettings(listLocationsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for listLocations from properties.");
      }
    }
    Retry getLocationRetry = clientProperties.getGetLocationRetry();
    if (getLocationRetry != null) {
      RetrySettings getLocationRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getLocationSettings().getRetrySettings(), getLocationRetry);
      clientSettingsBuilder.getLocationSettings().setRetrySettings(getLocationRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getLocation from properties.");
      }
    }
    Retry setIamPolicyRetry = clientProperties.getSetIamPolicyRetry();
    if (setIamPolicyRetry != null) {
      RetrySettings setIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.setIamPolicySettings().getRetrySettings(), setIamPolicyRetry);
      clientSettingsBuilder.setIamPolicySettings().setRetrySettings(setIamPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for setIamPolicy from properties.");
      }
    }
    Retry getIamPolicyRetry = clientProperties.getGetIamPolicyRetry();
    if (getIamPolicyRetry != null) {
      RetrySettings getIamPolicyRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.getIamPolicySettings().getRetrySettings(), getIamPolicyRetry);
      clientSettingsBuilder.getIamPolicySettings().setRetrySettings(getIamPolicyRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace("Configured method-level retry settings for getIamPolicy from properties.");
      }
    }
    Retry testIamPermissionsRetry = clientProperties.getTestIamPermissionsRetry();
    if (testIamPermissionsRetry != null) {
      RetrySettings testIamPermissionsRetrySettings =
          RetryUtil.updateRetrySettings(
              clientSettingsBuilder.testIamPermissionsSettings().getRetrySettings(),
              testIamPermissionsRetry);
      clientSettingsBuilder
          .testIamPermissionsSettings()
          .setRetrySettings(testIamPermissionsRetrySettings);
      if (LOGGER.isTraceEnabled()) {
        LOGGER.trace(
            "Configured method-level retry settings for testIamPermissions from properties.");
      }
    }
    return clientSettingsBuilder.build();
  }

  /**
   * Provides a FeaturestoreServiceClient bean configured with FeaturestoreServiceSettings.
   *
   * @param featurestoreServiceSettings settings to configure an instance of client bean.
   * @return a {@link FeaturestoreServiceClient} bean configured with {@link
   *     FeaturestoreServiceSettings}
   */
  @Bean
  @ConditionalOnMissingBean
  public FeaturestoreServiceClient featurestoreServiceClient(
      FeaturestoreServiceSettings featurestoreServiceSettings) throws IOException {
    return FeaturestoreServiceClient.create(featurestoreServiceSettings);
  }

  private HeaderProvider userAgentHeaderProvider() {
    String springLibrary = "spring-autogen-featurestore-service";
    String version = this.getClass().getPackage().getImplementationVersion();
    return () -> Collections.singletonMap("user-agent", springLibrary + "/" + version);
  }
}
